Repository primefaces/primefaces, pull requests merged in 2018-03, with the labels that each got.

#3224 Update hazelcast lib
  pom.xml
Labels: enhancement

#3220 Update rome tools to 1.9.0
  pom.xml
Labels: enhancement

#3147 Greedy
  src/main/java/org/primefaces/component/dnd/DroppableRenderer.java
  src/main/resources-maven-jsf/ui/droppable.xml
Labels: new feature

#3094 isValueBlank: better implementation
  src/main/java/org/primefaces/util/ComponentUtils.java
Labels: enhancement

#3142 Fix #3141 - Move InputRenderer methods to SelectRenderer
  src/main/java/org/primefaces/renderkit/InputRenderer.java
  src/main/java/org/primefaces/renderkit/SelectRenderer.java
Labels: new feature

#3133 Fixes #2749 - p:button does not use nested f:param when using href attribute
  src/main/java/org/primefaces/renderkit/CoreRenderer.java
  src/main/java/org/primefaces/renderkit/OutcomeTargetRenderer.java
  src/main/java/org/primefaces/util/ComponentUtils.java
  src/test/java/org/primefaces/util/ComponentUtilsTest.java
Labels: new feature

#3037 Fix #3029 - strengthen the focus function in core.js
  src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: defect, enhancement

#3247 Fix #3246 https://github.com/primefaces/primefaces/issues/3246
  src/main/java/org/primefaces/component/signature/SignatureRenderer.java
  src/main/resources/META-INF/resources/primefaces/signature/signature.css
  src/main/resources/META-INF/resources/primefaces/signature/signature.js
Labels: new feature

#2876 Fix #2331: SelectOneMenu added keyup/keydown for Editable.
  src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
Labels: defect, enhancement

#3031 Fix #2583, Fix #2584 - disable sortable on transfer start until save state is fi…
  src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: defect, enhancement

#3010 Fix #2795: Schedule use description for tooltip.
  src/main/resources/META-INF/resources/primefaces/schedule/schedule.js
Labels: new feature

#3013 Fix #232: Schedule localization of 'weekNumberTitle'.
  src/main/resources/META-INF/resources/primefaces/core/core.js
  src/main/resources/META-INF/resources/primefaces/schedule/schedule.js
Labels: new feature

#3023 #3022 Configure the default values for the time slider in calendar
  src/main/java/org/primefaces/component/calendar/CalendarRenderer.java
  src/main/resources-maven-jsf/ui/calendar.xml
Labels: new feature
