Repository primefaces/primefaces, pull requests merged in 2021-03, with the labels that each got.

#7035 Fix #7032: Slider handle AZERTY keyboard and prevent duplicate -/.
  src/main/resources/META-INF/resources/primefaces/slider/slider.js
Labels: pending-review

#7030 Fix #7028: Textarea ENTER do not close editor
  src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: enhancement, pending-review

#7047 Fix #7044/#7045: SelectOne default to value when no label
  src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
Labels: pending-review

#7064 Fix #6940: InputNumber firing change event when value not changed
  src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: pending-review

#7085 Fix #7079/#7082: CascadeSelect NPE or incorrect label displayed
  src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java
Labels: pending-review

#7084 Fix #7083: CascadeSelect enable/disable widget methods
  docs/10_0_0/components/cascadeselect.md
  src/main/resources/META-INF/resources/primefaces/forms/forms.cascadeselect.js
Labels: enhancement

#7080 Fix #7078: CommandButton rendering multiple onclick DOM attributes
  src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
Labels: pending-review

#7095 Fix #7086: CellEdit focus revert #6187
  src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: pending-review

#7069 Fix #7065: Password align feedback panel and input width
  src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
Labels: pending-review

#6861 Fix #6860 - Core: migrate String nullity check with LangUtils
  src/main/java/org/primefaces/PrimeFaces.java
  src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java
  src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java
  src/main/java/org/primefaces/application/resource/QRCodeHandler.java
  src/main/java/org/primefaces/clientwindow/PrimeClientWindow.java
  src/main/java/org/primefaces/component/api/UITable.java
  src/main/java/org/primefaces/component/api/Widget.java
  src/main/java/org/primefaces/component/button/Button.java
  src/main/java/org/primefaces/component/commandbutton/CommandButton.java
  src/main/java/org/primefaces/component/datatable/DataTable.java
  src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  src/main/java/org/primefaces/component/dataview/DataView.java
  src/main/java/org/primefaces/component/export/DataExporter.java
  src/main/java/org/primefaces/component/headerrow/HeaderRowRenderer.java
  src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java
  src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
  src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  src/main/java/org/primefaces/component/password/Password.java
  src/main/java/org/primefaces/component/password/PasswordRenderer.java
  src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java
  src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
  src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  src/main/java/org/primefaces/component/timeline/TimelineRenderer.java
  src/main/java/org/primefaces/component/tristatecheckbox/TriStateCheckboxRenderer.java
  src/main/java/org/primefaces/config/WebXmlParser.java
  src/main/java/org/primefaces/context/PrimePartialResponseWriter.java
  src/main/java/org/primefaces/expression/SearchExpressionFacade.java
  src/main/java/org/primefaces/model/DefaultScheduleModel.java
  src/main/java/org/primefaces/renderkit/InputRenderer.java
  src/main/java/org/primefaces/util/AjaxRequestBuilder.java
  src/main/java/org/primefaces/util/CSVBuilder.java
  src/main/java/org/primefaces/util/CalendarUtils.java
  src/main/java/org/primefaces/util/EscapeUtils.java
  src/main/java/org/primefaces/util/LangUtils.java
  src/main/java/org/primefaces/util/ResourceUtils.java
Labels: enhancement

#7017 Fix #10/#7018 Treetable exporter (based on Datatable exporter)
  src/main/java/org/primefaces/component/export/DataExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableCSVExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableExcelExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableExcelXExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableExcelXStreamExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableExporterFactory.java
  src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
  src/main/java/org/primefaces/component/treetable/export/TreeTableXMLExporter.java
Labels: new feature
