Repository primefaces/primefaces, pull requests merged in 2021-02, with the labels that each got.

#6914 Fix #6912: FileUpload global attribute
  docs/10_0_0/components/fileupload.md
  src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
  src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
Labels: pending-review

#6753 Fix #6752: LetterAvatar port of dynamic color and label
  docs/10_0_0/components/avatar.md
  src/main/java/org/primefaces/component/avatar/Avatar.java
  src/main/java/org/primefaces/component/avatar/AvatarBase.java
  src/main/java/org/primefaces/component/avatar/AvatarRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
  src/main/resources/META-INF/resources/primefaces/avatar/avatar.css
Labels: enhancement, pending-review

#6751 Fix #6750: Avatar added Gravatar support
  docs/10_0_0/components/avatar.md
  src/main/java/org/primefaces/component/avatar/AvatarBase.java
  src/main/java/org/primefaces/component/avatar/AvatarRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement, pending-review

#6976 #6967: GraphicImage docs for byte[]/InputStream
  docs/10_0_0/components/graphicimage.md
Labels: documentation

#6981 #6973: Disable CSS animations globally
  src/main/resources/META-INF/resources/primefaces/core/core.js
  src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: pending-review

#6989 Password specific styles
  src/main/java/org/primefaces/component/password/Password.java
  src/main/java/org/primefaces/component/password/PasswordRenderer.java
  src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: pending-review

#7013 Fix #7012: Slider add min max range functionality
  docs/10_0_0/components/slider.md
  docs/migrationguide/10_0_0.md
  src/main/java/org/primefaces/component/slider/Slider.java
  src/main/java/org/primefaces/component/slider/SliderBase.java
  src/main/java/org/primefaces/component/slider/SliderRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
  src/main/resources/META-INF/resources/primefaces/slider/slider.js
Labels: enhancement

#6370 Fix #5014: Wrong calculation of width for scrollable tables
  src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: defect, pending-review

#7010 Fix for #7008 - DataScroller with SelectBooleanCheckbox: Initial checked value is overwritten for loaded chunks during first decode
  src/main/java/org/primefaces/component/api/UIData.java
  src/main/java/org/primefaces/component/datascroller/DataScroller.java
Labels: pending-review

#7031 Fix #7029: LinkButton allow content
  src/main/java/org/primefaces/component/linkbutton/LinkButton.java
  src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java
Labels: enhancement

#7019 Fix #7020: TriStateCheckbox add 'escape' attribute
  docs/10_0_0/components/tristatecheckbox.md
  src/main/java/org/primefaces/component/tristatecheckbox/TriStateCheckboxBase.java
  src/main/java/org/primefaces/component/tristatecheckbox/TriStateCheckboxRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: new feature

#7014 #6995: Server side localization
  src/main/resources/org/primefaces/Messages_cs.properties
  src/main/resources/org/primefaces/Messages_de.properties
  src/main/resources/org/primefaces/Messages_el.properties
  src/main/resources/org/primefaces/Messages_es.properties
  src/main/resources/org/primefaces/Messages_fr.properties
  src/main/resources/org/primefaces/Messages_it.properties
  src/main/resources/org/primefaces/Messages_ka.properties
  src/main/resources/org/primefaces/Messages_lv.properties
  src/main/resources/org/primefaces/Messages_nl.properties
  src/main/resources/org/primefaces/Messages_pl.properties
  src/main/resources/org/primefaces/Messages_pt.properties
  src/main/resources/org/primefaces/Messages_ro.properties
  src/main/resources/org/primefaces/Messages_ru.properties
  src/main/resources/org/primefaces/Messages_sk.properties
  src/main/resources/org/primefaces/Messages_tr.properties
Labels: pending-review

#7033 Fix #7026 - Datatable: SelectOneMenu has wrong value after filtering
  src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java
Labels: pending-review

#7037 Fix #6943: Timeline grouping with lazy load
  src/main/java/org/primefaces/component/timeline/TimelineRenderer.java
Labels: pending-review
