Repository primefaces/primefaces, pull requests merged in 2021-09, with the labels that each got.

#7800 PrimeFlex documentation to point to WebJars
  docs/10_0_0/core/responsive.md
  docs/11_0_0/core/responsive.md
  primefaces-showcase/src/main/webapp/primeflex/setup.xhtml
  primefaces-showcase/src/main/webapp/ui/panel/flexGrid.xhtml
Labels: documentation

#7825 New Component: SpeedDial
  docs/11_0_0/components/speeddial.md
  pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/button/SpeedDialView.java
  primefaces-showcase/src/main/webapp/ui/button/speedDial.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDial.java
  primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDialBase.java
  primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDialRenderer.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/speeddial/speeddial.css
  primefaces/src/main/resources/META-INF/resources/primefaces/speeddial/speeddial.js
Labels: new feature

#7857 Documentation updates for nullSortOrder
  docs/10_0_0/components/column.md
  docs/10_0_0/components/columns.md
  docs/11_0_0/components/column.md
  docs/11_0_0/components/columns.md
  docs/7_0/components/datatable.md
  docs/8_0/components/datatable.md
  primefaces-showcase/pom.xml
Labels: documentation

#7283 Fix #7279: FileUpload: Add dropZone attribute
  docs/11_0_0/components/fileupload.md
  docs/11_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/file/FileUploadView.java
  primefaces-showcase/src/main/webapp/ui/file/upload/dnd.xhtml
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: pending-review

#7895 Doc: FileDownload: Monitor Status improvement
  docs/10_0_0/components/filedownload.md
  docs/11_0_0/components/filedownload.md
Labels: documentation
