Repository primefaces/primefaces, pull requests merged in 2021-01, with the labels that each got.

#6837 Fix #6485: FullCalendar 5.5.1
  docs/10_0_0/core/thirdpartylibs.md
  src/main/resources/META-INF/resources/primefaces/schedule/build/package.json
  src/main/resources/META-INF/resources/primefaces/schedule/fullcalendar.min.js
Labels: defect, dependencies

#6859 Fix #6858: update vis.js libraries
  docs/10_0_0/core/thirdpartylibs.md
  src/main/resources/META-INF/resources/primefaces/timeline/0-timeline.min.js
  src/main/resources/META-INF/resources/primefaces/timeline/timeline.css
Labels: defect

#6347 Fix #4928: BreadCrumb: accessibility
  src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java
  src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  src/main/java/org/primefaces/util/HTML.java
Labels: theme

#6883 Fix #6882: Divider can be used in menus as separator
  docs/10_0_0/components/divider.md
  src/main/java/org/primefaces/component/divider/DividerBase.java
  src/main/java/org/primefaces/component/divider/DividerRenderer.java
  src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement

#6886 Fix #6870 BreadCrumb: should not render separators in HTML
  src/main/java/org/primefaces/component/breadcrumb/BreadCrumb.java
  src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java
  src/main/resources/META-INF/resources/primefaces-saga/theme.css
Labels: pending-review

#6894 Fix #6873: Use capitalCase field if headerText/facet is null
  src/main/java/org/primefaces/component/column/Column.java
  src/main/java/org/primefaces/component/columns/Columns.java
  src/main/java/org/primefaces/util/LangUtils.java
  src/test/java/org/primefaces/util/LangUtilsTest.java
Labels: enhancement

#6903 Fix #6902: Timeline zoom/move widget methods are by user
  src/main/resources/META-INF/resources/primefaces/timeline/1-timeline.js
Labels: pending-review

#6909 Fix #6908: remove ScheduleRenderingMode and occurences
  docs/10_0_0/components/schedule.md
  docs/migrationguide/10_0_0.md
  src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java
  src/main/java/org/primefaces/model/DefaultScheduleEvent.java
  src/main/java/org/primefaces/model/ScheduleDisplayMode.java
  src/main/java/org/primefaces/model/ScheduleEvent.java
Labels: enhancement
