Repository primefaces/primefaces, pull requests merged in 2022-06, with the labels that each got.

#8860 Rename moreText to moreTextSelect in docs
  docs/10_0_0/components/autocomplete.md
  docs/11_0_0/components/autocomplete.md
  docs/12_0_0/components/autocomplete.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/AutoCompleteView.java
  primefaces-showcase/src/main/webapp/ui/input/autoComplete.xhtml
Labels: documentation

#8829 Fix #8830: Added the policyProvided option for the CSP context-param
  docs/12_0_0/core/contentsecuritypolicy.md
  docs/12_0_0/gettingstarted/configuration.md
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
  primefaces/src/main/java/org/primefaces/csp/CspPhaseListener.java
  primefaces/src/main/java/org/primefaces/csp/CspResponseWriter.java
Labels: pending-review

#8886 Tree documentation onDrop
  docs/10_0_0/components/tree.md
  docs/11_0_0/components/tree.md
  docs/12_0_0/components/tree.md
  docs/7_0/components/tree.md
  docs/8_0/components/tree.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#8914 Fix #8910: Optimize JS bundling
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/calendar/Calendar.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/lightbox/LightBox.java
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/0-jquery.ui.datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/1-jquery.ui.timepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/2-jquery.ui.pfextensions.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/3-jquery.ui.datepicker.css
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/3-jquery.ui.timepicker.css
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/jquery.ui.timepicker.d.ts
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
Labels: :zap: performance

#8888 Feature Request #8887: Re-enabled row selection by button
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/SelectionFeature.java
Labels: discussion

#8902 IT: one user-action causes two ajax-calls (combination of p:ajax with eg CommandButton) - ensure correct queuing (blur-event)
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/inputnumber/InputNumber006.java
  primefaces-integration-tests/src/main/webapp/inputnumber/inputNumber006.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputnumber/InputNumber006Test.java
Labels: integration_test

#8926 IT - re-enable test (was disabled due to a Chrome 99 bug)
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/chips/Chips004Test.java
Labels: integration_test
