Repository primefaces/primefaces, pull requests merged in 2022-04, with the labels that each got.

#8446 Fix #8443/#7072: Menubar id refactoring
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/model/menu/BaseMenuModel.java
  primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java
Labels: needs investigation

#8585 Fix #8582: AutoComplete empty items padding
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.css
Labels: theme

#8013 #7962 Schedule: Upgrade FullCalendar 5.10.1
  docs/12_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/build/package.json
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/fullcalendar.min.css
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/fullcalendar.min.js
Labels: theme

#8655 Bump moment.js to 2.29.2
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment.js
Labels: javascript

#8731 Docs: replace apostrophe with singlequote
  docs/10_0_0/core/elFunctions.md
  docs/11_0_0/core/elFunctions.md
  docs/12_0_0/core/elFunctions.md
  docs/8_0/core/elFunctions.md
Labels: documentation

#8729 Fix #8725: AutoComplete match requests in queryMode
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/autocomplete/AutoComplete006.java
  primefaces-integration-tests/src/main/webapp/autocomplete/autoComplete002.xhtml
  primefaces-integration-tests/src/main/webapp/autocomplete/autoComplete006.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/autocomplete/AutoComplete006Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/AutoComplete.java
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: pending-review

#8742 SelectCheckboxMenu AJAX docs
  docs/10_0_0/components/selectcheckboxmenu.md
  docs/11_0_0/components/selectcheckboxmenu.md
  docs/12_0_0/components/selectcheckboxmenu.md
  docs/8_0/components/selectcheckboxmenu.md
Labels: documentation

#8322 Fix #7901: Toggleswitch icons
  docs/12_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SelectBooleanView.java
  primefaces-showcase/src/main/webapp/ui/input/toggleSwitch.xhtml
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitchBase.java
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitchRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/toggleswitch/toggleswitch.js
Labels: theme, pending-review
