Repository primefaces/primefaces, pull requests merged in 2022-07, with the labels that each got.

#8960 Added error handling link in docs
  docs/11_0_0/components/ajaxexceptionhandler.md
  docs/12_0_0/components/ajaxexceptionhandler.md
Labels: documentation

#8988 Fixes #8987 - DataExporter: OutputFormat doesn't render correctly on exports
  primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: pending-review

#8927 Fix #76: TabMenu: Add orientation
  docs/12_0_0/components/tabmenu.md
  docs/12_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/menu/tabMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuBase.java
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: theme

#8792 Fix #8791: DataTable: row alignment issue with scrollable and frozen columns
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.frozen.js
Labels: pending-review

#9023 Showcase - remove new badges from components existing since PF 10 or 11
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
Labels: documentation
