Repository primefaces/primefaces, pull requests merged in 2022-10, with the labels that each got.

#9255 Showcase: Improve icon list
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/misc/PrimeIconsView.java
  primefaces-showcase/src/main/webapp/icons.xhtml
Labels: pending-review

#8807 Fix #8773: Charts (jqPlot): Remove
  docs/13_0_0/components/chart.md
  docs/migrationguide/13_0_0.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chart/ChartView.java
  primefaces-showcase/src/main/webapp/ui/chart/animate.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/area.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/bar.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/bubble.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/combined.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/date.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/donut.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/export.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/interactive.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/line.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/live.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/metergauge.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/multiaxis.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/ohlc.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/pie.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/responsive.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/zoom.xhtml
  primefaces/src/main/java/org/primefaces/component/chart/Chart.java
  primefaces/src/main/java/org/primefaces/component/chart/ChartBase.java
  primefaces/src/main/java/org/primefaces/component/chart/ChartRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/BarRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/BasePlotRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/BubbleRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/CartesianPlotRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/DonutRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/LineRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/MeterGaugeRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/OhlcRenderer.java
  primefaces/src/main/java/org/primefaces/component/chart/renderer/PieRenderer.java
  primefaces/src/main/java/org/primefaces/model/chart/Axis.java
  primefaces/src/main/java/org/primefaces/model/chart/AxisType.java
  primefaces/src/main/java/org/primefaces/model/chart/BarChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/BarChartSeries.java
  primefaces/src/main/java/org/primefaces/model/chart/BubbleChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/BubbleChartSeries.java
  primefaces/src/main/java/org/primefaces/model/chart/CartesianChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/CategoryAxis.java
  primefaces/src/main/java/org/primefaces/model/chart/ChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/ChartSeries.java
  primefaces/src/main/java/org/primefaces/model/chart/DateAxis.java
  primefaces/src/main/java/org/primefaces/model/chart/DonutChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/HorizontalBarChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/LegendPlacement.java
  primefaces/src/main/java/org/primefaces/model/chart/LineChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/LineChartSeries.java
  primefaces/src/main/java/org/primefaces/model/chart/LinearAxis.java
  primefaces/src/main/java/org/primefaces/model/chart/MeterGaugeChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/OhlcChartModel.java
  primefaces/src/main/java/org/primefaces/model/chart/OhlcChartSeries.java
  primefaces/src/main/java/org/primefaces/model/chart/PieChartModel.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/charts/0-jqPlot.js
  primefaces/src/main/resources/META-INF/resources/primefaces/charts/1-charts.js
  primefaces/src/main/resources/META-INF/resources/primefaces/charts/charts.css
  primefaces/src/main/resources/META-INF/resources/primefaces/charts/jqplot.txt
Labels: breaking-change

#7418 Fix #6956: Drop Internet Explorer support
  primefaces/src/main/java/org/primefaces/component/media/MediaRenderer.java
  primefaces/src/main/java/org/primefaces/util/AgentUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.css
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.env.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.polyfills.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/datepicker.css
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/inputgroup.css
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/inputnumber.css
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.css
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sidebar/sidebar.css
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/signature.css
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.css
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
  primefaces/src/main/resources/META-INF/resources/primefaces/terminal/terminal.css
  primefaces/src/main/resources/META-INF/resources/primefaces/terminal/terminal.js
  primefaces/src/main/resources/META-INF/resources/primefaces/toggleswitch/toggleswitch.css
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.horizontal.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.css
Labels: breaking-change

#9312 PanelStyle, PanelStyleClass docs
  docs/10_0_0/components/selectonemenu.md
  docs/11_0_0/components/selectonemenu.md
  docs/12_0_0/components/selectonemenu.md
  docs/13_0_0/components/selectonemenu.md
  docs/7_0/components/selectonemenu.md
  docs/8_0/components/selectonemenu.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#9335 Selenium 4.5.2 Mockito 4.8.1
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces/pom.xml
Labels: dependencies, java
