Repository primefaces/primefaces, pull requests merged in 2023-07, with the labels that each got.

#10288 IT: TextExporter Serializable
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/dataexporter/TextExporter.java
Labels: integration_test

#10294 Fix #10284: Tree selection null check
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
Labels: :lady_beetle: defect

#10296 Fix #10291: ColorPicker hex color converter docs
  docs/13_0_0/components/colorpicker.md
  docs/migrationguide/13_0_0.md
Labels: documentation

#10295 Fix #10292: Galleria thumbnail don't shift if items <= visible
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleriathumbnail.js
Labels: :lady_beetle: defect

#10306 fix #10303: bug in CheckboxTreeNodeChildren:set in combination with sorting
  primefaces/src/main/java/org/primefaces/model/CheckboxTreeNodeChildren.java
Labels: :lady_beetle: defect

#10304 Fix #10300: Galleria delay showing caption until rendering complete
  primefaces/src/main/java/org/primefaces/component/galleria/GalleriaRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleriaitem.js
Labels: :lady_beetle: defect

#10313 Fix #10311/#9259: DatePicker remove mask workaround
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#10317 Fix #10309: BlockUI must hide if source is no longer in DOM
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#10322 Fix #10314 - DataExporter: fails on export columnGroup
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
Labels: :lady_beetle: defect

#10320 Fix #10315: SelectOneRadio flex=true assume layout=responsive
  docs/migrationguide/13_0_0.md
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: enhancement

#10321 Fix #10318: SelectOneRadio fix responsive long labels
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#10327 Introducing ComponentUtils#isUIRepeat
  primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java
  primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: enhancement

#10324 Fix #10323 - DataExporter: problems with xlsx export and columnGroup
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java
Labels: :lady_beetle: defect

#10326 Fix #10325 - DataExporter: xlsx export and ui:repeat inside columnGroup
  primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java
Labels: :lady_beetle: defect

#10332 Hotkey doc update
  docs/10_0_0/components/hotkey.md
  docs/11_0_0/components/hotkey.md
  docs/12_0_0/components/hotkey.md
  docs/13_0_0/components/hotkey.md
  docs/7_0/components/hotkey.md
  docs/8_0/components/hotkey.md
Labels: documentation

#10338 Fix #10335: AutoComplete don't render header facets if emptyMessage
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.css
Labels: :lady_beetle: defect

#10339 Fix #10334 - DataTable: dynamic columns have wrong order after sorting
  primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java
Labels: :lady_beetle: defect

#10337 fix 10336: Captcha: Incorrect error message if context parameters are not set
  primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
Labels: :lady_beetle: defect

#10341 Fix #10340: Menu revert js:void(0) for CSP issues
  primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java
Labels: :lady_beetle: defect

#10358 Fix #10355: SelectOneMenu trigger icon should focus panel
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#10364 Fix #10361: Tree handle long labels
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.css
Labels: :lady_beetle: defect

#10366 Fix #10365: ImageCropper originalFilename for streamed content
  primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java
  primefaces/src/test/java/org/primefaces/component/imagecropper/ImageCropperRendererTest.java
Labels: :lady_beetle: defect

#10370 Fix #10365: ImageCropper originalFilename for streamed content
  docs/13_0_0/components/imagecropper.md
  docs/14_0_0/components/imagecropper.md
  primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java
Labels: :lady_beetle: defect

#10382 Fix #10381: Cropper.js v1.5.13
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/imagecropper/0-cropper.js
Labels: dependencies, javascript

#10384 Fix #10378: OutputLabel associate SelectCheckBoxMenu
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenu.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuBase.java
Labels: accessibility

#10383 Fix #10379: Panel don't render labelledby if no header
  primefaces/src/main/java/org/primefaces/component/panel/PanelRenderer.java
Labels: accessibility

#10393 Fix #10392: Dialog focus proper first input, fallback to close button
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: accessibility

#10405 Fixes #10402 13.0.1 DataExporter: fileName should be marked as requir…
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#10414 Fix #10413: Locales AU and UK/GB
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
Labels: enhancement

#10410 Fix #10365: ImageCropper improved name handling
  primefaces/src/main/java/org/primefaces/component/imagecropper/ImageCropperRenderer.java
Labels: enhancement

#10408 Fix #10398: Messages add clearMessages() widget method
  docs/14_0_0/components/messages.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
Labels: enhancement

#10412 Fix #10281: Growl/Messages refactor to UINotifications
  primefaces/src/main/java/org/primefaces/component/api/UINotifications.java
  primefaces/src/main/java/org/primefaces/component/growl/GrowlBase.java
  primefaces/src/main/java/org/primefaces/component/growl/GrowlRenderer.java
  primefaces/src/main/java/org/primefaces/component/message/MessageBase.java
  primefaces/src/main/java/org/primefaces/component/messages/MessagesBase.java
  primefaces/src/main/java/org/primefaces/component/messages/MessagesRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/UINotificationRenderer.java
Labels: enhancement

#10417 Fix #10333: Paginator move server labels to client
  docs/14_0_0/core/localization.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/component/api/Pageable.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/paginator/FirstPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/LastPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/NextPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PrevPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/RowsPerPageDropdownRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableBase.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10415 #10333: Autocomplete move server labels to client labels
  docs/14_0_0/components/autocomplete.md
  docs/14_0_0/core/localization.md
  docs/migrationguide/14_0_0.md
  primefaces-integration-tests/src/main/webapp/autocomplete/autoComplete005.xhtml
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteBase.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10416 #10333: Locale rename firstDay to firstDayOfWeek
  docs/14_0_0/core/localization.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-iw.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ka.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-vi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js
Labels: accessibility
