Repository primefaces/primefaces, pull requests merged in 2023-08, with the labels that each got.

#10419 Fix #10333: Use PrimeLocale
  docs/14_0_0/core/localization.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/calendar/Calendar001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/schedule/Schedule001Test.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces-showcase/src/main/webapp/ui/data/schedule/localization.xhtml
  primefaces-showcase/src/main/webapp/ui/input/calendar/calendar.xhtml
  primefaces-showcase/src/main/webapp/ui/input/calendar/calendarJava8.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-da.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-iw.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ka.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-vi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: breaking-change

#10423 Selenium 4.11.0
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java
Labels: dependencies, java

#10424 Fix #10333: DataTable/CheckBoxMenu Select All Checkbox ARIA
  docs/14_0_0/core/localization.md
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenu.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10428 Fix #10333: ARIA close icon label moved to client
  docs/14_0_0/core/localization.md
  primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java
  primefaces/src/main/java/org/primefaces/component/dialog/Dialog.java
  primefaces/src/main/java/org/primefaces/component/dialog/DialogRenderer.java
  primefaces/src/main/java/org/primefaces/component/messages/Messages.java
  primefaces/src/main/java/org/primefaces/component/messages/MessagesRenderer.java
  primefaces/src/main/java/org/primefaces/component/panel/Panel.java
  primefaces/src/main/java/org/primefaces/component/panel/PanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleria.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
  primefaces/src/main/resources/META-INF/resources/primefaces/panel/panel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sidebar/sidebar.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10430 Fix #10425: ColorPicker respect theme color
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker004Test.java
  primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
Labels: :lady_beetle: defect

#10432 Fix #10425: 13.0.1 ColorPicker respect theme color
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker004Test.java
  primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
Labels: :lady_beetle: defect

#10431 Fix #10429: Datatable selection aria labels radio/checkbox
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#10433 Fix #10333: Filer input aria-label moved to client
  docs/14_0_0/core/localization.md
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/picklist/PickListRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10441 Fix #10438: 13.0.1 Showcase CRUD delete (#10440)
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/CrudView.java
Labels: :lady_beetle: defect

#10439 Fix #10312: InputMask dd.mm.yyyy fix
  docs/14_0_0/core/thirdpartylibs.md
  primefaces-integration-tests/src/main/webapp/inputmask/inputMask004.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputmask/InputMask003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputmask/InputMask004Test.java
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/0-jquery.inputmask.js
Labels: :lady_beetle: defect

#10446 Fix #10312: 13.0.1 InputMask dd.mm.yyyy fix
  primefaces-integration-tests/src/main/webapp/inputmask/inputMask004.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputmask/InputMask003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputmask/InputMask004Test.java
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/0-jquery.inputmask.js
Labels: :lady_beetle: defect

#10447 Fix #10333: Datatable,Galleria,Panel ARIA labels
  docs/14_0_0/core/localization.md
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/headerrow/HeaderRowRenderer.java
  primefaces/src/main/java/org/primefaces/component/panel/Panel.java
  primefaces/src/main/java/org/primefaces/component/panel/PanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/rowtoggler/RowToggler.java
  primefaces/src/main/java/org/primefaces/component/rowtoggler/RowTogglerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleriaitem.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/panel/panel.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10272 Fix #2705 - Fileupload: Directory structure
  primefaces/src/main/java/org/primefaces/component/fileupload/AbstractFileUploadDecoder.java
  primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java
  primefaces/src/main/java/org/primefaces/component/fileupload/NativeFileUploadDecoder.java
  primefaces/src/main/java/org/primefaces/event/FileUploadEvent.java
  primefaces/src/main/java/org/primefaces/event/FilesUploadEvent.java
  primefaces/src/main/java/org/primefaces/model/file/AbstractUploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/CommonsUploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/NIOUploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/NativeUploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFileWrapper.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/test/java/org/primefaces/model/file/NativeUploadedFileTest.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: new feature

#10448 Fix #10333: DatePicker ARIA
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: accessibility

#10450 Fix #10333: Password ARIA labels
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/password/Password002Test.java
  primefaces/src/main/java/org/primefaces/component/password/PasswordBase.java
  primefaces/src/main/java/org/primefaces/component/password/PasswordRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
Labels: accessibility

#10451 Fix #10333: Growl/Messages ARIA
  docs/14_0_0/core/localization.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ka.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10454 Fix #10333: Switch ON/OFF Aria
  docs/14_0_0/core/localization.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectbooleanbutton/SelectBooleanButton001Test.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchBase.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectbooleanbutton/SelectBooleanButtonBase.java
  primefaces/src/main/java/org/primefaces/component/selectbooleanbutton/SelectBooleanButtonRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectbooleanbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/inputswitch/inputswitch.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-da.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/toggleswitch/toggleswitch.js
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: accessibility

#10456 Fix #10333: Growl ARIA removed dead code
  primefaces/src/main/java/org/primefaces/component/growl/GrowlRenderer.java
  primefaces/src/main/java/org/primefaces/component/messages/Messages.java
  primefaces/src/main/java/org/primefaces/renderkit/UINotificationRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
Labels: accessibility

#10462 Fix #10333: Update CS and add new locales to pom.xml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
Labels: accessibility

#10458 Fix #10457: queueMicroTask instead of setTimeout(0)
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.frozen.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/effect/effect.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
  primefaces/src/main/resources/META-INF/resources/primefaces/lifecycle/lifecycle.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/mindmap/mindmap.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: enhancement, pending-review

#10469 fix #10467: 13.0.1 sidebar ajax-listener not executed
  primefaces/src/main/java/org/primefaces/component/sidebar/SidebarRenderer.java
Labels: :lady_beetle: defect

#10474 Fix #10471: ColumnToggler removing too much text
  primefaces-showcase/src/main/webapp/ui/data/datatable/columnToggler.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
Labels: :lady_beetle: defect

#10478 Fix #10275: ScrollTo customize animation duration
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: enhancement

#10480 Fix #10477: Accordion toggleSpeed property
  docs/14_0_0/components/accordionpanel.md
  docs/14_0_0/components/panel.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelBase.java
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.js
Labels: new feature

#10479 Fix #10476: Accordion scroll tab into view
  docs/14_0_0/components/accordionpanel.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/panel/accordionPanel.xhtml
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelBase.java
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.js
Labels: enhancement

#10485 Fix #10484: BlockUI do not show block if AJAX queue empty
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#10486 Fix #10484: 13.0.1 BlockUI do not show block if AJAX queue empty
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#10488 Update autocomplete.js: avoid duplicate method calls
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: enhancement

#10493 Fix #10492: ClamAV use timeout for connection timeout
  primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonClient.java
Labels: :lady_beetle: defect

#10494 Fix #10492: 13.0.1 ClamAV use timeout for connection timeout
  primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonClient.java
Labels: :lady_beetle: defect

#10503 Fix #10299: PrimeFaces.utils.killswitch() convenience method
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: enhancement

#10505 Fix #10305: SelectCheckBoxMenu add selectedLabel
  docs/14_0_0/components/selectcheckboxmenu.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/webapp/selectcheckboxmenu/selectCheckboxMenu001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu001Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectCheckboxMenu.java
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuBase.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: enhancement

#10510 Fix #10506: 13.0.1 Revert changing script id's only change ID
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: :lady_beetle: defect

#10509 Fix #10507: Port ContextMenu fixes to TreeTable
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/ContextMenuView.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/treetable/ContextMenuView.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/contextMenu.xhtml
  primefaces-showcase/src/main/webapp/ui/data/treetable/contextMenu.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#10511 Fix #10507: 13.0.1 Port ContextMenu fixes to TreeTable
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/ContextMenuView.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/treetable/ContextMenuView.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/contextMenu.xhtml
  primefaces-showcase/src/main/webapp/ui/data/treetable/contextMenu.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#10514 Fix #10512: Datepicker TouchUI showcase
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
Labels: documentation

#10515 Fix #10512: 13.0.1 Datepicker TouchUi showcase
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
Labels: documentation

#10257 Fix #10251: FileDownload allow disabling of `no-store`
  docs/14_0_0/components/filedownload.md
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadTagHandler.java
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement

#10525 Fix #10518: Tabview default focus configs
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10528 Fix #10518: 13.0.1 TabView default focus configs
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10541 Fix #10531: 13.0.1 WebDriver 5.5.0 for Java 8
  primefaces-selenium/primefaces-selenium-core/pom.xml
Labels: :lady_beetle: defect

#10543 Fix #10533: BlockUI if using delay do not display if Ajax Queue
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#10547 Fix #10533: 13.0.1 BlockUI if using delay do not display if Ajax Queue
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#10562 Fixed #10319 - 13.0.1 SelectOneRadio: Add columnClasses attribute
  docs/13_0_0/components/selectoneradio.md
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioBase.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: new feature

#10566 Fix #10565: jQuery 3.7.1
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js
Labels: dependencies, javascript

#10536 Fix #10532: Java 11
  .github/workflows/build.yml
  pom.xml
  primefaces/pom.xml
Labels: breaking-change

#10574 feat #10573: add server API to set bar radiuses
  primefaces/src/main/java/org/primefaces/model/charts/bar/BarChartDataSet.java
  primefaces/src/main/java/org/primefaces/model/charts/bar/BarCorner.java
Labels: enhancement

#10542 Fix #1435/#3992: SelectManyMenu/SelectOneListbox WCAG and Keyboard support
  docs/14_0_0/components/selectmanymenu.md
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectlistbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanymenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js
Labels: accessibility

#10513 Fix #4685: DatePicker ARIA/WCAG and keyboard support
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datepicker/DatePicker001.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable026.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable026Dates.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable026Not.xhtml
  primefaces-integration-tests/src/main/webapp/datepicker/datePicker001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable026DatesTest.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable026NotTest.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable026Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker001Test.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/datepicker.css
Labels: accessibility

#10564 Fix #9608: ColumnToggler add selectAll/unselectAll
  docs/14_0_0/components/columntoggler.md
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.css
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
Labels: new feature
