Repository primefaces/primefaces, pull requests merged in 2023-06, with the labels that each got.

#10195 Fix #10191: Spinner change links to buttons
  docs/13_0_0/core/localization.md
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: accessibility

#10201 Fix #10200: PrimeFlex 3.3.1 and link updates
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
  primefaces-showcase/src/main/webapp/index.xhtml
  primefaces-showcase/src/main/webapp/primeflex/setup.xhtml
  primefaces-showcase/src/main/webapp/resources/showcase/css/primeflex2.css
  primefaces-showcase/src/main/webapp/resources/showcase/css/primeflex3.css
  primefaces-showcase/src/main/webapp/ui/data/dataview/responsive.xhtml
  primefaces-showcase/src/main/webapp/ui/df/level1.xhtml
  primefaces-showcase/src/main/webapp/ui/input/formLayout.xhtml
  primefaces-showcase/src/main/webapp/ui/panel/dashboard.xhtml
  primefaces-showcase/src/main/webapp/ui/panel/flexGrid.xhtml
Labels: documentation

#10204 Fix #10203: Timeline: editableAdd is not set
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineBase.java
Labels: :lady_beetle: defect

#10057 Fix #9969 - Core: Refactor Exporter - Part 2
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/dataexporter/TextExporter.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/dataexporter/AbstractDataExporterTest.java
  primefaces-integration-tests/src/test/resources/org/primefaces/integrationtests/dataexporter/languages-pageonly.txt
  primefaces-integration-tests/src/test/resources/org/primefaces/integrationtests/dataexporter/languages.txt
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/dataexporter/CustomizedDocumentsView.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/dataexporter/DataExporterView.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/dataexporter/TextExporter.java
  primefaces-showcase/src/main/webapp/ui/data/dataexporter/customizedDocuments.xhtml
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableCSVExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelXExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelXStreamExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporterFactory.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableXMLExporter.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporter.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporterTagHandler.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporters.java
  primefaces/src/main/java/org/primefaces/component/export/ExportConfiguration.java
  primefaces/src/main/java/org/primefaces/component/export/Exporter.java
  primefaces/src/main/java/org/primefaces/component/export/ExporterType.java
  primefaces/src/main/java/org/primefaces/component/export/ExporterUtils.java
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableCSVExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelXExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelXStreamExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExporterFactory.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableXMLExporter.java
  primefaces/src/main/java/org/primefaces/context/PrimeApplicationContext.java
  primefaces/src/main/java/org/primefaces/util/IOUtils.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement, pending-review

#10132 Fix #10099 visitTree doesn't handle VisitResult.REJECT
  primefaces/src/main/java/org/primefaces/component/api/UITabPanel.java
Labels: :lady_beetle: defect

#10218 Fix #10209 - DataTable: Filter usage modify the value object type
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java
Labels: :lady_beetle: defect

#10234 Fix #10233: SelectOneMenu remove CSS transform
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: enhancement

#10241 #10240 SelectOneRadio deprecate plain
  docs/13_0_0/components/selectoneradio.md
  docs/migrationguide/13_0_0.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement, documentation

#10260 Fix #10242: Dashboard deprecation clean up
  primefaces/src/main/java/org/primefaces/component/dashboard/Dashboard.java
  primefaces/src/main/java/org/primefaces/model/dashboard/DashboardModel.java
  primefaces/src/main/java/org/primefaces/model/dashboard/DefaultDashboardModel.java
Labels: documentation

#10265 Fix #10264 - Exporter: Custom registration issue
  docs/13_0_0/components/dataexporter.md
  primefaces/src/main/java/org/primefaces/component/export/DataExporters.java
Labels: :lady_beetle: defect

#10274 Showcase: fix ToggleSwitch remote demo
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SelectBooleanView.java
Labels: documentation

#10277 Fix #10276: ColorPicker 0.21.0
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-coloris.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-colorpicker.css
Labels: dependencies
