Repository primefaces/primefaces, pull requests merged in 2023-11, with the labels that each got.

#10934 Fix #10371 13.0.3 DataTable: ClassCastException when DataTable is lazy
  primefaces/src/main/java/org/primefaces/component/api/UIData.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#10948 Fix #10945: Datepicker set initial view date
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10949 Fix #10945: 13.0.3 Datepicker set initial view date
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10952 Fix #10950: Use NULL for FacesMessage detail
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
Labels: :lady_beetle: defect

#10968 Fix #10864: Tooltip global animation fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#10969 Fix #10864: 13.0.3 Tooltip global animation fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#10974 DatePicker filter range example clarification
  primefaces-showcase/src/main/webapp/ui/data/datatable/columns.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
Labels: documentation

#10978 Fix #10967 - Datatable: support custom components as filter
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/model/FilterMeta.java
  primefaces/src/main/java/org/primefaces/util/ComponentTraversalUtils.java
Labels: new feature

#10991 Add Malyasian and Kyrgyz locales
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ms.js
Labels: enhancement

#10997 Add TabView badge example
  primefaces-showcase/src/main/webapp/ui/panel/tabView.xhtml
Labels: documentation

#11006 Fix #11005: FileDownload AJAX escape name
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java
Labels: :lady_beetle: defect

#11007 Fix #11005: 13.0.4 FileDownload AJAX escape name
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java
Labels: :lady_beetle: defect

#11010 Fix #11002, #11003: 13.0.4 CSV fixes / improvements
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
Labels: :lady_beetle: defect

#11015 Fix #11012: Autocomplete highlighting
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: :lady_beetle: defect

#11016 Fix #11012: 13.0.4 Autocomplete highlighting
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: :lady_beetle: defect

#11011 Fix #11008 - 13.0.4 CSV: growl rendering broken
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
  primefaces/src/main/type-definitions/core.d.ts
Labels: :lady_beetle: defect

#11017 Fix #10998: SelectOneMenu loading indicator
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: enhancement

#10943 Fix #8416 - DataTable: clarify / rename selection attributes
  docs/14_0_0/components/datatable.md
  docs/migrationguide/14_0_0.md
  primefaces-integration-tests/src/main/webapp/datatable/dataTable002.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable002NonLazy.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable002ReflectionLazyDataModel.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable002RowCountOtherImpl.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable004.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable005.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable005Array.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable006.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable010.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable032.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable035.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable036_lazy.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable036_nonLazy.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable039.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/selection.xhtml
  primefaces/src/main/java/org/primefaces/component/api/DynamicColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/column/ColumnBase.java
  primefaces/src/main/java/org/primefaces/component/columns/Columns.java
  primefaces/src/main/java/org/primefaces/component/columns/ColumnsBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/SelectionFeature.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement, breaking-change

#11032 avoid js exception when cleaning up contextmenu widget (#11022)
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js
Labels: :lady_beetle: defect

#11033 fix #11022: 13.0.4 Cleanup ContextMenu properly
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js
Labels: :lady_beetle: defect

#11027 Remove OWASP Dependency Check
  .github/workflows/build.yml
  primefaces/pom.xml
  primefaces/src/conf/owasp-suppressions.xml
Labels: enhancement

#11028 13.0.4 Remove OWASP Dependency Check
  .github/workflows/build.yml
  primefaces/pom.xml
  primefaces/src/conf/owasp-suppressions.xml
Labels: enhancement

#11030 Fix #11029: Spinner allow BACKSPACE
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11031 Fix #11029: 13.0.4 Spinner allow BACKSPACE
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11035 Fix #11018: 13.0.4 SelectCheckboxMenu aria-expanded
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#11034 Fix #11018: SelectCheckboxMenu aria-expanded
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#11021 Fix total size count for data scroller
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java
Labels: :lady_beetle: defect

#11038 update touchswipe.js to 1.6.19
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/touch/touchswipe.js
Labels: dependencies, javascript

#11042 Fix #11019: Datascroller fix total size count
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java
Labels: :lady_beetle: defect

#11049 Fix #11046 - 13.0.4 Calendar: $this._base_updateDatepicker when stayi…
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/2-jquery.ui.pfextensions.js
Labels: :lady_beetle: defect

#11053 Fix #10970: BlockUI delay binding global triggers until UI is loaded
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#11054 Fix #10970: 13.0.4 BlockUI delay binding trigger
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#11020 Fix #11001 - Simple FileUpload: refactor client side validation
  docs/14_0_0/core/localization.md
  docs/migrationguide/14_0_0.md
  primefaces-integration-tests/src/main/webapp/WEB-INF/web.xml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload001.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload002.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload003.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload004.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload005.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload004Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload005Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/FileUpload.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeExpectedConditions.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/Guard.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/spi/WebDriverProvider.java
  primefaces-selenium/primefaces-selenium-core/src/main/resources/primefaces-selenium/onload.js
  primefaces-showcase/src/main/webapp/ui/file/upload/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/basicAuto.xhtml
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.validators.js
Labels: enhancement
