Repository primefaces/primefaces, pull requests merged in 2023-05, with the labels that each got.

#10101 Theme fixes
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#9711 Fix #8765/#7767/#7763/#7765/#3781: AutoComplete/SelectOneMenu/RowExpansion/OrderList duplicate ids
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectonemenu/SelectOneMenu012Test.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/RowExpandFeature.java
  primefaces/src/main/java/org/primefaces/component/orderlist/OrderListRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: pending-review

#10174 Fix #10172: DatePicker selecting incorrect month
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10176 Fix #10175 - TreeTable: NumberFormatException if select all entries
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTable.java
Labels: :lady_beetle: defect

#10178 Fix #10166: SelectManyCheckbox handle SPACE/ENTER key
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanycheckbox.js
Labels: :lady_beetle: defect

#10182 Fix #10179: Manifest Automatic Module entry
  primefaces/pom.xml
Labels: enhancement

#10183 #9129 OutputLabel: Keep required indicator visible with PrimeFlex
  primefaces-showcase/src/main/webapp/ui/misc/outputLabel.xhtml
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#10184 Docs: fix responsive priority mistakes
  docs/10_0_0/components/columns.md
  docs/11_0_0/components/columns.md
  docs/12_0_0/components/columns.md
  docs/13_0_0/components/columns.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#10190 Fix #10189: Dialog should render not displayed
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/dialog/Dialog001Test.java
  primefaces/src/main/java/org/primefaces/component/dialog/DialogRenderer.java
Labels: :lady_beetle: defect

#10193 Fix #10191: Add href to anchor links
  pom.xml
  primefaces/src/conf/owasp-suppressions.xml
  primefaces/src/main/java/org/primefaces/component/scrolltop/ScrollTopRenderer.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
Labels: enhancement
