Repository primefaces/primefaces, pull requests merged in 2023-10, with the labels that each got.

#10756 Fix #10754/#10757: DatePicker Now label
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#10758 Fix #10754/#10757: 13.0.2 DatePicker Now
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#10765 Fixed #10764 - When tabbing through a dialog framework modal the curs…
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js
Labels: :lady_beetle: defect

#10759 PartialResponseWriting stop wrapping
  primefaces/src/main/java/org/primefaces/context/PartialResponseWriterWrapper.java
  primefaces/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java
  primefaces/src/main/java/org/primefaces/csp/CspPartialResponseWriter.java
Labels: breaking-change

#10753 Fix #10751: Apache Commons Upload deprecated
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/component/fileupload/CommonsFileUploadDecoder.java
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
  primefaces/src/main/java/org/primefaces/util/Constants.java
  primefaces/src/main/java/org/primefaces/webapp/MultipartRequest.java
  primefaces/src/main/java/org/primefaces/webapp/filter/FileUploadFilter.java
  primefaces/src/test/java/org/primefaces/mock/pf/PrimeConfigurationMock.java
Labels: breaking-change

#10769 fix primefaces#10763: TreeTable: Filtering with CustomNode and cloneOnFilter does not work (primefaces#10763)
  primefaces/src/main/java/org/primefaces/component/treetable/feature/FilterFeature.java
  primefaces/src/test/java/org/primefaces/component/treetable/feature/CustomNode.java
  primefaces/src/test/java/org/primefaces/component/treetable/feature/TreeTableFilterFeatureTest.java
Labels: :lady_beetle: defect

#10772 Fix #10770: SelectOneMenu receive p:focus
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#10775 Fix #10575: 13.0.2 MenuItem oncomplete script is not called if no act…
  primefaces/src/main/java/org/primefaces/model/menu/MenuItem.java
  primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java
  primefaces/src/test/java/org/primefaces/renderkit/MenuItemAwareRendererTest.java
Labels: :lady_beetle: defect

#10778 Hebrew locale
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-he.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-iw.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: enhancement

#10788 Fix #10786: 13.0.2 SelectCheckboxMenu width after AJAX
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#10784 TreeTable: removal of cloneOnFilter property
  docs/14_0_0/components/treetable.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/component/treetable/feature/FilterFeature.java
  primefaces/src/test/java/org/primefaces/component/treetable/feature/TreeTableFilterFeatureTest.java
Labels: enhancement

#10796 Fix #10790: MoveScriptsToBottom fail if duplicate html/body
  primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java
  primefaces/src/test/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriterTest.java
Labels: enhancement

#10795 Fix #10721: 13.0.2 Handle TAB press with selectone panel
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#10806 Fix #10804: TabView focusOnLastActiveTab default false
  docs/13_0_0/components/tabview.md
  docs/14_0_0/components/tabview.md
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewBase.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10807 Fix #10804: 13.0.2 TabView focusOnLastActiveTab default false
  docs/13_0_0/components/tabview.md
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewBase.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10816 Fix #10809 13.0.3 DataTable: selectAll checkbox is disabled after rem…
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#10808 Fix #10805: HtmlSantitizer allow media elements
  primefaces/src/main/java/org/primefaces/util/HtmlSanitizer.java
Labels: enhancement

#10832 Fix #10830 - DataTable: Error if filter facet element is bound to List
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
Labels: :lady_beetle: defect

#10840 Fix #10839: DeferredRender list unique by widgetId
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10842 Fix #10839: 13.0.3 DeferredRender list unique by widgetId
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10843 Fix #10819: Datepicker initialize navigator correctly
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10844 Fix #10819: 13.0.3 Datepicker initialize navigator correctly
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10848 Fix #10822: Hazelcast move to docs
  docs/14_0_0/components/cache.md
  docs/migrationguide/14_0_0.md
  primefaces/pom.xml
  primefaces/src/conf/owasp-suppressions.xml
  primefaces/src/main/java/org/primefaces/cache/DefaultCacheProvider.java
  primefaces/src/main/java/org/primefaces/cache/HazelcastCacheProvider.java
Labels: breaking-change

#10852 Fix #10831 - Wizard: Add disableOnAjax attribute for Next/Back navigation
  docs/14_0_0/components/wizard.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/wizard/WizardBase.java
  primefaces/src/main/java/org/primefaces/component/wizard/WizardRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js
Labels: enhancement

#10853 Fix #10847: AutoComplete closes on Enter when no item is highlighted
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: accessibility

#10855 Fix #10847: 13.0.3 AutoComplete closes on Enter when no item is highl…
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: accessibility

#10861 Fix #10858 - Datatable: clear filter after filtered + "all per page" shows all pages again
  docs/PrimeFaces.d.ts
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: :lady_beetle: defect

#10869 Fix #10858 - 13.0.3 Datatable: clear filter after filtered + "all per…
  docs/PrimeFaces.d.ts
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: :lady_beetle: defect

#10868 Fix #10864: Tooltip global animation fix
  docs/13_0_0/components/tooltip.md
  docs/14_0_0/components/tooltip.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#10867 Fix #10864: 13.0.3 Tooltip global display fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#10860 Fix #10845/#10790: 13.0.3 MoveScriptsToBottom backport
  primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java
  primefaces/src/test/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriterTest.java
Labels: :lady_beetle: defect

#10851 Fix #10845: MoveScriptsToBottom do not touch non JS scripts
  primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java
  primefaces/src/test/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriterTest.java
Labels: :lady_beetle: defect

#10882 Fix #10873: 13.0.3 isPrintableKey null check
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#10884 Fix #10874: `InputSwitch` has been deprecated since 10.0 and will be removed in 15.0.0
  docs/migrationguide/14_0_0.md
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/InputSwitch.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitch.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchBase.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: breaking-change

#10885 #10866
  primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#10889 Fix #10880: SelectOne better re-focus handling
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#10890 Fix #10866: 13.0.3 FloatLabel fixes
  primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#10897 Fix #10863: PDF default encoding to BaseFont.IDENTITY_H
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
Labels: enhancement

#10900 Fix #10877: Upgrade org.json/json to 20231013
  pom.xml
Labels: :lock: security

#10898 Fix #10863: 13.0.3 PDF default encoding to BaseFont.IDENTITY_H
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
Labels: enhancement

#10892 #10838
  docs/14_0_0/components/datatable.md
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: enhancement

#10899 Fix #9970: MenuBar/TieredMenu add hideDelay
  docs/14_0_0/components/menubar.md
  docs/14_0_0/components/tieredmenu.md
  docs/14_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/14_0_0.md
  primefaces-showcase/src/main/webapp/ui/menu/menubar.xhtml
  primefaces/src/main/java/org/primefaces/component/menu/AbstractMenu.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarBase.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuBase.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: new feature

#10906 Fix #10839: Improved deferred widget handling
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10910 Fix #10839: 13.0.3 Improved deferred widget handling
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10908 PanelGrid remove deprecation warning for table layout
  primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java
Labels: documentation

#10907 Fix #10850: DatePicker fire dateSelect in multiple selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#10917 Fix #10913: 13.0.3 Focus first link only in dialogs
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10916 Fix #10913: Focus first link only in dialogs
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#10912 Fix #10345: Badge add icon support
  docs/14_0_0/components/badge.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/misc/badge.xhtml
  primefaces/src/main/java/org/primefaces/component/badge/Badge.java
  primefaces/src/main/java/org/primefaces/component/badge/BadgeBase.java
  primefaces/src/main/java/org/primefaces/component/badge/BadgeRenderer.java
  primefaces/src/main/java/org/primefaces/model/badge/BadgeModel.java
  primefaces/src/main/java/org/primefaces/model/badge/DefaultBadgeModel.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/badge/badge.css
Labels: new feature

#10923 Fix #10922: Spinner prefix breaks with min value
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner004Test.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SpinnerView.java
  primefaces-showcase/src/main/webapp/ui/input/spinner.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#10926 Fix #10922: 13.0.3 Spinner prefix breaks with min value
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner004Test.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SpinnerView.java
  primefaces-showcase/src/main/webapp/ui/input/spinner.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#10920 Fix #10679: MoveScriptsToBottom deferred
  docs/14_0_0/gettingstarted/configuration.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomResponseWriter.java
  primefaces/src/main/java/org/primefaces/application/resource/MoveScriptsToBottomState.java
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
  primefaces/src/main/java/org/primefaces/context/PrimeFacesContext.java
Labels: enhancement

#10927 Fix #10918: Column(s) filterPlaceholder property
  docs/14_0_0/components/column.md
  docs/14_0_0/components/columns.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
  primefaces/src/main/java/org/primefaces/component/api/DynamicColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/column/ColumnBase.java
  primefaces/src/main/java/org/primefaces/component/columns/ColumnsBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: new feature

#10919 Added community page
  docs/14_0_0/components/datatable.md
  docs/14_0_0/gettingstarted/community.md
  docs/14_0_0/menu.md
Labels: documentation

#10928 Fix #10921: Badge add onClick and delegate to target by default
  docs/14_0_0/components/badge.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/misc/badge.xhtml
  primefaces/src/main/java/org/primefaces/component/badge/Badge.java
  primefaces/src/main/java/org/primefaces/component/badge/BadgeBase.java
  primefaces/src/main/java/org/primefaces/component/badge/BadgeRenderer.java
  primefaces/src/main/java/org/primefaces/model/badge/BadgeModel.java
  primefaces/src/main/java/org/primefaces/model/badge/DefaultBadgeModel.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/badge/badge.css
Labels: new feature
