Repository primefaces/primefaces, pull requests merged in 2023-09, with the labels that each got.

#10556 Fix #10554 - DataTable: reduce number of calls to setRowIndex in encodeRows
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: enhancement, :zap: performance

#10579 Fix #10578: XSS prevention in icon only buttons
  primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectbooleanbutton/SelectBooleanButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
Labels: :lock: security

#10582 Fix #10578: XSS prevention in icon only buttons
  primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectbooleanbutton/SelectBooleanButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
Labels: :lock: security

#10577 Fix #10576: Paginator position must be lowercase in script
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
Labels: :lady_beetle: defect

#10594 Fix #10593: AutoNumeric 4.10.0
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: dependencies

#10596 Fix #10328: UIData backport Mojarra fixes
  primefaces/src/main/java/org/primefaces/component/api/ImmutableSavedState.java
  primefaces/src/main/java/org/primefaces/component/api/SavedState.java
  primefaces/src/main/java/org/primefaces/component/api/UIData.java
Labels: :zap: performance

#10601 Fix #10592: HideNoSelectionOption handle string boolean
  primefaces/src/main/java/org/primefaces/renderkit/SelectRenderer.java
Labels: :lady_beetle: defect

#10606 Fix #10592: 13.0.1 HideNoSelectionOption handle string boolean
  primefaces/src/main/java/org/primefaces/renderkit/SelectRenderer.java
Labels: :lady_beetle: defect

#10611 Fix #10608/#10607: doc updates
  docs/12_0_0/components/overlaypanel.md
  docs/13_0_0/components/inputnumber.md
  docs/13_0_0/components/overlaypanel.md
  docs/14_0_0/components/inputnumber.md
  docs/14_0_0/components/overlaypanel.md
Labels: documentation

#10610 Fix #10328/#10584: 13.0.1 UIData backport Mojarra fixes
  primefaces/src/main/java/org/primefaces/component/api/ImmutableSavedState.java
  primefaces/src/main/java/org/primefaces/component/api/SavedState.java
  primefaces/src/main/java/org/primefaces/component/api/UIData.java
Labels: :lady_beetle: defect

#10617 Header doesn't exported issue 10616
  primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java
Labels: :lady_beetle: defect

#10619 Issue 10615
  primefaces/src/main/java/org/primefaces/component/export/ExporterUtils.java
Labels: enhancement

#10614 Fix #10613: Cookie 3.0.5, Moment 0.5.43, Coloris 0.21.1, JS Plumb 2.15.6
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-coloris.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/js.cookie.js
  primefaces/src/main/resources/META-INF/resources/primefaces/diagram/0-jsplumb.min.js
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment-timezone-with-data.js
Labels: dependencies, javascript

#10409 Fixes #10404 - Exporter: Allow user can export a custom value type other than string
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/dataexporter/TextExporter.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/dataexporter/TextExporter.java
  primefaces/src/main/java/org/primefaces/component/api/DynamicColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/column/ColumnBase.java
  primefaces/src/main/java/org/primefaces/component/columns/ColumnsBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableCSVExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableXMLExporter.java
  primefaces/src/main/java/org/primefaces/component/export/ColumnValue.java
  primefaces/src/main/java/org/primefaces/component/export/ExcelOptions.java
  primefaces/src/main/java/org/primefaces/component/export/ExporterUtils.java
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableCSVExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTablePDFExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableXMLExporter.java
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
  primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java
Labels: new feature

#10612 Fix #10609: Colorpicker double conversion
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker003Test.java
  primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java
Labels: :zap: performance

#10624 InputNumber maxlength docs incorrect
  docs/12_0_0/components/inputnumber.md
  docs/13_0_0/components/inputnumber.md
  docs/14_0_0/components/inputnumber.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#10625 Fix #10609: 13.0.1 Colorpicker double conversion
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/colorpicker/ColorPicker003Test.java
  primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java
Labels: :zap: performance

#10627 Mojarra 2.3.21
  pom.xml
  primefaces-showcase/pom.xml
Labels: dependencies

#10633 Fix #10044: DatePicker viewdate default to input date first
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#10634 Fix #10044: 13.0.1 DatePicker viewdate default to input date first
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#10637 Fix #10636: Messages close icon wrong position
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#10638 Fix #10636: 13.0.1 Messages close icon wrong position
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#10649 Fix #10645: 13.0.2 Datepicker JS error on init
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10648 Fix #10646: Picklist Selenium improved selectors
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/PickList.java
Labels: :lady_beetle: defect

#10650 Fix #10646: 13.0.2 Picklist Selenium improved selectors
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/PickList.java
Labels: :lady_beetle: defect

#10651 Fix #10645: Datepicker handle multiple date initial value
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10660 Fix #10653: 13.0.2 Panel add ARIA role to toggleable header
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/panel/Panel001Test.java
  primefaces/src/main/java/org/primefaces/component/panel/PanelRenderer.java
Labels: accessibility

#10589 Fix #10588: Hindi translation
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hi.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: enhancement

#10666 Locale: Add Austrian German
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/layout.css
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
Labels: documentation

#10659 Fix #10658: CSP wrap FastStringWriter
  primefaces/src/main/java/org/primefaces/csp/CspPartialResponseWriter.java
  primefaces/src/main/java/org/primefaces/csp/CspResponseWriter.java
Labels: :lady_beetle: defect

#10664 Fix #10654: CSP handling of encodeIndexedId
  primefaces/src/main/java/org/primefaces/csp/CspResponseWriter.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: :lady_beetle: defect

#10670 Fix #10654/#10658: 13.0.2 CSP fixes
  primefaces/src/main/java/org/primefaces/csp/CspPartialResponseWriter.java
  primefaces/src/main/java/org/primefaces/csp/CspResponseWriter.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: :lady_beetle: defect

#10661 Fix #10656 - DataExporter: Introducing bufferSize to avoid OOM
  docs/14_0_0/components/dataexporter.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporter.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporterTagHandler.java
  primefaces/src/main/java/org/primefaces/component/export/ExportConfiguration.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: new feature, :zap: performance

#10684 Fix #10681: JPALazyDataModel case sensitive filters
  docs/14_0_0/components/datatable.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/model/JpaLazyDataModel.java
Labels: enhancement

#10686 Fix #10685: JPALazyDataModel wildcard support
  docs/14_0_0/components/datatable.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/model/JpaLazyDataModel.java
Labels: enhancement

#10698 Fix #10695: 13.0.2 SelectManyCheckbox lineDirection/pageDirection fix
  primefaces-showcase/src/main/webapp/ui/input/manyCheckbox.xhtml
  primefaces/src/main/java/org/primefaces/component/selectmanycheckbox/SelectManyCheckboxRenderer.java
Labels: :lady_beetle: defect

#10703 Fix #10702: CurrencyValidator test fix
  primefaces/src/test/java/org/primefaces/util/CurrencyValidatorTest.java
Labels: :lady_beetle: defect

#10704 Fix #10702: 13.0.2 CurrencyValidator test fix
  primefaces/src/test/java/org/primefaces/util/CurrencyValidatorTest.java
Labels: :lady_beetle: defect

#10701 Fix #10696: SelectManyCheckbox responsive updates
  primefaces/src/main/java/org/primefaces/component/selectmanycheckbox/SelectManyCheckboxRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/grid/grid.css
Labels: enhancement

#10550 Fix #10549 - UITable: cache columns when possible
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable033.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable033.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable033Test.java
  primefaces/src/main/java/org/primefaces/component/api/ColumnAware.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/columns/Columns.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTable.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: enhancement, :zap: performance

#10626 Fix #10557: Rating not setting value on cancel event
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/rating/Rating001.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/rating/Rating001Test.java
  primefaces/src/main/java/org/primefaces/component/rating/Rating.java
Labels: :lady_beetle: defect

#10711 Fix #10557: 13.0.2 Rating not setting value on cancel event
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/rating/Rating001.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/rating/Rating001Test.java
  primefaces/src/main/java/org/primefaces/component/rating/Rating.java
Labels: :lady_beetle: defect

#10709 Fix #10693: Tabview fix for active tab unrendered
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10710 Fix #10693: 13.0.2 Tabview fix for active tab unrendered
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :lady_beetle: defect

#10715 Fix #10714: Inputs allow CTRL+A/CTRL+C
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#10718 Fix #10714: 13.0.2 Inputs allow CTRL+A/CTRL+C
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#10719 Fix #10694: 13.0.2 Splitter hide until initial sizing complete
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
Labels: enhancement

#10722 Fix #10721: SelectOneMenu return focus to input
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#10723 Fix #10721: 13.0.2 SelectOneMenu return focus to input
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#10724 Fix #10684: JPA case sensitive use Faces Locale
  primefaces/src/main/java/org/primefaces/model/JpaLazyDataModel.java
Labels: enhancement

#10728 Fix #10725: Datepicker Today button should update time
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker004Test.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10729 Fix #10727: DatePicker hour validation
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10731 Fix #10726: Radio add ui-state-readonly
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: enhancement

#10736 Fix #10733: Filedownload docs fix
  docs/10_0_0/components/filedownload.md
  docs/11_0_0/components/filedownload.md
  docs/12_0_0/components/filedownload.md
  docs/13_0_0/components/filedownload.md
  docs/14_0_0/components/filedownload.md
  docs/7_0/components/filedownload.md
  docs/8_0/components/filedownload.md
Labels: documentation

#10732 Fix #10727: 13.0.2 DatePicker hour validation
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10734 Fix #10726: 13.0.2 Radio add ui-state-readonly
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: enhancement

#10735 Fix #10725: 13.0.2 Datepicker Today button should update time
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker004Test.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10742 Fix #10739: DatePicker showTime=true if timeOnly=true
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10743 Fix #10740: ColumnToggler cleanse tooltips
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
Labels: :lady_beetle: defect

#10744 Fix #10741: Paginator aria-current="page"
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: accessibility

#10745 Fix #10741: 13.0.2 Paginator aria-current="page"
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: accessibility

#10746 Fix #10740: 13.0.2 ColumnToggler cleanse tooltips
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
Labels: :lady_beetle: defect

#10747 Fix #10739: 13.0.2 DatePicker showTime=true if timeOnly=true
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#10750 Apache POI 5.2.4, Commons IO 2.13.0
  docs/14_0_0/gettingstarted/dependencies.md
  pom.xml
  primefaces-showcase/pom.xml
Labels: dependencies, java
