Repository primefaces/primefaces, pull requests merged in 2023-12, with the labels that each got.

#11058 Fix #11055: 13.0.4 TreeTable/DataTable delay sticky header render
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11057 Fix #11055: TreeTable/DataTable delay sticky header render
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11070 Fix #11065: 13.0.4 Dialog absolute position scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11069 Fix #11065: Dialog absolute position scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11074 Fix #11073: BlockUI better handling of removed DOM elements
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#11077 #11071 - Better spanish translation
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
Labels: documentation

#11079 Fix #11078: Datatable fix reflow + edit
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11080 Fix #11078: 13.0.4 Datatable fix reflow + edit
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11083 Fix #11076: 13.0.4 Colorpicker input in dialog
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
Labels: :lady_beetle: defect

#11095 Fix #11094: Datatable collapseAllRows docs
  docs/12_0_0/components/datatable.md
  docs/13_0_0/components/datatable.md
  docs/14_0_0/components/datatable.md
Labels: documentation

#11093 Fix #11092 - DataTable: Composite component not working in cellEditor
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/ajaxstatus/AjaxStatusRenderer.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java
  primefaces/src/main/java/org/primefaces/component/card/CardRenderer.java
  primefaces/src/main/java/org/primefaces/component/carousel/CarouselRenderer.java
  primefaces/src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java
  primefaces/src/main/java/org/primefaces/component/chronoline/ChronolineRenderer.java
  primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java
  primefaces/src/main/java/org/primefaces/component/confirmpopup/ConfirmPopupRenderer.java
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGridRenderer.java
  primefaces/src/main/java/org/primefaces/component/datalist/DataList.java
  primefaces/src/main/java/org/primefaces/component/datalist/DataListRenderer.java
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramRenderer.java
  primefaces/src/main/java/org/primefaces/component/dialog/DialogRenderer.java
  primefaces/src/main/java/org/primefaces/component/export/ExporterUtils.java
  primefaces/src/main/java/org/primefaces/component/feedreader/FeedReaderRenderer.java
  primefaces/src/main/java/org/primefaces/component/fieldset/FieldsetRenderer.java
  primefaces/src/main/java/org/primefaces/component/galleria/GalleriaRenderer.java
  primefaces/src/main/java/org/primefaces/component/inplace/InplaceRenderer.java
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/orderlist/OrderListRenderer.java
  primefaces/src/main/java/org/primefaces/component/outputpanel/OutputPanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/panel/Panel.java
  primefaces/src/main/java/org/primefaces/component/panel/PanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java
  primefaces/src/main/java/org/primefaces/component/picklist/PickListRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectmanycheckbox/SelectManyCheckboxRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
  primefaces/src/main/java/org/primefaces/component/subtable/SubTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/tabview/Tab.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/java/org/primefaces/component/texteditor/TextEditorRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineRenderer.java
  primefaces/src/main/java/org/primefaces/component/toolbar/ToolbarRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/wizard/WizardRenderer.java
  primefaces/src/main/java/org/primefaces/event/CellEditEvent.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
  primefaces/src/main/java/org/primefaces/util/FacetUtils.java
  primefaces/src/test/java/org/primefaces/util/ComponentUtilsTest.java
Labels: enhancement

#11106 Fix #11104/#11103: SelectOneMenu keyboard with filter open
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#11107 Fix #11104/#11103: 13.0.4 SelectOneMenu keyboard with filter open
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#11108 Fix #11101: SelectCheckboxMenu fix trigger
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: accessibility

#11109 Fix #11101: 13.0.4 SelectCheckboxMenu fix trigger
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: accessibility

#11113 Fix #11102 - 13.0.4 Issue 6354 breaks the predefined Grid CSS columns style …
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGridRenderer.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
Labels: :lady_beetle: defect

#11114 Fix #11102 - Issue 6354 breaks the predefined Grid CSS columns style …
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGridRenderer.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
Labels: :lady_beetle: defect

#11099 #10988 StaticMessage closable
  docs/14_0_0/components/staticmessage.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/message/MessagesView.java
  primefaces-showcase/src/main/webapp/ui/message/staticMessage.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/staticmessage/StaticMessage.java
  primefaces/src/main/java/org/primefaces/component/staticmessage/StaticMessageBase.java
  primefaces/src/main/java/org/primefaces/component/staticmessage/StaticMessageRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/staticmessage/staticmessage.css
  primefaces/src/main/resources/META-INF/resources/primefaces/staticmessage/staticmessage.js
Labels: enhancement

#11116 Fix #11115: DatePicker consistent hide()
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#11117 Fix #11115: 13.0.4 DatePicker consistent hide()
  primefaces-showcase/src/main/webapp/WEB-INF/footer.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#11124 SelectManyCheckbox Ajax Events docs
  docs/12_0_0/components/selectmanycheckbox.md
  docs/13_0_0/components/selectmanycheckbox.md
  docs/14_0_0/components/selectmanycheckbox.md
  primefaces-showcase/src/main/webapp/WEB-INF/footer.xhtml
Labels: documentation

#11126 Fix #11125: Filter triggered by cut and paste
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11127 Fix #11125: 13.0.4 Filter triggered by cut and paste
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11132 Autonumeric 4.10.1
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: dependencies, javascript

#11137 Fix #11134: FileUpload unescape proper URL chars
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: integration_test

#11136 Fixes #11135 - DataTable/TreeTable: support composite as filter
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/event/CellEditEvent.java
  primefaces/src/main/java/org/primefaces/model/FilterMeta.java
  primefaces/src/main/java/org/primefaces/util/ComponentTraversalUtils.java
  primefaces/src/main/java/org/primefaces/util/FacetUtils.java
Labels: enhancement

#11138 Fix #11135: Composite filter integration test
  primefaces-integration-tests/src/main/webapp/datatable/dataTable043.xhtml
  primefaces-integration-tests/src/main/webapp/resources/composite/dataTableFilter.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable043Test.java
Labels: integration_test

#11131 Fix #11130: Respect OS prefers-reduced-motion setting
  docs/14_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.env.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: accessibility

#11141 Fix #11140: Datepicker previous next calculation
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11142 Fix #11140: 13.0.4 Datepicker previous next calculation
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11149 check all messages attached to target of p:message (#11148)
  primefaces/src/main/java/org/primefaces/component/message/MessageRenderer.java
Labels: :lady_beetle: defect

#11152 Fix #11148: Message integration test
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/message/Message001.java
  primefaces-integration-tests/src/main/webapp/message/message001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/message/Message001Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Message.java
Labels: integration_test

#11153 Fix #11148: 13.0.5 Message fix for multiple messages
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/message/Message001.java
  primefaces-integration-tests/src/main/webapp/message/message001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/message/Message001Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Message.java
  primefaces/src/main/java/org/primefaces/component/message/MessageRenderer.java
Labels: :lady_beetle: defect

#11158 Fix #9260: DatePicker duplicate onChange events
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#11159 Fix #9260: 13.0.5 DatePicker duplicate onChange events
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11161 #11155 SplitButton border radius
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#11163 Fix #11162: Space and NumpadEnter
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.cascadeselect.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanymenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
  primefaces/src/main/resources/META-INF/resources/primefaces/terminal/terminal.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: accessibility

#11164 Fix idletimer version in docs
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/idlemonitor/0-jquery.idletimer.js
Labels: documentation

#11157 Message(s): add composite support (#3796)
  primefaces/src/main/java/org/primefaces/component/message/MessageRenderer.java
  primefaces/src/main/java/org/primefaces/component/message/MessageState.java
  primefaces/src/main/java/org/primefaces/renderkit/UINotificationRenderer.java
Labels: enhancement

#11168 Fix #3796: Message composite integration test
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/general/component/InputTextComponent.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/message/Message002.java
  primefaces-integration-tests/src/main/webapp/message/message002.xhtml
  primefaces-integration-tests/src/main/webapp/resources/composite/inputTextTooltip.xhtml
  primefaces-integration-tests/src/main/webapp/resources/composite/inputTextTooltipHolder.xhtml
  primefaces-integration-tests/src/main/webapp/resources/composite/inputTextTooltipHolderWithComposite.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/message/Message002Test.java
Labels: integration_test

#11169 Fix #5782: Datatable RTL column resizing
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: rtl

#11170 Fix #5782: 13.0.5 Datatable RTL column resizing
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11171 Fix #9622: Datatable RTL horizontal scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11172 Fix #9622: 13.0.5 Datatable RTL horizontal scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11174 Fix #11173: Selenium: DeploymentAdapter is required
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/BootstrapExtension.java
Labels: integration_test

#11175 Fix #11173: 13.0.5 Selenium: DeploymentAdapter is required
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/BootstrapExtension.java
Labels: :lady_beetle: defect

#11176 Fix #2330: SelectManyMenu/SelectOneListBox itemSelect/Unselect AJAX events
  docs/14_0_0/components/multiselectlistbox.md
  docs/14_0_0/components/selectmanymenu.md
  docs/14_0_0/components/selectonelistbox.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SelectManyView.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SelectOneView.java
  primefaces-showcase/src/main/webapp/ui/input/listbox.xhtml
  primefaces-showcase/src/main/webapp/ui/input/manyMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/api/PrimeClientBehaviorHolder.java
  primefaces/src/main/java/org/primefaces/component/multiselectlistbox/MultiSelectListbox.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenu.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuBase.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListbox.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxBase.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectlistbox.js
Labels: enhancement

#11180 Fix #31: MenuBar/TieredMenu RTL support
  docs/14_0_0/components/menubar.md
  docs/14_0_0/components/tieredmenu.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/dock/DockBase.java
  primefaces/src/main/java/org/primefaces/component/menu/AbstractMenu.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenu.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: new feature

#11181 Fix #1388: Horizontal Tree RTL
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/tree/Tree.java
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.css
Labels: enhancement, rtl

#11184 Fix #11091: DataExporter migration guide 13.0.0
  docs/migrationguide/13_0_0.md
Labels: documentation

#11190 Fix #11188: GMap add key placeholder
  primefaces-showcase/src/main/webapp/ui/data/gmap/addMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/circles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/controls.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/draggableMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/event.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/geocode.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/infoWindow.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/mapDialog.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markerSelection.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polygons.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polylines.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/rectangles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/street.xhtml
Labels: documentation

#11192 Fix #11188: GMap add key
  primefaces-showcase/src/main/webapp/ui/data/gmap/addMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/circles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/controls.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/draggableMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/event.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/geocode.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/infoWindow.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/mapDialog.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markerSelection.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polygons.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polylines.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/rectangles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/street.xhtml
Labels: documentation

#11193 Fix #11182/#11155: 13.0.5 Splitbutton/TabMenu Theme fixes
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: :lady_beetle: defect, theme

#11194 Fix #11188: 13.0.5 GMap add key
  primefaces-showcase/src/main/webapp/ui/data/gmap/addMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/circles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/controls.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/draggableMarkers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/event.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/geocode.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/infoWindow.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/mapDialog.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markerSelection.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/markers.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polygons.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/polylines.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/rectangles.xhtml
  primefaces-showcase/src/main/webapp/ui/data/gmap/street.xhtml
Labels: documentation

#11200 Fix #11199: wait for close button to get focus
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/dialog/Dialog002Test.java
Labels: integration_test

#11205 Fix #11203: Tree003Test add pause between keypresses
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/tree/Tree003Test.java
Labels: integration_test
