Repository primefaces/primefaces, pull requests merged in 2024-10, with the labels that each got.

#12655 Fix #12654: Widget preConstruct hook and docs
  docs/15_0_0/core/widgets.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/ajax/lifecycle.xhtml
  primefaces/src/main/java/org/primefaces/component/api/Widget.java
  primefaces/src/main/java/org/primefaces/util/WidgetBuilder.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
Labels: new feature

#12549 Fix #12511: Datatable/TreeTable filterNormalize
  docs/15_0_0/components/datatable.md
  docs/15_0_0/components/treetable.md
  docs/15_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableBase.java
  primefaces/src/main/java/org/primefaces/component/treetable/feature/FilterFeature.java
  primefaces/src/main/java/org/primefaces/model/FilterMeta.java
  primefaces/src/main/java/org/primefaces/util/LangUtils.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/test/java/org/primefaces/util/LangUtilsTest.java
Labels: enhancement

#12678 Fix #12677: Schedule tooltip was transparent
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/build/src/main.css
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/fullcalendar.min.css
Labels: :lady_beetle: defect

#12679 Fix #12677: 14.0.6 Schedule tooltip was transparent
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/build/src/main.css
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/fullcalendar.min.css
Labels: :lady_beetle: defect

#12686 Fix #12682: 14.0.6 InputNumber float label with symbol
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12667 Fix #12661: BlockUI block mouse/keyboard events
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#12676 Fix #12661: 14.0.6 BlockUI block mouse/keyboard events
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#12693 Fix typo in commandLink.html
  docs/vdldoc/p/commandLink.html
Labels: documentation

#12691 Fixes #12664 - Add utility to get server-side widget easily, similar to PF(...) on the client side
  docs/15_0_0/core/javaAPI.md
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
Labels: new feature

#12696 Fix #12694: AjaxStatus handle Faces completion
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
Labels: :lady_beetle: defect

#12697 Fix #12694: 14.0.6 AjaxStatus handle Faces completion
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
Labels: :lady_beetle: defect

#12702 14.0.6 POI 5.3.0 and Proper shading of classes
  docs/14_0_0/gettingstarted/dependencies.md
  pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/misc/PrimeIconsView.java
  primefaces/pom.xml
Labels: enhancement

#12670 Fix #12666: Datatable: filtering with BigDecimal
  primefaces/src/main/java/org/primefaces/model/filter/EqualsFilterConstraint.java
  primefaces/src/main/java/org/primefaces/model/filter/ExactFilterConstraint.java
Labels: :lady_beetle: defect

#12711 Fix #12708: 14.0.6 SelectCheckBoxMenu taglib updates
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12712 Fix #12708: SelectCheckBoxMenu taglib updates
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12713 Fix #12666: 14.0.6 Datatable: filtering with BigDecimal
  primefaces/src/main/java/org/primefaces/model/filter/EqualsFilterConstraint.java
  primefaces/src/main/java/org/primefaces/model/filter/ExactFilterConstraint.java
Labels: :lady_beetle: defect

#12716 Fix #12707: 14.0.6 Picklist check for String matrix
  primefaces/src/main/java/org/primefaces/component/picklist/PickListRenderer.java
Labels: :lady_beetle: defect

#12719 Autonumeric 4.10.6
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: dependencies, javascript

#12724 Chart.js 4.4.5
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/chart/0-chartjs.min.js
Labels: dependencies

#12738 Fix #12737: 14.0.7 killswitch() widget existence checks
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#12739 Fix #12737: killswitch() widget existence checks
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#12741 Fix #12740: Terminate Poller/IdleMonitor on ajax `update="@all"`
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12742 Fix #12740: 14.0.7 Terminate Poller/IdleMonitor on AJAX update="@all"
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12748 Mixed Chart Example
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chartjs/ChartView.java
  primefaces-showcase/src/main/webapp/ui/chart/mixed.xhtml
Labels: documentation

#12755 Fixes #10909 - removed deprecated FileUpload properties
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: breaking-change

#12735 Fix #12731: Export columns in correct order after reorder
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
Labels: :lady_beetle: defect

#12745 Fix #12731: 14.0.7 Export columns in correct order after reorder
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/texteditor/TextEditor001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/texteditor/TextEditor002Test.java
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
Labels: :lady_beetle: defect

#12759 Fixes primefaces#12722 - FileUpload: always try to use messages used in update attr first to display errors
  docs/15_0_0/components/message.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload005Test.java
  primefaces/src/main/java/org/primefaces/component/growl/GrowlRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
Labels: enhancement

#12763 Fix #12744 14.0.7 Datatable: supports multiple editableValueHolder in filters
  primefaces/src/main/java/org/primefaces/util/CompositeUtils.java
  primefaces/src/main/java/org/primefaces/util/FacetUtils.java
Labels: enhancement

#12766 Fix #12765: @widgetVar allow hyphen and underscores in widget names
  primefaces/src/main/java/org/primefaces/component/api/Widget.java
  primefaces/src/main/java/org/primefaces/expression/WidgetVarSearchKeywordResolver.java
Labels: :lady_beetle: defect

#12768 Fix #12765: 14.0.7 @widgetVar allow hyphen and underscores in widget names
  primefaces/src/main/java/org/primefaces/component/api/Widget.java
  primefaces/src/main/java/org/primefaces/expression/WidgetVarSearchKeywordResolver.java
Labels: :lady_beetle: defect

#12774 Document animations
  docs/15_0_0/core/ajaxJavascriptApi.md
  docs/15_0_0/core/animations.md
  docs/15_0_0/menu.md
Labels: documentation

#12776 Fix #12771: 14.0.7 AJAX resolving clientIds of currently unrendered should not throw a exception
  primefaces/src/main/java/org/primefaces/expression/WidgetVarSearchKeywordResolver.java
  primefaces/src/main/java/org/primefaces/util/AjaxRequestBuilder.java
Labels: :lady_beetle: defect

#12777 Fixes #12773 - Advanced FileUpload: rendering of error messages broken with p:message
  primefaces-showcase/src/main/webapp/ui/message/messages.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
Labels: :lady_beetle: defect

#12785 Fixes #12089 - DatePicker: add Week Picker, similar to Month Picker
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarJava8View.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces-themes/theme-base/components/button/_button.scss
  primefaces-themes/theme-base/components/button/_speeddial.scss
  primefaces-themes/theme-base/components/button/_splitbutton.scss
  primefaces-themes/theme-base/components/data/_picklist.scss
  primefaces-themes/theme-base/components/data/_tree.scss
  primefaces-themes/theme-base/components/file/_fileupload.scss
  primefaces-themes/theme-base/components/input/_autocomplete.scss
  primefaces-themes/theme-base/components/input/_checkbox.scss
  primefaces-themes/theme-base/components/input/_chips.scss
  primefaces-themes/theme-base/components/input/_datepicker.scss
  primefaces-themes/theme-base/components/input/_inplace.scss
  primefaces-themes/theme-base/components/input/_inputgroup.scss
  primefaces-themes/theme-base/components/input/_radiobutton.scss
  primefaces-themes/theme-base/components/input/_selectcheckboxmenu.scss
  primefaces-themes/theme-base/components/input/_selectonelistbox.scss
  primefaces-themes/theme-base/components/input/_selectonemenu.scss
  primefaces-themes/theme-base/components/input/_slider.scss
  primefaces-themes/theme-base/components/input/_spinner.scss
  primefaces-themes/theme-base/components/input/_toggleswitch.scss
  primefaces-themes/theme-base/components/menu/_menu.scss
  primefaces-themes/theme-base/components/misc/_chip.scss
  primefaces-themes/theme-base/components/misc/_tag.scss
  primefaces-themes/theme-base/components/overlay/_overlaypanel.scss
  primefaces-themes/theme-base/components/panel/_accordion.scss
  primefaces-themes/theme-base/components/panel/_panel.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-dark-common/extensions/_chips.scss
  primefaces-themes/themes/primefaces-material-dark-common/extensions/_selectcheckboxmenu.scss
  primefaces-themes/themes/primefaces-material-dark-common/extensions/_toggleswitch.scss
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-light-common/extensions/_chips.scss
  primefaces-themes/themes/primefaces-material-light-common/extensions/_selectcheckboxmenu.scss
  primefaces-themes/themes/primefaces-material-light-common/extensions/_toggleswitch.scss
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#12790 Fix #12089: DatePicker weekview doc updates
  docs/14_0_0/components/datepicker.md
  docs/15_0_0/components/datepicker.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12791 Fix #12089: 14.0.7 DatePicker weekview
  docs/14_0_0/components/datepicker.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarJava8View.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#12793 Fix #6944: 14.0.7 Timeline: null value when used inside a composite
  primefaces/src/main/java/org/primefaces/component/timeline/DefaultTimelineUpdater.java
Labels: :lady_beetle: defect

#12780 Fix #12779: Signature better text position
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/1-widget.js
Labels: :lady_beetle: defect

#12781 Fix #12779: 14.0.7 Signature better text position
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/1-widget.js
Labels: :lady_beetle: defect

#12796 Chart.js 4.4.6
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/chart/0-chartjs.min.js
Labels: dependencies, javascript

#12807 Fix #12805: SelectBooleanButton remove label attribute
  docs/14_0_0/components/selectbooleanbutton.md
  docs/15_0_0/components/selectbooleanbutton.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12806 Fix #12805: 14.0.7 SelectBooleanButton remove label attribute
  docs/14_0_0/components/selectbooleanbutton.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12800 Fix #12799: http://xmlns.jcp.org/xml/ns/javaee/web-facelettaglibrary_2_3.xsd
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12817 Fix #12811: jQuery UI 1.14.1
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js
Labels: dependencies, javascript
