Repository primefaces/primefaces, pull requests merged in 2024-03, with the labels that each got.

#11541 Fix #11537: Filter ENTER key prevent form submit
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11542 Fix #11537: 13.0.7 Filter ENTER key prevent form submit
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11546 Fix #11545: DatePicker timepicker mouseleave for mouseout
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11535 Fix #11534: Password toggle mask accessibility
  primefaces-showcase/src/main/webapp/ui/input/password.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
Labels: accessibility

#11559 13.0.8: LibrePDF 1.3.42 and JSON 20240303
  pom.xml
Labels: enhancement, dependencies

#11552 Fix #11551: DefaultCommand focus button before trigger
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: enhancement

#11543 Fix #11540: Picklist trigger input changes on transfer
  docs/14_0_0/components/picklist.md
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/component/picklist/PickList.java
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: enhancement

#11567 Fix #11539: Typedoc updates
  primefaces/pom.xml
  primefaces/src/main/type-definitions/package-lock.json
  primefaces/src/main/type-definitions/package.json
  primefaces/src/main/type-definitions/tsconfig.typedoc.json
Labels: documentation

#11568 jQuery Rangy 1.2.0
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.rangy.js
Labels: dependencies

#11571 Coloris 0.23.0
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-coloris.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-colorpicker.css
Labels: dependencies, javascript

#11579 jQuery UI Touch Punch 1.1.1
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.touch-punch.js
Labels: dependencies, javascript

#11583 Fix #11582: getResourceScriptURI() iterate until found
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.resources.js
Labels: :lady_beetle: defect

#11584 Fix #11582: 13.0.8 getResourceScriptURI() iterate until found
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.resources.js
Labels: :lady_beetle: defect

#11587 Fix #11586: Radio unregister events before new events
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectoneradio.js
Labels: :lady_beetle: defect

#11588 Fix #11586: 13.0.8 Radio unregister events before new events
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectoneradio.js
Labels: :lady_beetle: defect

#11593 Fix #11590: InputMask handle escape character '\'
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
  primefaces/src/test/java/org/primefaces/component/inputmask/InputMaskRendererTest.java
Labels: :lady_beetle: defect

#11594 Fix #11590: 13.0.8 InputMask handle escape character '\'
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
  primefaces/src/test/java/org/primefaces/component/inputmask/InputMaskRendererTest.java
Labels: :lady_beetle: defect

#11591 Fix #11589: DataScroller update lazy rowCount for facet
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java
Labels: :lady_beetle: defect

#11592 Fix #11589: 13.0.8 DataScroller update lazy rowCount for facet
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerRenderer.java
Labels: :lady_beetle: defect

#11597 Fix #11595: CSP wrap custom FacesException
  primefaces/src/main/java/org/primefaces/csp/CspException.java
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: enhancement

#11602 jQuery UI Touch Punch 1.1.3
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.touch-punch.js
Labels: dependencies, javascript

#11604 Fix #11569: Core JS setGlobalLocaleValue
  docs/14_0_0/core/localization.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: enhancement

#11603 Fix #11598: Datatable sticky z-index with existing sticky
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sticky/sticky.js
Labels: :lady_beetle: defect

#11601 Fix #11598: 13.0.8 Datatable sticky z-index with existing sticky
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sticky/sticky.js
Labels: :lady_beetle: defect

#11607 Fix #10946: 13.0.8 CSP add nonce only to JSF forms
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable018.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectonemenu/SelectOneMenu012.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectonemenu/SelectOneMenu013.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
Labels: enhancement

#11610 JFreeChart 1.5.4
  .gitignore
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/multimedia/GraphicImageView.java
Labels: dependencies

#11622 PaginatorPosition docs
  docs/10_0_0/components/datatable.md
  docs/11_0_0/components/datatable.md
  docs/12_0_0/components/datatable.md
  docs/13_0_0/components/datatable.md
  docs/14_0_0/components/datatable.md
  docs/7_0/components/datatable.md
  docs/8_0/components/datatable.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11617 jQuery UI Touch Punch 1.1.4
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.touch-punch.js
Labels: dependencies, javascript

#11616 Fix #11615: OutputLabel RTL support
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabel.java
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelBase.java
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: enhancement, rtl

#11620 Fix #11619: ExporterOptions extend Serializable
  primefaces/src/main/java/org/primefaces/component/export/ExporterOptions.java
Labels: :lady_beetle: defect

#11621 Fix #11619: 13.0.8 ExporterOptions extend Serializable
  primefaces/src/main/java/org/primefaces/component/export/ExporterOptions.java
Labels: :lady_beetle: defect

#11633 GMap doc updates
  docs/10_0_0/components/gmap.md
  docs/11_0_0/components/gmap.md
  docs/12_0_0/components/gmap.md
  docs/13_0_0/components/gmap.md
  docs/14_0_0/components/gmap.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11635 Fix #11634: Galleria show(index) widget method
  docs/14_0_0/components/galleria.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/1-galleria.js
Labels: enhancement

#11646 #11645 DatePicker lazy inline
  primefaces-showcase/src/main/webapp/ui/input/datepicker/metadata.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#11648 #11645 13.0.8 DatePicker lazy inline
  primefaces-showcase/src/main/webapp/ui/input/datepicker/metadata.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#11653 Fix #11650: Datatable do not make first/last column resizable after drop
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11654 Fix #11650: 13.0.8 Datatable do not make first/last column resizable …
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11655 Fix #11652: InputNumber respect cut/copy/paste
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#11656 Fix #11652: 13.0.8 InputNumber respect cut/copy/paste
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#11657 #11644 Disable DatePicker on Ajax
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/datepicker.css
Labels: new feature

#11662 Fix #11660: 13.0.8 Spinner round properly in case of string value
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11661 Fix #11660: Spinner round properly in case of string value
  primefaces-integration-tests/src/main/webapp/spinner/spinner005.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner005Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#11667 Showcase: PrismJS 1.29.0
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/_syntax.scss
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/layout.css
  primefaces-showcase/src/main/webapp/resources/showcase/script/prism.js
Labels: documentation

#11670 NotificationBar add back to showcase
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
Labels: documentation

#11673 Macro-optimization for DefaultResolver#get
  primefaces/src/main/java/org/primefaces/util/PropertyDescriptorResolver.java
Labels: :zap: performance

#11672 Fix #11671 - DefaultLazyDataModel: make it compatible with other lazy-able components
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
Labels: new feature

#11675 Fix component classes in docs
  docs/10_0_0/components/panelgrid.md
  docs/10_0_0/components/picklist.md
  docs/11_0_0/components/panelgrid.md
  docs/11_0_0/components/picklist.md
  docs/12_0_0/components/panelgrid.md
  docs/12_0_0/components/picklist.md
  docs/13_0_0/components/panelgrid.md
  docs/13_0_0/components/picklist.md
  docs/14_0_0/components/panelgrid.md
  docs/14_0_0/components/picklist.md
  docs/7_0/components/panelgrid.md
  docs/7_0/components/picklist.md
  docs/8_0/components/panelgrid.md
  docs/8_0/components/picklist.md
Labels: documentation

#11639 Fix #11623/#11577: NVDA issues with ui-helper-hidden-accessible
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.css
Labels: accessibility

#11676 Fix #11674: Tree add filterDelay, filterEvent
  docs/14_0_0/components/datatable.md
  docs/14_0_0/components/tree.md
  docs/14_0_0/components/treetable.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/data/tree/filter.xhtml
  primefaces/src/main/java/org/primefaces/component/tree/TreeBase.java
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: enhancement

#11679 13.0.8 OWASP Sanitizer 20240325.1
  pom.xml
Labels: dependencies, java

#11585 Fix #11578: Dialog resize observer
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: enhancement

#11687 Fix #11684: jQuery CaretPosition lazily create DIV
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.caretposition.js
Labels: :zap: performance

#11688 Fix #11663: PrimeIcons v7.0.0
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/misc/PrimeIconsView.java
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.css
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.eot
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.svg
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.ttf
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.woff
  primefaces/src/main/resources/META-INF/resources/primefaces/primeicons/primeicons.woff2
Labels: enhancement

#11693 Fix #11692: jQuery remove event leak
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
Labels: :zap: performance
