Repository primefaces/primefaces, pull requests merged in 2024-01, with the labels that each got.

#11202 Fix #11201: Update TabView Accessibility
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/TabView.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: accessibility

#11186 Fix #11044 - FileUpload: move server side validation to a own p:validateFile
  docs/14_0_0/menu.md
  docs/14_0_0/validators/validateFile.md
  docs/migrationguide/14_0_0.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/MenuCategory.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/MenuItem.java
  primefaces-showcase/src/main/webapp/WEB-INF/menu.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/basic.xhtml
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/java/org/primefaces/component/fileupload/NativeFileUploadDecoder.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/java/org/primefaces/util/MessageFactory.java
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: enhancement

#11185 Fix #8119: SelectCheckBoxMenu itemSelect event
  docs/14_0_0/components/selectcheckboxmenu.md
  docs/14_0_0/components/selectmanymenu.md
  docs/14_0_0/components/selectonelistbox.md
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectManyMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CheckboxView.java
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenu.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenu.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListbox.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: enhancement

#11189 Fix #3921: Menu rebind trigger after AJAX update
  docs/14_0_0/components/slidemenu.md
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
Labels: enhancement

#11216 Fix #3210: Dialog reimplement minimize
  primefaces-integration-tests/src/main/webapp/dialog/dialog004.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/dialog/Dialog004Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Dialog.java
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11219 Fix #11218: AutoComplete add more source tabs to showcase
  primefaces-showcase/src/main/webapp/ui/input/autoComplete.xhtml
Labels: documentation

#11220 Fix #11218: 13.0.5 AutoComplete add more source tabs to showcase
  primefaces-showcase/src/main/webapp/ui/input/autoComplete.xhtml
Labels: documentation

#11217 Fix #10689: Organigram drop tolerance
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/extensions.txt
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
  primefaces/src/main/resources/META-INF/resources/primefaces/organigram/organigram.js
Labels: :lady_beetle: defect

#11221 Fix #10689: 13.0.5 Organigram drop tolerance
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/extensions.txt
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
  primefaces/src/main/resources/META-INF/resources/primefaces/organigram/organigram.js
Labels: :lady_beetle: defect

#11210 Fix #3551: Datatable remember multiple selection between AJAX updates
  primefaces-integration-tests/src/main/webapp/datatable/dataTable005.xhtml
  primefaces-integration-tests/src/main/webapp/datatable/dataTable005Array.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable005Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11213 Fix #11211: CLIENT_SIDE_LOCALISATION true by default
  docs/migrationguide/14_0_0.md
  primefaces-integration-tests/src/main/webapp/WEB-INF/web.xml
  primefaces-showcase/src/main/webapp/WEB-INF/web.xml
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
Labels: enhancement

#11222 Selection migration docs
  docs/migrationguide/14_0_0.md
  primefaces-showcase/src/main/webapp/ui/data/datatable/selection.xhtml
Labels: documentation

#11215 Fixes #11043 - Advanced FileUpload: migrate client side validation to CSV
  docs/14_0_0/components/fileupload.md
  docs/14_0_0/core/csvJavascriptAPI.md
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/fileupload/FileUploadView.java
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload000.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload001.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload002.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload003.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload004.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload005.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload006.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload007.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload008.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload009.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload010.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload011.xhtml
  primefaces-integration-tests/src/main/webapp/fileupload/fileUpload012.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/AbstractFileUploadTest.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload000Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload004Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload005Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload006Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload007Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload008Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload009Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload010Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload011Test.java
  primefaces-showcase/src/main/webapp/ui/file/upload/auto.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/basicAuto.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/chunked.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/dnd.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/multiple.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/single.xhtml
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
  primefaces/src/main/type-definitions/core.d.ts
Labels: breaking-change

#11225 Fix #8475: Allow SHIFT range checkbox selection
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: enhancement

#11226 Fix #4725: Column accessible header text
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/expansion.xhtml
  primefaces-showcase/src/main/webapp/ui/data/treetable/basic.xhtml
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: accessibility

#11228 Fix #99: ConfirmDialog allow ajax=false submission
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001.java
  primefaces-integration-tests/src/main/webapp/confirmdialog/confirmDialog001.xhtml
  primefaces-integration-tests/src/main/webapp/confirmdialog/confirmDialog002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog002Test.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/overlay/ConfirmView.java
  primefaces-showcase/src/main/webapp/ui/overlay/confirmDialog.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: new feature

#11232 Fix #11230: CommandLink disabledOnAjax fix
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js
Labels: :lady_beetle: defect

#11233 Fix #11230: 13.0.5 CommandLink disabledOnAjax fix
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js
Labels: :lady_beetle: defect

#11235 Fix #3454: Confirm beforeShow docs
  docs/10_0_0/components/confirm.md
  docs/11_0_0/components/confirm.md
  docs/12_0_0/components/confirm.md
  docs/13_0_0/components/confirm.md
  docs/14_0_0/components/confirm.md
  docs/7_0/components/confirm.md
  docs/8_0/components/confirm.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11239 Fix #9201: Growl support simultaneous sticky display
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
Labels: enhancement

#11240 Fix #2478: ColumnTogglerEvent giving access to UIColumn
  docs/14_0_0/components/columntoggler.md
  docs/migrationguide/14_0_0.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/BasicView.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/columnToggler.xhtml
  primefaces/src/main/java/org/primefaces/component/columntoggler/ColumnToggler.java
  primefaces/src/main/java/org/primefaces/event/ColumnToggleEvent.java
Labels: enhancement

#11209 IT - take screenshots of failed tests
  .github/workflows/build.yml
  .github/workflows/nightly.yml
  primefaces-integration-tests-jakarta/src/test/resources-filtered/primefaces-selenium/config.properties
  primefaces-integration-tests/src/test/resources-filtered/primefaces-selenium/config.properties
  primefaces-selenium/README.md
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePageTest.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/ConfigProvider.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/junit/ScreenshotOnFailureExtension.java
Labels: integration_test

#11246 #11245 - Preserve jQuery.remove behavior
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
Labels: :lady_beetle: defect

#11247 Fix #11245 13.0.5 Preserve jQuery.remove behavior
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
Labels: :lady_beetle: defect

#11248 Fix #8950: DatePicker year as input number
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker011Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DatePicker.java
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/_core.scss
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/layout.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/datepicker.css
Labels: accessibility

#11257 Fix #11256: 13.0.5 Showcase build Jetty WAR
  primefaces-showcase/pom.xml
Labels: documentation

#11258 Fix #11256: Showcase build Jetty WAR
  primefaces-showcase/pom.xml
Labels: documentation

#11255 Fix #11254: SelectCheckboxMenu document collectionType
  docs/10_0_0/components/selectcheckboxmenu.md
  docs/11_0_0/components/selectcheckboxmenu.md
  docs/12_0_0/components/selectcheckboxmenu.md
  docs/13_0_0/components/selectcheckboxmenu.md
  docs/14_0_0/components/selectcheckboxmenu.md
  docs/7_0/components/selectcheckboxmenu.md
  docs/8_0/components/selectcheckboxmenu.md
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11260 Fix #11254: 13.0.5 SelectCheckboxMenu document collectionType
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11261 Fix #11252 13.0.5 Tree multiple drag
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: :lady_beetle: defect

#11244 Fix #5710: 13.0.5 OverlayPanel destroy widget if target is removed from DOM
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/overlaypanel/OverlayPanel002Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#11243 Fix #5710: OverlayPanel destroy widget if target is removed from DOM
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/overlaypanel/OverlayPanel002Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#11238 Fix #11023: 13.0.5 Draggable FrozenColumns fix
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: :lady_beetle: defect

#11268 SelectBooleanButtons AJAX docs
  docs/10_0_0/components/selectbooleanbutton.md
  docs/11_0_0/components/selectbooleanbutton.md
  docs/12_0_0/components/selectbooleanbutton.md
  docs/13_0_0/components/selectbooleanbutton.md
  docs/14_0_0/components/selectbooleanbutton.md
Labels: documentation

#11273 Fix #11229: OverlayPanel in dialog appendTo
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/overlaypanel/OverlayPanel002Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#11274 Fix #11229: 13.0.5 OverlayPanel in dialog appendTo
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/overlaypanel/OverlayPanel002Test.java
  primefaces-showcase/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#11178 #10258 Minimum Ajax load animation duration
  docs/14_0_0/core/ajaxJavascriptApi.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/commandbutton/CommandButton001.java
  primefaces-integration-tests/src/main/webapp/commandbutton/commandButton001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/commandbutton/CommandButton001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog002Test.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePageTest.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js
Labels: enhancement

#11276 Fix #11275: Close link ARIA improvements
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/panel/panel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sidebar/sidebar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/staticmessage/staticmessage.js
Labels: accessibility

#11277 Fix #11214: SplitButton theme update
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#11278 Fix #11214: 13.0.5 SplitButton theme update
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#11280 Fix #11279: 13.0.5 DatePicker now docs
  docs/13_0_0/core/localization.md
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
Labels: documentation

#11281 Fix #11279: DatePicker Now docs
  docs/13_0_0/core/localization.md
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
Labels: documentation

#8118 Fix #8113: Table filters now HTML5 search type
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: enhancement

#11283 Fix #11282: SelectOne placeholder styling
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#11284 Fix #11282: 13.0.5 SelectOne placeholder styling
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: theme

#11286 Fix #11285: LinkButton allow non-string value
  primefaces/src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java
Labels: :lady_beetle: defect

#11287 Fix #11285: 13.0.5 LinkButton allow non-string value
  primefaces/src/main/java/org/primefaces/component/linkbutton/LinkButtonRenderer.java
Labels: :lady_beetle: defect

#11292 Fix #11282: SelectOneMenu placeholder non-breaking space
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11293 Fix #11282: 13.0.5 SelectOneMenu placeholder non-breaking space
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11294 Fix #11290: Datatable selection disabled issues
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11295 Fix #11290: 13.0.5 Datatable selection disabled issues
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11297 Closes #11296: Button allow non-string value
  primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java
Labels: :lady_beetle: defect

#11299 Fix #11296: 13.0.5 Button allow non-string value
  primefaces/src/main/java/org/primefaces/component/button/ButtonRenderer.java
Labels: :lady_beetle: defect

#11300 Fix #5665 Chartjs: fixes to allow timeseries bar chart
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chartjs/ChartJsView.java
  primefaces/src/main/java/org/primefaces/model/charts/axes/cartesian/CartesianTime.java
  primefaces/src/main/java/org/primefaces/model/charts/bar/BarChartDataSet.java
Labels: enhancement

#11304 Fix #11301: 13.0.5 DefaultCommand CSP with ajax=false
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect

#11305 Fix #11301: DefaultCommand CSP with ajax=false
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect

#11309 AutoNumeric 4.10.4
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: dependencies, javascript

#11310 Fix #11308: Dialog ESC in correct order
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11311 Fix #11308: 13.0.5 Dialog ESC in correct order
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11313 #11312 Schedule: slotLabelFormat
  docs/10_0_0/components/schedule.md
  docs/11_0_0/components/schedule.md
  docs/12_0_0/components/schedule.md
  docs/13_0_0/components/schedule.md
  docs/7_0/components/schedule.md
  docs/8_0/components/schedule.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/ScheduleJava8View.java
  primefaces/src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java
Labels: enhancement

#11315 Fix #11314: Aria missing key default
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: enhancement

#11320 Fix #11318: Dialog return focus prevent scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11323 Fix #11318: 13.0.6 Dialog return focus prevent scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11326 Fix #11325: SelectOneMenu respect tabindex
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
Labels: :lady_beetle: defect

#11327 Fix #11325: 13.0.6 SelectOneMenu respect tabindex
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
Labels: :lady_beetle: defect

#11328 Fix #11318: Dialog return focus prevent scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11329 Fix #11318: 13.0.6 Dialog return focus prevent scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11321 Fix #11319: DatePicker do not use time for date comparison
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11324 Fix #11319: 13.0.6 DatePicker do not use time for date comparison
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#11333 Fix #11308: Dialog ESC in highest zIndex order
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11334 Fix #11308: 13.0.6 Dialog ESC in highest zIndex order
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11336 Fix #11332: incorrect DataTable rendering in case of scrollable=true …
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.frozen.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility, rtl

#11337 Fix #11332: 13.0.6 DataTable rendering in case of scrollable=true and…
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.frozen.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility, rtl

#11349 Fix #10251: 13.0.6 FileDownload allow disabling of `no-store`
  docs/13_0_0/components/filedownload.md
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadTagHandler.java
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: enhancement

#11347 Selenium: incorrect determination of baseURL for remote tests
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeSelenium.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/ConfigProvider.java
Labels: integration_test

#11351 Fix #11346: 13.0.6 Selenium: incorrect determination of baseURL for r…
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeSelenium.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/ConfigProvider.java
Labels: :lady_beetle: defect

#11348 Fix #11344: MenuBar/TieredMenu start/end facets
  docs/14_0_0/components/menubar.md
  docs/14_0_0/components/tieredmenu.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/menu/menubar.xhtml
  primefaces/src/main/java/org/primefaces/component/menu/AbstractMenu.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: enhancement

#11355 Fix #11354: Selenium: cannot set Firefox options through system settings
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java
Labels: :lady_beetle: defect

#11353 Fix #11350: MegaMenu rtl and start/end facets
  docs/14_0_0/components/megamenu.md
  docs/14_0_0/components/menubar.md
  docs/14_0_0/components/tieredmenu.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/menu/megaMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
Labels: enhancement

#11359 Fix #11354: 13.0.6 Selenium: cannot set Firefox options through syste…
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java
Labels: :lady_beetle: defect

#11357 #11352
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: :lady_beetle: defect

#11367 Fix #11358: 13.0.6 MenuItem invoke push/pop ComponentFromEL
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
Labels: :lady_beetle: defect

#11365 Fix #11362: Datatable reflow sort column names w/facet
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11366 Fix #11362: 13.0.6 Datatable reflow sort column names w/facet
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11368 Fix #11363: CSV Basic Showcase fix numeric
  primefaces-showcase/src/main/webapp/ui/csv/basic.xhtml
Labels: documentation
