Repository primefaces/primefaces, pull requests merged in 2024-05, with the labels that each got.

#11839 SONAR: fix issues
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
  primefaces/src/main/java/org/primefaces/application/DialogKeepFlashPhaseListener.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/BarcodeGenerator.java
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/export/CSVOptions.java
  primefaces/src/main/java/org/primefaces/component/export/ExcelOptions.java
  primefaces/src/main/java/org/primefaces/component/export/PDFOptions.java
  primefaces/src/main/java/org/primefaces/component/multiselectlistbox/MultiSelectListbox.java
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/java/org/primefaces/config/WebXmlParser.java
  primefaces/src/main/java/org/primefaces/util/BeanUtils.java
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
  primefaces/src/main/java/org/primefaces/util/FastStringWriter.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
Labels: enhancement

#11790 Fix #11096: Editor update Quill 2.0.0
  docs/15_0_0/core/thirdpartylibs.md
  primefaces-showcase/src/main/webapp/ui/input/textEditor.xhtml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/0-quill.min.js
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/0-texteditor.css
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/1-texteditor-theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/1-texteditor.js
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/texteditor.d.ts
  primefaces/src/main/type-definitions/blocklist.txt
  primefaces/src/main/type-definitions/package-lock.json
  primefaces/src/main/type-definitions/package.json
  primefaces/src/main/type-definitions/tsconfig.typedoc.json
Labels: dependencies, javascript

#11576 Fix #11575: Captcha add hCaptcha support
  docs/15_0_0/components/captcha.md
  docs/15_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/15_0_0.md
  primefaces-showcase/src/main/webapp/ui/misc/captcha.xhtml
  primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaBase.java
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/captcha/captcha.js
Labels: new feature

#11516 #11506 LazyDataModel: no need to count results if first==0 && lazyData.size < pageSize
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoComplete.java
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGrid.java
  primefaces/src/main/java/org/primefaces/component/datalist/DataList.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataView.java
Labels: :zap: performance

#11846 Fix #10909: Remove deprecated InputSwitch
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/input/inputSwitch.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitch.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchBase.java
  primefaces/src/main/java/org/primefaces/component/inputswitch/InputSwitchRenderer.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/inputswitch/inputswitch.css
  primefaces/src/main/resources/META-INF/resources/primefaces/inputswitch/inputswitch.js
Labels: breaking-change

#11845 Fix #11398: jQuery 4.0.0
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/1-jquery.fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js
Labels: dependencies, javascript

#11851 Fix #11806: Fileupload ignore invalid content type
  primefaces/src/main/java/org/primefaces/component/cache/UICacheRenderer.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
Labels: :lady_beetle: defect

#11856 Fix #11806: 14.0.1 Fileupload ignore invalid content type
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
Labels: :lady_beetle: defect

#11855 Fix #11731: Remove autocomplete="off" from hidden inputs
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: breaking-change

#11865 Fix #11864: CSS fixes from Sonar
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumber.java
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.css
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.css
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datascroller/datascroller.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
  primefaces/src/main/resources/META-INF/resources/primefaces/divider/divider.css
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/imagecompare/imagecompare.css
  primefaces/src/main/resources/META-INF/resources/primefaces/imageswitch/imageswitch.css
  primefaces/src/main/resources/META-INF/resources/primefaces/inplace/inplace.css
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/inputnumber.css
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.css
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.css
  primefaces/src/main/resources/META-INF/resources/primefaces/orderlist/orderlist.css
  primefaces/src/main/resources/META-INF/resources/primefaces/panel/panel.css
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.css
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/build/src/fullcalendar-vars.css
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.css
  primefaces/src/main/resources/META-INF/resources/primefaces/stack/stack.css
  primefaces/src/main/resources/META-INF/resources/primefaces/staticmessage/staticmessage.css
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.css
  primefaces/src/main/resources/META-INF/resources/primefaces/timeline/timeline.css
  primefaces/src/main/resources/META-INF/resources/primefaces/toggleswitch/toggleswitch.css
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.css
Labels: enhancement

#11624 Fix #9551 - Diagram: generate unique client ids per iteration
  primefaces-showcase/src/main/webapp/ui/data/diagram/editable.xhtml
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramBase.java
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramRenderer.java
  primefaces/src/main/java/org/primefaces/model/diagram/DefaultDiagramModel.java
Labels: enhancement, breaking-change

#11861 Fix #11860: 14.0.1 Dialog return focus ONLY if no other dialogs still open
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11862 Fix #11860: Dialog return focus ONLY if no other dialogs still open
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11871 Fix #11870: 13.0.10 Restore JDK8 compatibility
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11867 Fix #11789: FeedReader switch to new library
  docs/15_0_0/components/feedreader.md
  docs/15_0_0/gettingstarted/dependencies.md
  docs/15_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/15_0_0.md
  pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-integration-tests/src/main/webapp/feedreader/feedReader001.xhtml
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/webapp/ui/misc/feedReader.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/feedreader/FeedReaderBase.java
  primefaces/src/main/java/org/primefaces/component/feedreader/FeedReaderRenderer.java
  primefaces/src/main/java/org/primefaces/component/feedreader/RSSUtils.java
  primefaces/src/main/java/org/primefaces/model/feedreader/FeedItem.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/test/java/org/primefaces/component/feedreader/FeedReaderTest.java
  primefaces/src/test/java/org/primefaces/component/feedreader/RSSUtilsTest.java
  primefaces/src/test/resources/org/primefaces/feeds/XXE.xml
  primefaces/src/test/resources/org/primefaces/feeds/XXEbomb.xml
  primefaces/src/test/resources/org/primefaces/feeds/podcast.xml
Labels: new feature

#11876 Fix #11681: Style plain select,input elements
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.css
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: enhancement

#11868 Fix #11822: AutoComplete allow control over highlight matches
  docs/15_0_0/components/autocomplete.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteBase.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: enhancement

#11891 Fix #11889: BooleanCheckbox duplicates ui-state-disabled
  primefaces/src/main/java/org/primefaces/component/selectbooleancheckbox/SelectBooleanCheckboxRenderer.java
Labels: :lady_beetle: defect

#11892 Fix #11889: 14.0.1 BooleanCheckbox duplicates ui-state-disabled
  primefaces/src/main/java/org/primefaces/component/selectbooleancheckbox/SelectBooleanCheckboxRenderer.java
Labels: :lady_beetle: defect

#11903 Fix #11433 Showcase: move to JakartaEE (10)
  primefaces-showcase/src/main/webapp/WEB-INF/beans.xml
  primefaces-showcase/src/main/webapp/WEB-INF/web-development.xml
  primefaces-showcase/src/main/webapp/ui/data/carousel.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/facets.xhtml
  primefaces-showcase/src/main/webapp/ui/data/organigram.xhtml
Labels: documentation

#11899 Fix #11879: FileUpload (advanced): DragAndDrop not working, javascript error
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect

#11905 Fix #11879: 14.0.1 FileUpload (advanced): DragAndDrop not working, javascript error
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect

#11909 Fix #11434: Update docs to Jakarta
  README.md
  docs/14_0_0/gettingstarted/download.md
  docs/15_0_0/components/autocomplete.md
  docs/15_0_0/components/colorpicker.md
  docs/15_0_0/components/datatable.md
  docs/15_0_0/components/dialog.md
  docs/15_0_0/components/gmap.md
  docs/15_0_0/components/importenum.md
  docs/15_0_0/components/orderlist.md
  docs/15_0_0/components/outputlabel.md
  docs/15_0_0/components/overlaypanel.md
  docs/15_0_0/components/picklist.md
  docs/15_0_0/components/progressbar.md
  docs/15_0_0/components/sidebar.md
  docs/15_0_0/components/signature.md
  docs/15_0_0/components/terminal.md
  docs/15_0_0/components/timeline.md
  docs/15_0_0/components/tooltip.md
  docs/15_0_0/components/tree.md
  docs/15_0_0/components/wizard.md
  docs/15_0_0/core/beanvalidationtransformation.md
  docs/15_0_0/core/clientwindow.md
  docs/15_0_0/core/contentsecuritypolicy.md
  docs/15_0_0/core/csv.md
  docs/15_0_0/core/csvMessages.md
  docs/15_0_0/core/dialogframework.md
  docs/15_0_0/core/errorhandling.md
  docs/15_0_0/core/globalattributes.md
  docs/15_0_0/core/localization.md
  docs/15_0_0/core/multiviewstate.md
  docs/15_0_0/core/performance.md
  docs/15_0_0/gettingstarted/configuration.md
  docs/15_0_0/gettingstarted/dependencies.md
  docs/15_0_0/gettingstarted/download.md
  docs/15_0_0/gettingstarted/helloworld.md
Labels: documentation

#11901 Fix #11375: StaticMessage add success severity
  docs/15_0_0/components/staticmessage.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/message/staticMessage.xhtml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.css
Labels: enhancement

#11910 Moment.js 2.30.1 Timezone 0.5.45
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment-timezone-with-data.js
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment.js
Labels: dependencies, javascript

#11913 Fix #11875: Remove deprecation and restore SubTable demo
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/domain/Stats.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/domain/Team.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/SubTableView.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/subtable.xhtml
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: documentation

#11919 QuillJS 2.0.2
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/0-quill.min.js
Labels: dependencies, javascript

#11926 Fix #11925: SelectOneButton improve ARIA label
  primefaces/src/main/java/org/primefaces/component/selectonebutton/SelectOneButtonRenderer.java
Labels: accessibility

#11927 Fix #11925: 14.0.1 SelectOneButton improve ARIA label
  primefaces/src/main/java/org/primefaces/component/selectonebutton/SelectOneButtonRenderer.java
Labels: accessibility

#11935 #11933: CSV fix positive and negative
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/csv/BeanValidationView.java
  primefaces-showcase/src/main/webapp/ui/csv/bean.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
Labels: :lady_beetle: defect

#11937 Fix Drag and Drop docs
  docs/10_0_0/components/dragdrop.md
  docs/11_0_0/components/dragdrop.md
  docs/12_0_0/components/dragdrop.md
  docs/13_0_0/components/dragdrop.md
  docs/14_0_0/components/dragdrop.md
  docs/15_0_0/components/dragdrop.md
  docs/7_0/components/dragdrop.md
  docs/8_0/components/dragdrop.md
Labels: documentation

#11932 Fix #11931: CSV Bean validation translations
  docs/14_0_0/core/localization.md
  docs/15_0_0/core/localization.md
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bg.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ckb.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-da.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-he.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-kk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-km.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ms.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-th.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-vi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
Labels: :lady_beetle: defect

#11941 Fix #11940: InputMaskRenderer update Javadoc
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
Labels: documentation

#11942 Fix #11940: 14.0.1 InputMaskRenderer update Javadoc
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
Labels: documentation

#11924 Fix #11914: 14.0.1 Allow both URN and URI Taglib
  primefaces/pom.xml
Labels: enhancement

#11911 Fix #11885 - DataTable: Select/unselect all with selectionPageOnly="false" does not work properly
  primefaces-integration-tests/src/main/webapp/datatable/dataTable006.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable006Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11950 Fix #11885 14.0.1 DataTable: Select/unselect all with selectionPageOnly="false" does not work properly
  primefaces-integration-tests/src/main/webapp/datatable/dataTable006.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable006Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11944 Fix #11394: Treetable block checkbox until AJAX completion
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11948 Fix #11947: TabMenu orientation based corner styling
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenu.java
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java
Labels: :lady_beetle: defect

#11949 Fix #11947: 14.0.1 TabMenu orientation based corner styling
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenu.java
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java
Labels: :lady_beetle: defect

#11953 Fix #11394: 14.0.1 Treetable block checkbox until AJAX completion
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :lady_beetle: defect

#11955 Fix #11940: InputMask doc updates
  docs/13_0_0/components/inputmask.md
  docs/14_0_0/components/inputmask.md
  docs/15_0_0/components/inputmask.md
Labels: documentation

#11956 #11952: add expandIcon/collapseIcon attributes to RowToggler
  docs/15_0_0/components/rowtoggler.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/webapp/datatable/dataTable041_customIcon.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable041CustomIconTest.java
  primefaces/src/main/java/org/primefaces/component/rowtoggler/RowToggler.java
  primefaces/src/main/java/org/primefaces/component/rowtoggler/RowTogglerBase.java
  primefaces/src/main/java/org/primefaces/component/rowtoggler/RowTogglerRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: enhancement

#11939 Fix #11931/#11933: 14.0.1 CSV Bean validation fixes
  docs/14_0_0/core/localization.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/csv/BeanValidationView.java
  primefaces-showcase/src/main/webapp/ui/csv/bean.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bg.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ckb.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-da.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-he.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-kk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-km.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ms.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-th.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-vi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.bv.js
Labels: :lady_beetle: defect

#11946 Fix #11929: ConfirmDialog/Popup yes and no labels and classes
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/webapp/confirmdialog/confirmDialog001.xhtml
  primefaces-integration-tests/src/main/webapp/confirmpopup/confirmPopup001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmpopup/ConfirmPopup001Test.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePageTest.java
  primefaces-showcase/src/main/webapp/ui/overlay/confirmDialog.xhtml
  primefaces-showcase/src/main/webapp/ui/overlay/confirmPopup.xhtml
  primefaces/src/main/java/org/primefaces/behavior/confirm/ConfirmBehavior.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: new feature

#11960 Chart.js 4.4.3
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/chart/0-chartjs.min.js
Labels: dependencies

#11966 Fix #11900: 14.0.1 FileUpload (advanced): Multiple FileUpload - regressions when some files do not meet the limits
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.validators.js
Labels: :lady_beetle: defect

#11967 Fix #11958: 14.0.1 InputMask only strip slotChar if using optional mask
  primefaces/src/main/java/org/primefaces/component/inputmask/InputMaskRenderer.java
Labels: :lady_beetle: defect

#11964 #11962: confirmMessage facet
  docs/15_0_0/components/confirm.md
  docs/15_0_0/components/confirmdialog.md
  docs/15_0_0/components/confirmpopup.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/overlay/confirmDialog.xhtml
  primefaces/src/main/java/org/primefaces/behavior/confirm/ConfirmBehavior.java
Labels: new feature

#11943 Fix #11938: CSV switch date parser to moment.js
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/csv/Csv003.java
  primefaces-integration-tests/src/main/webapp/csv/csv003.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv003Test.java
  primefaces-showcase/src/main/webapp/ui/csv/bean.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/convert/DateTimeConverter.java
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment-java-formatter.js
  primefaces/src/main/resources/META-INF/resources/primefaces/moment/moment.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.converters.js
Labels: :lady_beetle: defect

#11970 Fix #11969: Facelets 4.0 Tag Library
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#11971 Fix #11969: 14.0.1 Facelets 4.0 Tag Library
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#11954 Fix #11951/#11928: DatePicker accessibility fixes
  docs/14_0_0/components/datepicker.md
  docs/15_0_0/components/datepicker.md
  primefaces-integration-tests/src/main/webapp/datepicker/datePicker012.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker011Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DatePicker.java
  primefaces-showcase/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: accessibility

#11961 Fix #11951/#11928: 14.0.1 DatePicker accessibility fixes
  docs/14_0_0/components/datepicker.md
  primefaces-integration-tests/src/main/webapp/datepicker/datePicker012.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker011Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DatePicker.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: accessibility

#11978 Fix#11814: 14.0.1 Support DefaultCommand for submit button outside but linked to) form
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/commandlink/CommandLinkRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect

#11976 Fix #11973: Confirm call Yes event on original button
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: enhancement

#11981 Fix #11929: Confirm add yes/no icon handling
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/webapp/confirmdialog/confirmDialog001.xhtml
  primefaces-integration-tests/src/main/webapp/confirmpopup/confirmPopup001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmpopup/ConfirmPopup001Test.java
  primefaces-showcase/src/main/webapp/ui/overlay/confirmDialog.xhtml
  primefaces-showcase/src/main/webapp/ui/overlay/confirmPopup.xhtml
  primefaces/src/main/java/org/primefaces/behavior/confirm/ConfirmBehavior.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: enhancement

#11975 Fix #11783: Datatable keyboard/screen reader support for cells
  docs/14_0_0/components/datatable.md
  docs/14_0_0/gettingstarted/whatsnew.md
  docs/15_0_0/components/datatable.md
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#11985 Fix #11783: 14.0.1 Datatable keyboard/screen reader support for cells
  docs/14_0_0/components/datatable.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#11991 Fix #11990: 14.0.1 FileValidator remove POI dependency
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
Labels: :lady_beetle: defect

#11992 Fix #11990: FileValidator remove POI dependency
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
Labels: :lady_beetle: defect

#12000 Fix #11989: Showcase dev temp switch to Mojarra
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
Labels: documentation

#12003 Docs: Add section for performance considerations with JPALazyDataModel's iterator
  docs/15_0_0/components/datatable.md
Labels: documentation

#12002 Fix #12001: Preserve order of constants
  primefaces/src/main/java/org/primefaces/component/importconstants/ConstantsHashMap.java
  primefaces/src/main/java/org/primefaces/component/importenum/EnumHashMap.java
Labels: :lady_beetle: defect

#12005 Fix #12001: 14.0.1 Preserve order of constants
  primefaces/src/main/java/org/primefaces/component/importconstants/ConstantsHashMap.java
  primefaces/src/main/java/org/primefaces/component/importenum/EnumHashMap.java
Labels: :lady_beetle: defect

#12006 SelectOneRadio remove deprecated showcase example
  primefaces-showcase/src/main/webapp/ui/input/oneRadio.xhtml
Labels: documentation

#11987 Fix #11918: 14.0.1 Datatable auto fit column like Excel
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/data/datatable/columnResize.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#11999 Fix #6561: Menu ARIA accessibility
  primefaces-showcase/src/main/webapp/ui/menu/tieredMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/MenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: accessibility

#12018 Fix #11553 - TabView/AccordionPanel: Introduce TabEvent#index
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanel.java
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabView.java
  primefaces/src/main/java/org/primefaces/component/tabview/TabViewRenderer.java
  primefaces/src/main/java/org/primefaces/event/TabChangeEvent.java
  primefaces/src/main/java/org/primefaces/event/TabCloseEvent.java
  primefaces/src/main/java/org/primefaces/event/TabEvent.java
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: enhancement

#12010 Fix #11988: 14.0.1 Datatable sticky must initialize and not wait for first scroll
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12011 Fix #11988: Datatable sticky must initialize and not wait for first scroll
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12016 Fix #6561: 14.0.1 Menu ARIA accessibility
  primefaces-showcase/src/main/webapp/ui/menu/tieredMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/MenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: accessibility

#12026 Fix #12024: 14.0.1 Rating respect required=true
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/rating/Rating001Test.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/RatingView.java
  primefaces-showcase/src/main/webapp/ui/input/rating.xhtml
  primefaces/src/main/java/org/primefaces/component/rating/Rating.java
  primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: :lady_beetle: defect

#12036 Fix #12035 - Columns: sortFunction fails
  primefaces/src/main/java/org/primefaces/component/columns/ColumnsHandler.java
Labels: :lady_beetle: defect

#12037 Fix #12034: BlockUI restore original position
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect

#12039 Fix #12034: 14.0.1 BlockUI restore original position
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
Labels: :lady_beetle: defect
