Repository primefaces/primefaces, pull requests merged in 2024-02, with the labels that each got.

#11370 Fix #11369: 13.0.6 SelectOneMenu allow dialog ESC
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11371 Fix 11369: SelectOneMenu allow dialog ESC
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11374 Fix #11360: FileUploadUtils code coverage and javadoc
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: :lady_beetle: defect

#11373 Fix #11372: Poll add onactivated/deactivated callbacks
  docs/14_0_0/components/poll.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/ajax/poll.xhtml
  primefaces/src/main/java/org/primefaces/component/poll/PollBase.java
  primefaces/src/main/java/org/primefaces/component/poll/PollRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/poll/poll.js
Labels: new feature

#11376 Fix #10902/#11045: DataTable livescroll/virtualscroll fix
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#11377 Fix #10902/#11045: 13.0.6 DataTable livescroll/virtualscroll fix
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#11379 Fix #11378: 13.0.6 Global tooltip fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#11380 Fix #11378: Global tooltip fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#11340 #11036: CSV: enable (command-)button only after client side validation passes (ui-state-csv-valid + ui-state-csv-invalid)
  docs/14_0_0/components/commandbutton.md
  docs/14_0_0/core/csv.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/csv/Csv001.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/csv/Csv002.java
  primefaces-integration-tests/src/main/webapp/csv/csv001.xhtml
  primefaces-integration-tests/src/main/webapp/csv/csv002.xhtml
  primefaces-integration-tests/src/main/webapp/resources/it/css/primeflex3.css
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv002Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/AbstractComponent.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/AbstractInputComponent.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/csv/ValidationView.java
  primefaces-showcase/src/main/webapp/ui/csv/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/csv/custom.xhtml
  primefaces-showcase/src/main/webapp/ui/csv/event.xhtml
  primefaces-showcase/src/main/webapp/ui/csv/immediate.xhtml
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonBase.java
  primefaces/src/main/java/org/primefaces/component/commandbutton/CommandButtonRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.highlighters.js
  primefaces/src/main/type-definitions/core.d.ts
Labels: enhancement

#11341 #11322 DatePicker: enabledDates - allows the user to select only dates from the provided list
  docs/14_0_0/components/datepicker.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarJava8View.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarView.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePicker.xhtml
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePicker.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.d.ts
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: enhancement

#11384 Fix #11383: 13.0.6 Restore ImmutableSavedState
  primefaces/src/main/java/org/primefaces/component/api/ImmutableSavedState.java
Labels: :lady_beetle: defect

#11387 Fix #11385: 13.0.6 OverlayPanel only remove if not inside target
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#11386 Fix #11385: OverlayPanel only remove if not inside target
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#11388 Fix #11381: Splitter accessibility
  docs/14_0_0/components/splitter.md
  docs/14_0_0/components/splitterpanel.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/panel/splitter.xhtml
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
  primefaces/src/main/java/org/primefaces/component/splitter/SplitterBase.java
  primefaces/src/main/java/org/primefaces/component/splitter/SplitterPanelBase.java
  primefaces/src/main/java/org/primefaces/component/splitter/SplitterRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
Labels: accessibility

#11390 Fix #11389: DataView hide buttons if only using one type
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
Labels: :lady_beetle: defect

#11391 Fix #11389: 13.0.6 DataView hide buttons if only using one type
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
Labels: :lady_beetle: defect

#11402 Fix #11401: calculate first row even if rowCount=0
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable044.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable044.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable044Test.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
Labels: :lady_beetle: defect

#11405 Fix #11401: 13.0.6 calculate first row even if rowCount=0
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
Labels: :lady_beetle: defect

#11411 Fix #11407: Chips allow comma as separator again
  primefaces/src/main/java/org/primefaces/component/chips/ChipsRenderer.java
Labels: :lady_beetle: defect

#11412 Fix #11407: 13.0.6 Chips allow comma as separator again
  primefaces/src/main/java/org/primefaces/component/chips/ChipsRenderer.java
Labels: :lady_beetle: defect

#11415 Revert #11385: OverlayPanel revert remove on target logic
  primefaces-integration-tests/src/main/webapp/overlaypanel/overlayPanel002.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#11416 ProgressBar: add severities support
  docs/14_0_0/components/progressbar.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/misc/progressBar.xhtml
  primefaces/src/main/java/org/primefaces/component/progressbar/ProgressBar.java
  primefaces/src/main/java/org/primefaces/component/progressbar/ProgressBarBase.java
  primefaces/src/main/java/org/primefaces/component/progressbar/ProgressBarRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: enhancement

#11420 Fix #11419: SearchExpressionUtils defensive NPE check
  primefaces/src/main/java/org/primefaces/expression/SearchExpressionUtils.java
Labels: :lady_beetle: defect

#11430 Fix #11429: Message tooltip fix
  primefaces/src/main/resources/META-INF/resources/primefaces/message/message.js
Labels: :lady_beetle: defect

#11428 Fix #11426: 13.0.6 Spring Security CSRF
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: :lady_beetle: defect

#11437 Fix #11436: MeterGauge update migration guide
  docs/migrationguide/13_0_0.md
Labels: documentation

#11435 Fix #11424: DatePicker add hideOnRangeSelection
  docs/14_0_0/components/datepicker.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#11441 Fix #11440: Datatable sticky delay z-index until show
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11443 Fix #11440: 13.0.6 Datatable sticky delay z-index until show
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11451 Fix #11449: CSV add InputNumber example
  primefaces-showcase/src/main/webapp/ui/csv/basic.xhtml
Labels: documentation

#11454 Fix #9551: Diagram not generating a iterator / uniqueId
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramRenderer.java
Labels: enhancement

#11455 ARIA Fastpass fixes
  primefaces-showcase/src/main/webapp/WEB-INF/footer.xhtml
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
  primefaces-showcase/src/main/webapp/WEB-INF/topbar.xhtml
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#11456 Fix #9551: 13.0.6 Diagram not generating a iterator / uniqueId
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramRenderer.java
Labels: :lady_beetle: defect

#11458 Fix LazyCustomerDataModel#load impl
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/datatable/LazyCustomerDataModel.java
Labels: documentation

#11457 Fix #11452 - DataTable: LazyDataModel.load gets invoked multiple time…
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/model/LazyDataModel.java
Labels: :zap: performance

#11462 Fix #11459: Tree restore DnD after filtering
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: :lady_beetle: defect

#11461 Fix #11452 - 13.0.6 DataTable: LazyDataModel.load gets invoked multip…
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/model/LazyDataModel.java
Labels: :zap: performance

#11471 Fix #11460: Tree add dropMode attribute
  docs/13_0_0/components/tree.md
  docs/14_0_0/components/tree.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/tree/TreeBase.java
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: enhancement

#11479 Revert "Fix #9551: Diagram not generating a iterator / uniqueId
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramRenderer.java
Labels: :lady_beetle: defect

#11485 Fix #11484: Tooltip for fast mouse movement
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#11490 Add Kazakh Locale
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-kk.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: enhancement

#11494 Fix #11491: Datatable header scrolling
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.frozen.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#11501 Fix #11498: 13.0.7 Showcase favicon fix
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
Labels: documentation

#11499 Libre 1.4.1 for Java 11
  docs/14_0_0/gettingstarted/dependencies.md
  pom.xml
Labels: dependencies

#11509 Fix #11508: Do not render empty style, styleClass
  primefaces-showcase/src/main/webapp/ui/ajax/basic.xhtml
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java
Labels: :zap: performance

#11512 Fix #11483: 13.0.7 Showcase Mojarra NPE check
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/ajax/BasicView.java
Labels: documentation

#11510 Fix #11505: Fileupload refactor messageTemplate
  docs/14_0_0/components/fileupload.md
  docs/migrationguide/14_0_0.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/fileupload/FileUpload005Test.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
Labels: documentation

#11515 Fix #11513: Tree wrong dnd index for sibling going down
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: :lady_beetle: defect

#11514 Fix #11513: 13.0.7 Tree wrong dnd index for sibling going down
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: :lady_beetle: defect

#11517 Fix #11381: Improve Splitter accessibility
  primefaces/src/main/java/org/primefaces/component/splitter/SplitterRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
Labels: accessibility

#11524 Fix #11523: Fileupload ARIA progress bar
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: accessibility

#11525 Fix #11523: 13.0.7 Fileupload ARIA progress bar
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: accessibility

#11531 Fix #11508: 13.0.7 Do not render empty style, styleClass
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/panelgrid/PanelGridRenderer.java
Labels: :zap: performance

#11529 Fix #11521: Datatable first value fix
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/CustomerLazyDataModelNoCountImpl.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable045.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable045.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable045Test.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
Labels: :lady_beetle: defect

#11530 Fix #11521: 13.0.7 Datatable first value fix
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/CustomerLazyDataModelNoCountImpl.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable045.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable045.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable045Test.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
Labels: :lady_beetle: defect
