Repository primefaces/primefaces, pull requests merged in 2024-11, with the labels that each got.

#12820 #12815 IntegrationTests: SCREENSHOT_DIRECTORY not set when running on local
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/ConfigProvider.java
Labels: integration_test

#12827 Fix #12824: TreeTable CSV export missing headers
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableCSVExporter.java
Labels: :lady_beetle: defect

#12828 Fix #12824: 14.0.7 TreeTable CSV export missing headers
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableCSVExporter.java
Labels: :lady_beetle: defect

#12821 Fix #12819: Datatable remove legacy CSS border-collapse
  docs/migrationguide/14_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12822 Fix #12819: 14.0.7 Datatable remove legacy CSS border-collapse
  docs/migrationguide/14_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12835 Fix #12834: 14.0.7 SelectOneMenu handle paste and drop on filter
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#12836 Fix #12834: SelectOneMenu handle paste and drop on filter
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#12826 Fix #12825: Make Dashboard scope configurable
  docs/15_0_0/components/dashboard.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/dashboard/DashboardBase.java
  primefaces/src/main/java/org/primefaces/component/dashboard/DashboardRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/dashboard/dashboard.js
Labels: enhancement

#12749 Fix #12743 Do not render empty command containers (Menubar, Toolbar, MenuButton,...) [Draft]
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/dock/DockRenderer.java
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/MenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/panelmenu/PanelMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/slidemenu/SlideMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDialRenderer.java
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/stack/StackRenderer.java
  primefaces/src/main/java/org/primefaces/component/steps/StepsRenderer.java
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/toolbar/ToolbarRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/MenuItemAwareRenderer.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: enhancement, pending-review

#12842 Fix #12841: Delayed Hover Effect for TieredMenus
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#12843 Fix #12841: 14.0.7 TieredMenu delayed Hover Effect
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#12850 Fix #12845: 14.0.7 Tab menu chrome scrollbar
  primefaces/src/main/resources/META-INF/resources/primefaces-arya/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-amber/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-green/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-luna-pink/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-colored/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-dark/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-nova-light/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-vela/theme.css
Labels: :lady_beetle: defect

#12848 Fix #12844: SelectCheckBoxMenu allow empty label
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectChecboxMenu002.java
  primefaces-integration-tests/src/main/webapp/selectcheckboxmenu/selectCheckboxMenu002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu002Test.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#12849 Fix #12844: 14.0.7 SelectCheckBoxMenu allow empty label
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectChecboxMenu002.java
  primefaces-integration-tests/src/main/webapp/selectcheckboxmenu/selectCheckboxMenu002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu002Test.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#12858 Fixes #12856 - Timeline: Adding events dynamically not working anymore in when passing a search expression to the TimelineUpdater
  primefaces/src/main/java/org/primefaces/component/timeline/DefaultTimelineUpdater.java
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineListener.java
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineUpdater.java
Labels: :lady_beetle: defect

#12859 Fix #12856: 14.0.7 Timeline: Adding events dynamically not working
  primefaces/src/main/java/org/primefaces/component/timeline/DefaultTimelineUpdater.java
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineListener.java
  primefaces/src/main/java/org/primefaces/component/timeline/TimelineUpdater.java
Labels: :lady_beetle: defect

#12871 Fix #12868: 14.0.7 TreeTable field short notation
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/data/treetable/field.xhtml
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#12863 Fix #12855: HeadRenderer check for already loaded resource
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
Labels: :lady_beetle: defect

#12874 Fix #12855: 14.0.7 HeadRenderer check for already loaded resource
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
Labels: :lady_beetle: defect

#12877 Fix #12864: 14.0.7JPALazyDataModel: add possibilty to inject own/custom FilterMeta
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: enhancement

#12878 Fix #12484: Picklist allow custom labels per component
  docs/15_0_0/components/picklist.md
  primefaces-showcase/src/main/webapp/ui/data/pickList.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectbooleanbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
  primefaces/src/main/resources/META-INF/resources/primefaces/panel/panel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
  primefaces/src/main/resources/META-INF/resources/primefaces/rating/rating.js
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/1-widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
  primefaces/src/main/resources/META-INF/resources/primefaces/toggleswitch/toggleswitch.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: enhancement

#12873 Fix #12870: OverlayPanel allow showEvent 'none'
  docs/15_0_0/components/overlaypanel.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: enhancement

#12879 Fix #12008: CascadeSelect do not register scrollhandler for large lists
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.cascadeselect.js
Labels: :lady_beetle: defect

#12880 Fix #12008: 14.0.7 CascadeSelect do not register scrollhandler for large lists
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.cascadeselect.js
Labels: :lady_beetle: defect

#12882 Fix #12870: 14.0.7 OverlayPanel allow showEvent 'none'
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: enhancement

#12888 Fix #12887: InputText missing client behaviors
  primefaces/src/main/java/org/primefaces/component/inputtext/InputTextRenderer.java
Labels: :lady_beetle: defect

#12893 Fix #12891: Revert datatable CSS border-collapse
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12892 Fix #12891: 14.0.8 Revert datatable CSS border-collapse
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12894 Fix #12819: Datatable proper CSS for outline cells
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12895 Fix #12819: 14.0.8 Datatable proper CSS for outline cells
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12903 Fix #12887: 14.0.8 Widget callBehavior fall back to DOM `on` if no behaviors
  primefaces/src/main/java/org/primefaces/component/inputtext/InputTextRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
Labels: :lady_beetle: defect

#12902 Fix #12862 FileUpload: handle invalid filename like url-encoded characters (%20) as validation error
  docs/15_0_0/core/localization.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/model/file/AbstractUploadedFile.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_hr.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: :lady_beetle: defect

#12897 Fix #12896: Datatable/TreeTable add title to header
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#12898 Fix #12896: 14.0.8 Datatable/TreeTable add title to header
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#12905 Fix #12904: MessageFactory pass in FacesContext
  primefaces/src/main/java/org/primefaces/component/api/UICalendar.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/api/UITree.java
  primefaces/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java
  primefaces/src/main/java/org/primefaces/component/captcha/Captcha.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/password/Password.java
  primefaces/src/main/java/org/primefaces/component/picklist/PickList.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenu.java
  primefaces/src/main/java/org/primefaces/component/slider/Slider.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableBase.java
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/java/org/primefaces/util/MessageFactory.java
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
  primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonScanner.java
  primefaces/src/main/java/org/primefaces/virusscan/impl/VirusTotalReportScanner.java
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: :zap: performance

#12910 Fix ##12908: Datatable scrollable height must be 0px
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12911 Fix ##12908: 14.0.8 Datatable scrollable height must be 0px
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12914 FileUploadUtilsTest always force to US English
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: integration_test

#12916 Fixes #12901 - CSP: "Missing CSP nonce" on error page
  primefaces/src/main/java/org/primefaces/csp/CspPhaseListener.java
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: :lady_beetle: defect

#12922 Add Bosnian locale
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bs.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: enhancement

#12218 Sonar JS fixes for Core
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.clientwindow.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.expressions.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.resources.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
Labels: pending-review

#12930 Fix #12929/#12927: Tree ARIA issues
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.horizontal.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: accessibility

#12931 Fix #12929/#12927: 14.0.8 Tree ARIA issues
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.horizontal.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: accessibility

#12936 Fix #12934: 14.0.8 FileUpload fix warning message
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
Labels: :lady_beetle: defect

#12937 Fix #12934: FileUpload fix warning message
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
Labels: :lady_beetle: defect

#12935 Fix #12933: FileUpload rename directoryPath and fix path check
  primefaces/src/main/java/org/primefaces/model/file/AbstractUploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFile.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFileWrapper.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFiles.java
  primefaces/src/main/java/org/primefaces/model/file/UploadedFilesWrapper.java
Labels: :lady_beetle: defect

#12939 #12938 PrimeFaces.nextZindex
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.cascadeselect.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleria.js
  primefaces/src/main/resources/META-INF/resources/primefaces/growl/growl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/keyboard/1-keyboard.js
  primefaces/src/main/resources/META-INF/resources/primefaces/log/log.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.slidemenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/scrolltop/scrolltop.js
Labels: javascript

#12928 Fix #11863: Sonar JS fixes part 2
  primefaces/src/main/resources/META-INF/resources/primefaces/carousel/carousel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/clock/clock.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dashboard/dashboard.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datascroller/datascroller.js
  primefaces/src/main/resources/META-INF/resources/primefaces/diagram/1-diagram.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.multiselectlistbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.password.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanybutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanycheckbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectmanymenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonebutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectoneradio.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/gmap/gmap.js
  primefaces/src/main/resources/META-INF/resources/primefaces/keyboard/1-keyboard.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.contextmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/orderlist/orderlist.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/progressbar/progressbar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/slider/slider.js
  primefaces/src/main/resources/META-INF/resources/primefaces/speeddial/speeddial.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: javascript

#12943 Update Arabic from PrimeLocale
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
Labels: documentation

#12947 Fix #12941: Update 14.0.0 docs in main
  docs/14_0_0/components/fileupload.md
  docs/15_0_0/components/fileupload.md
  docs/migrationguide/14_0_0.md
  docs/migrationguide/15_0_0.md
Labels: documentation

#12823 Refactor Barcode to use a single modern dependency
  docs/15_0_0/components/barcode.md
  docs/15_0_0/gettingstarted/dependencies.md
  docs/migrationguide/15_0_0.md
  pom.xml
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/multimedia/barcode.xhtml
  primefaces-showcase/src/main/webapp/ui/multimedia/qrcode.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/application/resource/PrimeResourceHandler.java
  primefaces/src/main/java/org/primefaces/application/resource/QRCodeHandler.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/BarcodeGenerator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/BarcodeHandler.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/CodabarGenerator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/Code128Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/Code39Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/DataMatrixGenerator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/EAN13Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/EAN8Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/Int2of5Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/PDF417Generator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/PostnetGenerator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/UPCAGenerator.java
  primefaces/src/main/java/org/primefaces/application/resource/barcode/UPCEGenerator.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeBase.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeHandler.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: breaking-change

#12954 Fix #12953: SelectOneRadio proper identification by label
  primefaces-integration-tests/src/main/webapp/selectoneradio/selectOneRadio001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio001Test.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioBase.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility, integration_test

#12955 Fix #12953: 14.0.9 SelectOneRadio proper identification by label
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-integration-tests/src/main/webapp/selectoneradio/selectOneRadio001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio001Test.java
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadio.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioBase.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility

#12959 Fix #12958 : 14.0.9 ColorPicker popup not working in Sidebar
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
Labels: :lady_beetle: defect

#12960 Fix #12958 : ColorPicker popup not working in Sidebar
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
Labels: :lady_beetle: defect

#12965 Fix #12812: CSP update Policy Provided docs
  docs/12_0_0/core/contentsecuritypolicy.md
  docs/13_0_0/core/contentsecuritypolicy.md
  docs/14_0_0/core/contentsecuritypolicy.md
  docs/15_0_0/core/contentsecuritypolicy.md
Labels: documentation

#12964 Fixes #12942 - Advanced FileUpload: highlight when drag/drop files
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/layout.css
  primefaces-themes/theme-base/_components.scss
  primefaces-themes/theme-base/_keyframes.scss
  primefaces-themes/theme-base/components/file/_fileupload.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-mytheme/variables/_general.scss
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/fileupload.css
Labels: enhancement

#12971 Fix #12949: HeadRenderer use resources not links
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/core/head/CoreHead003.java
  primefaces-integration-tests/src/main/webapp/WEB-INF/web.xml
  primefaces-integration-tests/src/main/webapp/core/head/head001.xhtml
  primefaces-integration-tests/src/main/webapp/core/head/head002.xhtml
  primefaces-integration-tests/src/main/webapp/core/head/head003.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead003Test.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporter.java
  primefaces/src/main/java/org/primefaces/component/filedownload/FileDownloadActionListener.java
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
Labels: :zap: performance

#12972 QuillJS 2.0.3
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/0-quill.min.js
Labels: dependencies, javascript
