Repository primefaces/primefaces, pull requests merged in 2024-04, with the labels that each got.

#11699 Fix #11698: InputMask destroy
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/1-inputmask.js
Labels: :zap: performance

#11715 Fix #11714: AJAX update containing resources check for duplicates
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: :zap: performance

#11704 Fix #11703: FileUpload clean up on destroy
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :zap: performance

#11706 Fix #11705: IdleMonitor destroy widget properly
  primefaces/src/main/java/org/primefaces/component/idlemonitor/IdleMonitorRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js
Labels: :zap: performance

#11710 Fix #11709: Menubar/TieredMenu destroy to release DOM elements
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :zap: performance

#11718 Fix #11717: Picklist focus on mousedown
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: :lady_beetle: defect

#11719 Fix #11717: 13.0.8 Picklist focus on mousedown
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: :lady_beetle: defect

#11686 Fix #11685 - Datatable: action not called if columns is rendered conditionnally
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#11721 Integration test #11685
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable046.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable046.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable046Test.java
Labels: integration_test

#11722 13.0.8 IdleMonitor/FileUpload/DatePicker/Calendar/Menu/Mask client cleanup
  primefaces/src/main/java/org/primefaces/component/idlemonitor/IdleMonitorRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/1-inputmask.js
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.megamenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.panelmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :zap: performance

#11695 Fix #11694: AJAX event handler leak
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
Labels: :zap: performance

#11728 Fix #11727: ExcelStyleManager NPE guards
  primefaces/src/main/java/org/primefaces/util/ExcelStylesManager.java
Labels: :lady_beetle: defect

#11730 Fix #11702: 13.0.8 Detached DOM memory leaks on AJAX update
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
Labels: :zap: performance

#11733 Showcase: Update Flags CSS
  primefaces-showcase/src/main/webapp/resources/showcase/css/flags/flags.css
  primefaces-showcase/src/main/webapp/resources/showcase/css/flags/flags_responsive.png
Labels: documentation

#11738 Fix #11712/#11723: 13.0.8 Detach document and window events
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/1-colorpicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datascroller/datascroller.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/lifecycle/lifecycle.js
  primefaces/src/main/resources/META-INF/resources/primefaces/organigram/organigram.js
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
  primefaces/src/main/resources/META-INF/resources/primefaces/speeddial/speeddial.js
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
  primefaces/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js
  primefaces/src/main/resources/META-INF/resources/primefaces/sticky/sticky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: :zap: performance

#11740 Fix #11739: DragDrop/Resizable add destroy listeners
  primefaces/src/main/resources/META-INF/resources/primefaces/dragdrop/dragdrop.js
  primefaces/src/main/resources/META-INF/resources/primefaces/resizable/resizable.js
Labels: :zap: performance

#11741 Fix #11739: 13.0.8 DragDrop/Resizable add destroy listeners
  primefaces/src/main/resources/META-INF/resources/primefaces/dragdrop/dragdrop.js
  primefaces/src/main/resources/META-INF/resources/primefaces/resizable/resizable.js
Labels: :zap: performance

#11747 Coloris 0.24.0
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/colorpicker/0-coloris.js
  primefaces/src/main/type-definitions/package-lock.json
  primefaces/src/main/type-definitions/package.json
Labels: dependencies, javascript

#11754 JPALazyDataModel: remove constructors in favor of builder pattern
  docs/migrationguide/14_0_0.md
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: breaking-change

#11755 ChartUtils deprecated
  primefaces/src/main/java/org/primefaces/util/ChartUtils.java
Labels: breaking-change

#11756 Move IOBiConsumer into org.primefaces.util
  primefaces/src/main/java/org/primefaces/component/badge/BadgeRenderer.java
  primefaces/src/main/java/org/primefaces/util/IOBiConsumer.java
Labels: breaking-change

#11753 Fix #11748 - DataExporter: deprecate ExporterUtils
  docs/13_0_0/components/dataexporter.md
  docs/14_0_0/components/dataexporter.md
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/dataexporter/TextExporter.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/ShowcaseSystemEventListener.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/dataexporter/TextExporter.java
  primefaces-showcase/src/main/webapp/WEB-INF/faces-config.xml
  primefaces-showcase/src/main/webapp/ui/data/dataexporter/basic.xhtml
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableXMLExporter.java
  primefaces/src/main/java/org/primefaces/component/export/DataExporters.java
  primefaces/src/main/java/org/primefaces/component/export/ExporterUtils.java
  primefaces/src/main/java/org/primefaces/component/export/TableExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableExcelExporter.java
  primefaces/src/main/java/org/primefaces/component/treetable/export/TreeTableXMLExporter.java
Labels: breaking-change

#11746 ExceptionHandler: null check session, use ClientWindow whenever possible
  primefaces/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java
  primefaces/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandlerELResolver.java
Labels: enhancement

#11757 Fix #11737 ExceptionHandler: 13.0.9 null check session, use ClientWindow whenever possible
  primefaces/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java
  primefaces/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandlerELResolver.java
Labels: enhancement

#11760 Fix #10946: 13.0.9 CSP add noonce only to JSF forms
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
Labels: enhancement

#11761 Fix #11759: InterceptingResolver add convertToType
  primefaces/src/main/java/org/primefaces/el/InterceptingResolver.java
Labels: :lady_beetle: defect

#11769 Showcase fixes
  primefaces-showcase/src/main/java/org/primefaces/showcase/convert/CountryConverter.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/convert/OrderConverter.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/primeflex/ElevationView.java
  primefaces-showcase/src/main/webapp/WEB-INF/footer.xhtml
Labels: documentation

#11770 Showcase: Add toggleSelect example to CheckBoxMenu
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CheckboxView.java
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
Labels: documentation

#11775 Fix #11774: Cookies as SameSite=None in non-secure mode
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
Labels: enhancement

#11778 Fix #11777: JS getLocaleSettings defensive checks
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#11779 Fix #11102 - add arial-label to JumpToPage components (branch 13.x)
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/paginator/JumpToPageDropdownRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/JumpToPageInputRenderer.java
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_fr.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: enhancement

#11781 Fix #11407: Chips pasting issues
  primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js
Labels: :lady_beetle: defect

#11782 Fix #11407: 13.0.9 Chips pasting issues
  primefaces/src/main/resources/META-INF/resources/primefaces/chips/chips.js
Labels: :lady_beetle: defect

#11784 Fix #11780: Fix resource handling to allow raw JS code
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: :lady_beetle: defect

#11786 Fix #11780: 13.0.9 Fix resource handling to allow raw JS code
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: :lady_beetle: defect

#11792 Fix #11791: InputNumber allow Number.class to be decimal
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  primefaces/src/test/java/org/primefaces/component/inputnumber/InputNumberTest.java
Labels: :lady_beetle: defect

#11793 Fix #11791: 13.0.9 InputNumber allow Number.class to be decimal
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  primefaces/src/test/java/org/primefaces/component/inputnumber/InputNumberTest.java
Labels: :lady_beetle: defect

#11795 Touch Punch 1.1.5
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.touch-punch.js
Labels: dependencies

#11798 Dialog showcase example for focus
  primefaces-showcase/src/main/webapp/ui/overlay/dialog.xhtml
Labels: documentation

#11800 Fix #11799 - DataTable: Method is called multiple times inside of p:columns
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#11803 Fix #11799 - 13.0.9 DataTable: Method is called multiple times inside…
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: :lady_beetle: defect

#11811 Fix #11809: SelectOneMenu keyup only check printable keys
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11810 Fix #11809: 13.0.9 SelectOneMenu keyup only check printable keys
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#11821 Fix #11817: Toggleswitch move to components css/js
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitch.java
Labels: enhancement

#11819 Fix #11818: Dialog focus from link
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11820 Fix #11818: 13.0.9 Dialog focus from link
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#11816 Fix #11806: FileUpload switch error to dev warning
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
Labels: enhancement

#11828 Fix #11827: jQuery UI 1.13.3
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.css
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js
Labels: :lady_beetle: defect

#11825 Fix #11824: AjaxStatus always hide in oncomplete
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus001.java
  primefaces-integration-tests/src/main/webapp/ajaxstatus/ajaxStatus001.xhtml
  primefaces-integration-tests/src/main/webapp/ajaxstatus/ajaxStatus002.xhtml
  primefaces-integration-tests/src/main/webapp/ajaxstatus/ajaxStatus003.xhtml
  primefaces-integration-tests/src/main/webapp/ajaxstatus/ajaxStatus004.xhtml
  primefaces-integration-tests/src/main/webapp/ajaxstatus/ajaxStatus005.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus003Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus004Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/ajaxstatus/AjaxStatus005Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
Labels: :lady_beetle: defect

#11832 Fix #11830: Spinner prevent value outside min/max range
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerBase.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
Labels: :lady_beetle: defect

#11833 Fix #11830: 13.0.9 Spinner prevent value outside min/max range
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerBase.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
Labels: :lady_beetle: defect

#11834 Fix #11831: AutoComplete add showEmptyMessage
  docs/14_0_0/components/autocomplete.md
  docs/14_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteBase.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/resources/META-INF/primefaces-p.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: enhancement
