Repository primefaces/primefaces, pull requests merged in 2024-12, with the labels that each got.

#12975 Fix #12963: ProgressBar render label inside value
  docs/migrationguide/15_0_0.md
  primefaces-themes/theme-base/components/misc/_progressbar.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/java/org/primefaces/component/progressbar/ProgressBarRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/progressbar/progressbar.js
Labels: breaking-change

#12974 Fix #12969: DatePicker allow showLongMonthNames
  docs/15_0_0/components/datepicker.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#12984 Fixes #12966 - Advanced FileUpload: add empty facet
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/file/upload/advanced.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/auto.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/basicAuto.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/chunked.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/dnd.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/multiple.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/simple.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/single.xhtml
  primefaces-showcase/src/main/webapp/ui/file/upload/tooltips.xhtml
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUpload.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: enhancement

#12986 Fix #12985: DatePicker prevent ESC from bubbling up when panel open
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: accessibility

#12987 Fix #12985: 14.0.9 DatePicker prevent ESC from bubbling up when panel open
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: accessibility

#12997 Fix #12996: 14.0.9 SelectCheckboxMenu remove multipleLabel from taglib
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12998 Fix #12996: SelectCheckboxMenu remove multipleLabel from taglib
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12992 Fix #12989: Cell Editor with SelectOne blocking tab control
  primefaces-showcase/src/main/webapp/ui/data/datatable/edit.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12991 Fix #12989: 14.0.9 Cell Editor with SelectOne blocking tab control
  primefaces-showcase/src/main/webapp/ui/data/datatable/edit.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12994 Fix #12988: InputNumber AJAX input event
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#12995 Fix #12988: 14.0.9 InputNumber AJAX input event
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#13008 Showcase fix speed dial example for /ui/file/upload/simple
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/button/SpeedDialView.java
  primefaces-showcase/src/main/webapp/ui/button/speedDial.xhtml
Labels: documentation

#13007 #12966 FileUpload empty facet documentation
  docs/15_0_0/components/fileupload.md
  docs/15_0_0/gettingstarted/whatsnew.md
Labels: documentation

#13006 Fix #13005: DataView NPE in encodeHeader
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewRenderer.java
Labels: :lady_beetle: defect

#13004 Fix #13003: Themes add sources.jar
  primefaces-themes/pom.xml
  primefaces-themes/src/main/assembly/source-jar.xml
Labels: enhancement

#13017 HeadRenderer fix Firefox IT failing
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/head/CoreHead003Test.java
Labels: integration_test

#13022 #13016 - Column: component not pushed to EL
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
Labels: enhancement

#13019 Fix #13018: EqualsFilterConstraint handle enum/string
  primefaces/src/main/java/org/primefaces/model/filter/EqualsFilterConstraint.java
  primefaces/src/test/java/org/primefaces/model/filter/EqualsFilterConstraintTest.java
Labels: :lady_beetle: defect

#13020 Fix #13018: 14.0.9 EqualsFilterConstraint handle enum/string
  primefaces/src/main/java/org/primefaces/model/filter/EqualsFilterConstraint.java
  primefaces/src/test/java/org/primefaces/model/filter/EqualsFilterConstraintTest.java
Labels: :lady_beetle: defect

#13024 Fixes #12743, Fixes 13021; make encodePlaceholder impl per default
  primefaces/src/main/java/org/primefaces/component/breadcrumb/BreadCrumbRenderer.java
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/dock/DockRenderer.java
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/BaseMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menu/MenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubar/MenubarRenderer.java
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonRenderer.java
  primefaces/src/main/java/org/primefaces/component/panelmenu/PanelMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/slidemenu/SlideMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/speeddial/SpeedDialRenderer.java
  primefaces/src/main/java/org/primefaces/component/stack/StackRenderer.java
  primefaces/src/main/java/org/primefaces/component/steps/StepsRenderer.java
  primefaces/src/main/java/org/primefaces/component/tabmenu/TabMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/tieredmenu/TieredMenuRenderer.java
Labels: enhancement

#13025 Fix #13016 14.0.9 Column: component not pushed to EL
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
Labels: :lady_beetle: defect

#13027 Fix #13026: 14.0.9 Crud showcase fix
  primefaces-showcase/src/main/java/org/primefaces/showcase/domain/Product.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
Labels: documentation

#13028 Fix #13026: Crud showcase fix
  primefaces-showcase/src/main/java/org/primefaces/showcase/domain/Product.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/contextMenu.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/expansion.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/selection.xhtml
Labels: documentation

#13030 Fix #13029: 14.0.9 ColumnToggler cast to UITable not DataTable
  primefaces/src/main/java/org/primefaces/component/columntoggler/ColumnToggler.java
Labels: :lady_beetle: defect

#13031 Fix #13029: ColumnToggler cast to UITable not DataTable
  primefaces/src/main/java/org/primefaces/component/columntoggler/ColumnToggler.java
Labels: :lady_beetle: defect

#13036 Showcase CRUD fixes
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/_demo.scss
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/layout.css
Labels: documentation

#13037 14.0.9 Showcase CRUD fixes
  primefaces-showcase/src/main/webapp/resources/showcase/css/layout/_demo.scss
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
Labels: documentation

#13040 Autocomplete docs add placeholder
  docs/11_0_0/components/autocomplete.md
  docs/12_0_0/components/autocomplete.md
  docs/13_0_0/components/autocomplete.md
  docs/14_0_0/components/autocomplete.md
  docs/15_0_0/components/autocomplete.md
Labels: documentation

#13051 Fix #13042: ColumnToggler keyboard accessibility improvements
  primefaces/src/main/resources/META-INF/resources/primefaces/columntoggler/columntoggler.js
Labels: accessibility

#13052 Fix #13049: 14.0.9 Fix log format for single quote
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
Labels: :lady_beetle: defect

#13053 Fix #13049: Fix log format for single quote
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
Labels: :lady_beetle: defect

#13054 Fix #13047: SelectOneRadio fix screenreader announcement
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility

#13055 Fix #13047: 14.0.10 SelectOneRadio fix screenreader announcement
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility

#12881 Fix #12853: Datatable filter toggler via js
  docs/15_0_0/components/datatable.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: new feature

#13069 Fixes #13066, #13067 - removed unused media code, improve streamed content support
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/multimedia/MediaView.java
  primefaces/src/main/java/org/primefaces/component/media/MediaRenderer.java
  primefaces/src/main/java/org/primefaces/component/media/player/MediaPlayer.java
  primefaces/src/main/java/org/primefaces/component/media/player/PDFPlayer.java
  primefaces/src/main/java/org/primefaces/component/media/player/QuickTimePlayer.java
  primefaces/src/main/java/org/primefaces/component/media/player/RealPlayer.java
  primefaces/src/main/java/org/primefaces/component/media/player/WindowsPlayer.java
Labels: enhancement

#13065 Fix #13012/#12754/#12837: 14.0.10 DatePicker mask with blur
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#13072 Fixes #13071
  primefaces/src/main/java/org/primefaces/renderkit/HeadRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: enhancement

#13077 Fixes #13073
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/ajaxexceptionhandler/AjaxExceptionHandlerBase.java
  primefaces/src/main/java/org/primefaces/component/ajaxexceptionhandler/AjaxExceptionHandlerRenderer.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxexceptionhandler/ajaxexceptionhandler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: enhancement

#13088 Fix #13085: 14.0.10 DefaultCommand prevent NPE if target does not exist
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect

#13089 Fix #13085: DefaultCommand prevent NPE if target does not exist
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect

#13092 Fix #13091: 14.0.10 Datatable enable editors after validation failure
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13093 Fix #13091: Datatable enable editors after validation failure
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13097 Fixes #13094
  docs/15_0_0/core/errorhandling.md
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxexceptionhandler/ajaxexceptionhandler.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
Labels: enhancement

#13102 Fix #13101: InputNumber with currencySymbol with space
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#13103 Fix #13101: 14.0.10 InputNumber with currencySymbol with space
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#13105 Fix #12097/#12455/#13096: DatePicker yearNavigator allow old select dropdown
  docs/15_0_0/components/datepicker.md
  docs/migrationguide/15_0_0.md
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DatePicker.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement

#13108 Fix #11974: Autocomplete multiple mode support float label
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#13112 Fix #13001: Widget restore dashes
  primefaces/src/main/java/org/primefaces/component/api/Widget.java
Labels: :lady_beetle: defect

#13111 Fix #13001: 14.0.10 Widget restore dashes
  primefaces/src/main/java/org/primefaces/component/api/Widget.java
Labels: :lady_beetle: defect

#13114 Fix #12427: Autonumeric 4.10.8 fixes IME(Japanese) character input
  docs/14_0_0/core/thirdpartylibs.md
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: :lady_beetle: defect

#13113 Fix #12427: 14.0.10 Autonumeric 4.10.8 fixes IME(Japanese) character input
  docs/14_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/0-autoNumeric.js
Labels: :lady_beetle: defect

#13121 Fix #13120: primefaces.password.INVALID_MATCH_detail quote fields
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/password/Password004Test.java
  primefaces/src/main/resources/org/primefaces/Messages.properties
  primefaces/src/main/resources/org/primefaces/Messages_cs.properties
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
  primefaces/src/main/resources/org/primefaces/Messages_el.properties
  primefaces/src/main/resources/org/primefaces/Messages_en.properties
  primefaces/src/main/resources/org/primefaces/Messages_es.properties
  primefaces/src/main/resources/org/primefaces/Messages_fa.properties
  primefaces/src/main/resources/org/primefaces/Messages_hi.properties
  primefaces/src/main/resources/org/primefaces/Messages_hr.properties
  primefaces/src/main/resources/org/primefaces/Messages_in.properties
  primefaces/src/main/resources/org/primefaces/Messages_it.properties
  primefaces/src/main/resources/org/primefaces/Messages_ja.properties
  primefaces/src/main/resources/org/primefaces/Messages_ka.properties
  primefaces/src/main/resources/org/primefaces/Messages_ko.properties
  primefaces/src/main/resources/org/primefaces/Messages_lt.properties
  primefaces/src/main/resources/org/primefaces/Messages_lv.properties
  primefaces/src/main/resources/org/primefaces/Messages_nl.properties
  primefaces/src/main/resources/org/primefaces/Messages_no.properties
  primefaces/src/main/resources/org/primefaces/Messages_pl.properties
  primefaces/src/main/resources/org/primefaces/Messages_pt.properties
  primefaces/src/main/resources/org/primefaces/Messages_ro.properties
  primefaces/src/main/resources/org/primefaces/Messages_ru.properties
  primefaces/src/main/resources/org/primefaces/Messages_sk.properties
  primefaces/src/main/resources/org/primefaces/Messages_sv.properties
  primefaces/src/main/resources/org/primefaces/Messages_tr.properties
  primefaces/src/main/resources/org/primefaces/Messages_zh.properties
Labels: enhancement

#13123 Fix #13122: SelectBooleanCheckbox support fluid
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: enhancement

#13124 Fix #13122: 14.0.10 SelectBooleanCheckbox support fluid
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: enhancement

#13127 Fix #13125: PrimeFace.scrollTo allow jQuery element + doc
  docs/15_0_0/core/javascriptAPI.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: enhancement
