Repository primefaces/primefaces, pull requests merged in 2024-09, with the labels that each got.

#12546 Fix #12274: CellEditor update cell editors after any AJAX update
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12547 Fix #12274: 14.0.5 CellEditor update cell editors after any AJAX update
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12553 Fix #12551: Validator allowTypes regex with flags
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.validators.js
Labels: :lady_beetle: defect

#12552 Fix #12551: 14.0.5 Validator allowTypes regex with flags
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.validators.js
Labels: :lady_beetle: defect

#12556 XDev 2.2.0 change Color to RGBAColor
  docs/14_0_0/components/chart.md
  docs/15_0_0/components/chart.md
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chartjs/ChartView.java
Labels: dependencies

#11649 Fix #11640 - Core: introduce PrimeUIData (replacement of UIData)
  conf/checkstyle-tests.xml
  conf/checkstyle.xml
  primefaces/src/main/java/org/primefaces/component/api/PrimeUIData.java
  primefaces/src/main/java/org/primefaces/component/api/UIData.java
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/chronoline/ChronolineBase.java
  primefaces/src/main/java/org/primefaces/component/columns/ColumnsBase.java
  primefaces/src/main/java/org/primefaces/component/datascroller/DataScrollerBase.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableHandler.java
  primefaces/src/main/java/org/primefaces/component/diagram/DiagramBase.java
  primefaces/src/main/java/org/primefaces/component/patch/UIDataPatch.java
  primefaces/src/main/java/org/primefaces/event/CellEditEvent.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
Labels: enhancement

#12565 Fix #12564: Calendar add jquery plugins
  primefaces/src/main/java/org/primefaces/component/calendar/Calendar.java
Labels: :lady_beetle: defect

#12566 Fix #12564: 14.0.5 Calendar add jquery plugins
  primefaces/src/main/java/org/primefaces/component/calendar/Calendar.java
Labels: :lady_beetle: defect

#12567 Fix #12560: Plain Menu don't highlight until focused
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: accessibility

#12568 Fix #12560: 14.0.5 Plain Menu don't highlight until focused
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: accessibility

#12574 Fix #12572: 14.0.5 Chart add canvas style and class properties
  docs/14_0_0/components/chart.md
  primefaces/src/main/java/org/primefaces/component/chart/ChartBase.java
  primefaces/src/main/java/org/primefaces/component/chart/ChartRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#12575 Fix #12572: Chart add canvas style and class properties
  docs/14_0_0/components/chart.md
  docs/15_0_0/components/chart.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/chart/ChartBase.java
  primefaces/src/main/java/org/primefaces/component/chart/ChartRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#12573 Fix #12571: Datatable reflow CSS improvements
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: enhancement

#12588 #12587 DatePicker fluid input width
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: theme

#12589 Fix #12587: 14.0.6 DatePicker fluid input width
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#12583 Fix #12577: Screenreader improve hidden accessible
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.css
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.pfextensions.css
Labels: accessibility

#12582 Fix #12570: InputNumber change padControl from boolean to string for flexibility
  docs/15_0_0/components/inputnumber.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberBase.java
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#12585 Fix #12584: 14.0.6 SelectOneMenu support readonly attribute
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12586 Fix #12584: SelectOneMenu support readonly attribute
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12592 Fix #12591: Reduce Html5FacesContextResponseWriter instantiation
  primefaces/src/main/java/org/primefaces/application/factory/Html5FacesContext.java
Labels: :zap: performance

#12593 Fix #12591: 14.0.6 Reduce Html5FacesContextResponseWriter instantiation
  primefaces/src/main/java/org/primefaces/application/factory/Html5FacesContext.java
Labels: :zap: performance

#12539 Fix #12526: SelectOne ARIA/WCAG for groups
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: accessibility

#12598 Fix #12597: Datatable CSS selector too broad
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12599 Fix #12597: 14.0.6 Datatable CSS selector too broad
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.css
Labels: :lady_beetle: defect

#12602 Fix #12600: 14.0.6 DataTable cell editing tabbing restored
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12603 Fix #12600: DataTable cell editing tabbing restored
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12610 Fixed mismatched parentheses in JPALazyDataModel example
  docs/14_0_0/components/datatable.md
Labels: documentation

#12605 Fix #12604: JPA do not UPPERCASE numeric columns
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: :lady_beetle: defect

#12620 Fix #11623: SelectOneListBox improve ARIA support
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectlistbox.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonelistbox.js
Labels: accessibility

#12626 Fix #12623: Message inherit UIMessage
  primefaces-integration-tests/src/main/webapp/message/message001.xhtml
  primefaces-integration-tests/src/main/webapp/message/message002.xhtml
  primefaces/src/main/java/org/primefaces/component/message/MessageBase.java
Labels: :lady_beetle: defect

#12627 Fix #12623: 14.0.6 Message inherit UIMessage
  primefaces-integration-tests/src/main/webapp/message/message001.xhtml
  primefaces-integration-tests/src/main/webapp/message/message002.xhtml
  primefaces/src/main/java/org/primefaces/component/message/MessageBase.java
Labels: :lady_beetle: defect

#12632 Card update showcase to demonstrate ARIA
  primefaces-showcase/src/main/webapp/ui/panel/card.xhtml
Labels: documentation

#12634 Fix #12633: Chart fix client doc link
  docs/14_0_0/components/chart.md
  docs/15_0_0/components/chart.md
  primefaces-showcase/src/main/webapp/ui/chart/bar.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/bubble.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/custom.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/doughnut.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/export.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/facet.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/line.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/pie.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/polararea.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/radar.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/scatter.xhtml
Labels: documentation

#12635 Fix #12633: 14.0.6 Chart fix client doc link
  docs/14_0_0/components/chart.md
  primefaces-showcase/src/main/webapp/ui/chart/bar.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/bubble.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/custom.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/doughnut.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/export.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/facet.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/line.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/pie.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/polararea.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/radar.xhtml
  primefaces-showcase/src/main/webapp/ui/chart/scatter.xhtml
Labels: documentation

#12640 Showcase: update SC namespace to be URN
  primefaces-showcase/src/main/webapp/WEB-INF/showcase.taglib.xml
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
  primefaces-showcase/src/main/webapp/ui/data/timeline/editServer.xhtml
  primefaces-showcase/src/main/webapp/ui/data/timeline/grouping.xhtml
  primefaces-showcase/src/main/webapp/ui/data/timeline/lazy.xhtml
  primefaces-showcase/src/main/webapp/ui/data/timeline/nestedGrouping.xhtml
  primefaces-showcase/src/main/webapp/ui/misc/cache.xhtml
Labels: documentation

#12637 Fix #12636: 14.0.6 Tooltip correct arrow if using my/at
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12638 Fix #12636: Tooltip correct arrow if using my/at
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12641 Fix #12639: DatePicker fix range validation
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePicker.java
Labels: :lady_beetle: defect

#12642 Fix #12639: 14.0.6 DatePicker fix range validation
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePicker.java
Labels: :lady_beetle: defect

#12628 Fix #12625: Improve poor performance of paginated treeTable with larg…
  primefaces/src/main/java/org/primefaces/component/api/UITree.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTable.java
Labels: :zap: performance

#12643 Fix #12625: 14.0.6 Improve poor performance of paginated treeTable
  primefaces/src/main/java/org/primefaces/component/api/UITree.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTable.java
Labels: :zap: performance

#12653 Fix #12649 14.06 IT instability since Chrome 128
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeSelenium.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/internal/DefaultWebDriverAdapter.java
Labels: :lady_beetle: defect, integration_test

#12615 Fixes primefaces/primefaces#12614, include allSuffix in cache key for importEnum tag
  CONTRIBUTING.md
  docs/15_0_0/components/importenum.md
  docs/migrationguide/15_0_0.md
  primefaces-showcase/src/main/webapp/ui/misc/importEnum.xhtml
  primefaces/src/main/java/org/primefaces/component/importenum/ImportEnumTagHandler.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12613 Fix #12157: DatePicker add default hour,minute,second,ms
  docs/15_0_0/components/calendar.md
  docs/15_0_0/components/datepicker.md
  docs/15_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/15_0_0.md
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/api/UICalendar.java
  primefaces/src/main/java/org/primefaces/component/calendar/CalendarBase.java
  primefaces/src/main/java/org/primefaces/component/calendar/CalendarRenderer.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: enhancement
