Repository primefaces/primefaces, pull requests merged in 2024-08, with the labels that each got.

#12355 Fix #12352: Spinner allow min+required to be NULL
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/spinner/Spinner007.java
  primefaces-integration-tests/src/main/webapp/spinner/spinner007.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner007Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Spinner.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#12360 Fix #12352: 14.0.4 Spinner allow min+required to be NULL
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/spinner/Spinner007.java
  primefaces-integration-tests/src/main/webapp/spinner/spinner007.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner007Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Spinner.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/spinner/spinner.js
Labels: :lady_beetle: defect

#12367 Fix #12362 14.0.4 DefaultLazyDataModel: better implementation of count
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
Labels: :zap: performance

#12372 Fix #12366: 14.0.4 DefaultLazyDataModel: add ability for mixed filterBy in valueSupplier method and also automatic reflection based
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable001.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable002.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/DataTable044.java
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
Labels: enhancement

#12373 #12371 - PropertyDescriptorResolver: add setValue, similar to getValue
  primefaces/src/main/java/org/primefaces/util/PropertyDescriptorResolver.java
  primefaces/src/test/java/org/primefaces/util/PropertyDescriptorResolverTest.java
Labels: enhancement

#12374 Fix #12371 14.0.4 PropertyDescriptorResolver: add setValue, similar to getValue
  primefaces/src/main/java/org/primefaces/util/PropertyDescriptorResolver.java
  primefaces/src/test/java/org/primefaces/util/PropertyDescriptorResolverTest.java
Labels: enhancement

#12370 Fix #12361: DatePicker allow click to popup panel again
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: accessibility

#12375 Fix #12361: 14.0.4 DatePicker allow click to popup panel again
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: accessibility

#12369 Fix #12365: Spinner do not allow ONLY a thousandsSeparator char or any invalid number
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner001Test.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
Labels: :lady_beetle: defect

#12376 Fix #12365: 14.0.4 Spinner do not allow ONLY a thousandsSeparator char or any invalid number
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/spinner/Spinner001Test.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
Labels: :lady_beetle: defect

#12381 Fix #12379 14.0.4 DataTable: dont try to write filterValue back to EL if its read-only
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
Labels: enhancement

#12386 Fix #12349: MenuButton fix appendTo and Dialog support
  docs/14_0_0/components/menubutton.md
  docs/15_0_0/components/menubutton.md
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
Labels: :lady_beetle: defect

#12387 Fix #12349: 14.0.4 MenuButton fix appendTo and Dialog support
  docs/14_0_0/components/menubutton.md
  primefaces/src/main/java/org/primefaces/component/menubutton/MenuButtonBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
Labels: :lady_beetle: defect

#12383 Fix #12378: 14.0.4 Plain Menu only add ui-state-hover on hover
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: accessibility

#12388 Fix #12385: DatePicker respect readonly=true
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12389 Fix #12385: 14.0.4 DatePicker respect readonly=true
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12391 Fix #12390: Move QRCode to its own page so its now in AppMenu
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/multimedia/barcode.xhtml
  primefaces-showcase/src/main/webapp/ui/multimedia/qrcode.xhtml
Labels: documentation

#12242 Fix #12234: DatePicker initialize defaults on decode
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
Labels: :lady_beetle: defect

#12244 Fix #12234: 14.0.4 DatePicker initialize defaults on decode
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
Labels: :lady_beetle: defect

#12402 Showcase: Tree lazy example NPE in Quarkus showcase
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/data/tree/FileInfo.java
Labels: documentation

#12400 Fix #12399: CSP improve NULL checking
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/core/csp/CoreCsp001.java
  primefaces-integration-tests/src/main/webapp/core/csp/coreCsp001-page2.xhtml
  primefaces-integration-tests/src/main/webapp/core/csp/coreCsp001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/csp/CoreCsp001Test.java
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: :lady_beetle: defect

#12401 Fix #12399: 14.0.4 CSP improve NULL checking
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/core/csp/CoreCsp001.java
  primefaces-integration-tests/src/main/webapp/core/csp/coreCsp001-page2.xhtml
  primefaces-integration-tests/src/main/webapp/core/csp/coreCsp001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/csp/CoreCsp001Test.java
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: :lady_beetle: defect

#12392 Fix #11735: Added rowsPerPage in the PageEvent
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGrid.java
  primefaces/src/main/java/org/primefaces/component/datalist/DataList.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataView.java
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTable.java
  primefaces/src/main/java/org/primefaces/event/data/PageEvent.java
Labels: enhancement

#12407 IT: CSP failing test
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/csp/CoreCsp001Test.java
  primefaces/src/main/java/org/primefaces/application/exceptionhandler/PrimeExceptionHandler.java
Labels: integration_test

#12410 Fix #12409: 14.0.5 Showcase do not try to show inner classes source
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/FileContentMarkerUtil.java
Labels: :lady_beetle: defect

#12411 Fix #12409: Showcase do not try to show inner classes source
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/FileContentMarkerUtil.java
Labels: :lady_beetle: defect

#12414 Fix #12412: 14.0.5 Menu base use getMenuElement() vs this.jq
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
Labels: :lady_beetle: defect

#12415 Fix #12412: Menu base use getMenuElement() vs this.jq
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
Labels: :lady_beetle: defect

#12421 Fix #12420: ColorPicker required error leave field empty
  primefaces/src/main/java/org/primefaces/component/colorpicker/ColorPickerRenderer.java
Labels: :lady_beetle: defect

#12430 Fix #12428: DatePicker remove InputMask blur event
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#12431 Fix #12428: 14.0.5 DatePicker remove InputMask blur event
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#12417 Fix #12416: Core.js use crypto.randomUUID if available
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lock: security

#12453 Add Bangla locale
  primefaces-showcase/src/main/java/org/primefaces/showcase/service/CountryService.java
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bn.js
  primefaces/src/main/type-definitions/blocklist.txt
Labels: enhancement

#12442 Fix #12441: Password with ui-fluid and toggle mask
  primefaces-showcase/src/main/webapp/ui/misc/floatLabel.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#12443 Fix #12441: 14.0.5 Password with ui-fluid and toggle mask
  primefaces-showcase/src/main/webapp/ui/misc/floatLabel.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#12446 Fix #12444: Float Label handle browser auto-fill universally
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect, sponsoring required

#12445 Fix #12444: 14.0.5 Float Label handle browser auto-fill universally
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect, sponsoring required

#12439 Fix #12438: SelectBooleanCheckbox enable/disable widget properly
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectbooleancheckbox.js
Labels: :lady_beetle: defect

#12440 Fix #12438: 14.0.5 SelectBooleanCheckbox enable/disable widget properly
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectbooleancheckbox.js
Labels: :lady_beetle: defect

#12459 Fix #12454: DatePicker increase default year range to 2000
  docs/14_0_0/components/datepicker.md
  docs/15_0_0/components/datepicker.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12461 Fix #12454: 14.0.5 DatePicker increase default year range to 2000
  docs/14_0_0/components/datepicker.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12457 Fix #12456: Plain menu implement missing navigation keys
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: accessibility

#12458 Fix #12456: 14.0.5 Plain menu implement missing navigation keys
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: accessibility

#12472 Update docs to say Java 11 for PF14/15
  docs/14_0_0/gettingstarted/dependencies.md
  docs/15_0_0/gettingstarted/dependencies.md
Labels: documentation

#12467 Fix #12465: DatePicker always format in EN for conversion
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12468 Fix #12465: 14.0.5 DatePicker always format in EN for conversion
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12476 Fix #12475: 14.0.5 SelectManyCheckbox better responsive fix
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/grid/grid.css
Labels: :lady_beetle: defect

#12477 Fix #12475: SelectManyCheckbox responsive fixes
  primefaces-showcase/src/main/webapp/ui/input/manyCheckbox.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
  primefaces/src/main/resources/META-INF/resources/primefaces/grid/grid.css
Labels: :lady_beetle: defect

#12482 Fix hrefLang docs and Link showcase text
  docs/10_0_0/components/commandlink.md
  docs/11_0_0/components/commandlink.md
  docs/12_0_0/components/commandlink.md
  docs/13_0_0/components/commandlink.md
  docs/14_0_0/components/commandlink.md
  docs/15_0_0/components/commandlink.md
  docs/7_0/components/commandlink.md
  docs/8_0/components/commandlink.md
  primefaces-showcase/src/main/webapp/ui/button/link.xhtml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12478 Sonar cleanup possible security DOS warnings
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.clientwindow.js
Labels: :lock: security

#12487 Fix #12470: 14.0.5 WidgetVarSearchKeywordResolver fixed possible NPE
  primefaces/src/main/java/org/primefaces/expression/WidgetVarSearchKeywordResolver.java
Labels: :lady_beetle: defect

#12495 selectionMode is deprecated inside p:column
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
Labels: documentation

#12494 #12473 AutoUpdate: @obs() is updating dialog with dynamic="true" for no reason
  primefaces/src/main/java/org/primefaces/component/autoupdate/AutoUpdateListener.java
  primefaces/src/main/java/org/primefaces/component/autoupdate/AutoUpdatePhaseListener.java
Labels: :lady_beetle: defect

#12499 Fix #12473: 14.0.5 AutoUpdate @obs() fix
  primefaces/src/main/java/org/primefaces/component/autoupdate/AutoUpdateListener.java
  primefaces/src/main/java/org/primefaces/component/autoupdate/AutoUpdatePhaseListener.java
Labels: :lady_beetle: defect

#12496 Fix #12485: Menu respect disabled state
  primefaces-showcase/src/main/webapp/ui/menu/menu.xhtml
  primefaces-showcase/src/main/webapp/ui/menu/menubar.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
Labels: :lady_beetle: defect

#12497 Fix #12485: 14.0.5 Menu respect disabled state
  primefaces-showcase/src/main/webapp/ui/menu/menu.xhtml
  primefaces-showcase/src/main/webapp/ui/menu/menubar.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
Labels: :lady_beetle: defect

#12466 Fix #12463: Signature allow typed text, improve accessibility
  docs/14_0_0/components/signature.md
  docs/15_0_0/components/signature.md
  docs/15_0_0/core/thirdpartylibs.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SignatureView.java
  primefaces-showcase/src/main/webapp/ui/input/signature.xhtml
  primefaces/src/main/java/org/primefaces/component/signature/Signature.java
  primefaces/src/main/java/org/primefaces/component/signature/SignatureBase.java
  primefaces/src/main/java/org/primefaces/component/signature/SignatureRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/0-signature.js
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/1-widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/signature.css
Labels: enhancement, accessibility, sponsoring required

#12504 Chart.js 4.4.4
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/chart/0-chartjs.min.js
Labels: dependencies, javascript

#12505 Fix #12463: 14.0.5 Signature allow typed text, improve accessibility
  docs/14_0_0/components/signature.md
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/SignatureView.java
  primefaces-showcase/src/main/webapp/ui/input/signature.xhtml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/signature/Signature.java
  primefaces/src/main/java/org/primefaces/component/signature/SignatureBase.java
  primefaces/src/main/java/org/primefaces/component/signature/SignatureRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/0-signature.js
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/1-widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/signature/signature.css
Labels: enhancement, accessibility, sponsoring required

#12489 Fix #12481: 14.0.5 Tree allow filter event to override node state
  primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java
Labels: :lady_beetle: defect

#12514 Fix #12506: LinkButton ariaLabel docs update
  docs/14_0_0/components/linkbutton.md
  docs/15_0_0/components/linkbutton.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12503 Fix #12428: InputMask 5.0.10 bug with German date format
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/0-jquery.inputmask.js
Labels: :lady_beetle: defect

#12513 Fix #12428: 14.0.5 InputMask 5.0.10 bug with German date format
  primefaces/src/main/resources/META-INF/resources/primefaces/inputmask/0-jquery.inputmask.js
Labels: :lady_beetle: defect

#12516 Fix #12502: JSF to Jakarta Faces in 15.0 docs
  docs/15_0_0/components/ajaxstatus.md
  docs/15_0_0/components/autocomplete.md
  docs/15_0_0/components/blockui.md
  docs/15_0_0/components/captcha.md
  docs/15_0_0/components/commandbutton.md
  docs/15_0_0/components/commandlink.md
  docs/15_0_0/components/contextmenu.md
  docs/15_0_0/components/datatable.md
  docs/15_0_0/components/defaultcommand.md
  docs/15_0_0/components/effect.md
  docs/15_0_0/components/fileupload.md
  docs/15_0_0/components/focus.md
  docs/15_0_0/components/graphicimage.md
  docs/15_0_0/components/growl.md
  docs/15_0_0/components/lifecycle.md
  docs/15_0_0/components/linkbutton.md
  docs/15_0_0/components/log.md
  docs/15_0_0/components/message.md
  docs/15_0_0/components/messages.md
  docs/15_0_0/components/organigram.md
  docs/15_0_0/components/outputpanel.md
  docs/15_0_0/components/printer.md
  docs/15_0_0/components/resizable.md
  docs/15_0_0/components/schedule.md
  docs/15_0_0/components/terminal.md
  docs/15_0_0/core/accessibility.md
  docs/15_0_0/core/ajaxJavascriptApi.md
  docs/15_0_0/core/ajaxPartialsubmit.md
  docs/15_0_0/core/ajaxProcessing.md
  docs/15_0_0/core/ajaxRendering.md
  docs/15_0_0/core/beanvalidationtransformation.md
  docs/15_0_0/core/clientwindow.md
  docs/15_0_0/core/csv.md
  docs/15_0_0/core/dynamiccontent.md
  docs/15_0_0/core/globalattributes.md
  docs/15_0_0/core/javascriptAPI.md
  docs/15_0_0/core/misc.md
  docs/15_0_0/core/multiviewstate.md
  docs/15_0_0/core/performance.md
  docs/15_0_0/core/portlets.md
  docs/15_0_0/core/searchexpression.md
  docs/15_0_0/gettingstarted/dependencies.md
  docs/15_0_0/gettingstarted/download.md
  docs/15_0_0/home.md
Labels: documentation

#12517 Fix #12508: Confirm dialog non-global example
  primefaces-showcase/src/main/webapp/ui/overlay/confirmDialog.xhtml
Labels: documentation

#12512 Fix #12507 - DataTable: default input facet filter not working with dynamic columns
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
  primefaces/src/main/java/org/primefaces/event/CellEditEvent.java
  primefaces/src/main/java/org/primefaces/model/FilterMeta.java
  primefaces/src/main/java/org/primefaces/util/CompositeUtils.java
  primefaces/src/main/java/org/primefaces/util/EditableValueHolderState.java
Labels: :lady_beetle: defect

#12524 Fix #12474: TreeTable filter dynamic columns
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#12523 Fix #12507: 14.0.5 DataTable default input facet filter not working with dynamic columns
  primefaces/src/main/java/org/primefaces/component/api/UIColumn.java
  primefaces/src/main/java/org/primefaces/component/api/UITable.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/component/outputlabel/OutputLabelRenderer.java
  primefaces/src/main/java/org/primefaces/event/CellEditEvent.java
  primefaces/src/main/java/org/primefaces/model/FilterMeta.java
  primefaces/src/main/java/org/primefaces/util/CompositeUtils.java
  primefaces/src/main/java/org/primefaces/util/EditableValueHolderState.java
Labels: :lady_beetle: defect

#12525 Fix #12474: 14.0.5 TreeTable filter dynamic columns
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#12433 Fix #12429: jQuery UI 1.14.0
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/0-jquery.ui.datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.js
Labels: dependencies

#12532 XDev 2.1.0
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chartjs/ChartView.java
Labels: dependencies, java

#12542 Fix #12541: DatePicker enabledDates taglib.xml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#12543 Fix #12541: 14.0.5 DatePicker enabledDates taglib.xml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect
