Repository primefaces/primefaces, pull requests merged in 2024-06, with the labels that each got.

#12050 Fix #12049: Datatable allow click event to passthrough to clickable elements
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12053 Fix #12049: 14.0.1 Datatable allow click event to passthrough to clickable elements
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12047 Fix #12045: SameSite=Lax default for JSF 4.0
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12046 Fix #12045: 14.0.1 SameSite=Lax default for JSF 4.0
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12048 Fix #12044: Rating accessibility and bug fixes
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/rating/Rating001.java
  primefaces-integration-tests/src/main/webapp/rating/rating001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/rating/Rating001Test.java
  primefaces-showcase/src/main/webapp/ui/input/rating.xhtml
  primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java
  primefaces/src/main/java/org/primefaces/util/LangUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/rating/rating.js
Labels: :lady_beetle: defect, accessibility

#12058 Fix #12044: 14.0.1 Rating accessibility and bug fixes
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/rating/Rating001.java
  primefaces-integration-tests/src/main/webapp/rating/rating001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/rating/Rating001Test.java
  primefaces-showcase/src/main/webapp/ui/input/rating.xhtml
  primefaces/src/main/java/org/primefaces/component/rating/RatingRenderer.java
  primefaces/src/main/java/org/primefaces/util/LangUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/rating/rating.js
Labels: :lady_beetle: defect

#12014 Fix #11980: Auto detect HTML5 compliance
  docs/15_0_0/gettingstarted/configuration.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
  primefaces/src/main/java/org/primefaces/renderkit/RendererUtils.java
Labels: enhancement

#11998 Fix #11994: TabView prevent detached DOM elements on TabClose
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :zap: performance

#11997 Fix #11994: 14.0.1 TabView prevent detached DOM elements on TabClose
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tabview/tabview.js
Labels: :zap: performance

#12057 Fix #12056:Datatabe/TreeTable do not clear readonly/disabled filters
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: enhancement

#12064 Fix #12059: PickList prevent submission manipulation
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/picklist/PickList002.java
  primefaces-integration-tests/src/main/webapp/picklist/picklist002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/picklist/PickList002Test.java
  primefaces/src/main/java/org/primefaces/component/picklist/PickList.java
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: :lock: security

#12065 Fix #12059: 14.0.1 PickList prevent submission manipulation
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/picklist/PickList002.java
  primefaces-integration-tests/src/main/webapp/picklist/picklist002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/picklist/PickList002Test.java
  primefaces/src/main/java/org/primefaces/component/picklist/PickList.java
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: :lock: security

#12073 Fix #12068: Datatable checkbox selection with SPACE/ENTER
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#12078 Fix #12068: 14.0.1 Datatable checkbox selection with SPACE/ENTER
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: accessibility

#12055 Fix #12054: Taglib don't allow VAR as EL expression
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12095 Fix #12088: 14.0.1 DatePicker AJAX close called multiple times
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12081 Fix #12080: Separator deprecated
  docs/migrationguide/15_0_0.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/misc/separator.xhtml
  primefaces-showcase/src/main/webapp/ui/misc/spacer.xhtml
  primefaces/src/main/java/org/primefaces/component/separator/SeparatorRenderer.java
  primefaces/src/main/java/org/primefaces/component/separator/UISeparator.java
  primefaces/src/main/java/org/primefaces/component/separator/UISeparatorBase.java
Labels: breaking-change

#12092 #12085 Core: Ajax performance (cleanseDomElement): No need to cleanse options elements
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :zap: performance

#12096 Fix #12085 14.0.1 Core: Ajax performance (cleanseDomElement)
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :zap: performance

#12102 Fix #12098: Tooltip fix autoHide="false"
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12103 Fix #12098: 14.0.1 Tooltip fix autoHide="false"
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12107 Fix #12106: Splitter support touch devices
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
Labels: :lady_beetle: defect

#12108 Fix #12106: 14.0.1 Splitter support touch devices
  primefaces/src/main/resources/META-INF/resources/primefaces/splitter/splitter.js
Labels: :lady_beetle: defect

#12109 Fix #12099: p:columns rendered in p:columnGroup not fully working
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: :lady_beetle: defect

#12110 Fix #12099: 14.0.1 p:columns rendered in p:columnGroup not fully working
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: :lady_beetle: defect

#12112 Fix #12098: Tooltip autoHide="false" hidden when not crossing arrow
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12015 Fix #11850: SelectCheckBoxMenu ARIA accessibility updates
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu001Test.java
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenu.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: accessibility

#12111 Fix #11850: 14.0.1 SelectCheckBoxMenu ARIA accessibility updates
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu001Test.java
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenu.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: accessibility

#12115 XDev 2.0
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/chartjs/ChartView.java
Labels: dependencies

#12119 Fix #12118: Tooltip: escape selector for mouseTarget.closest
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12120 Fix #12117: Menu fix focus infinite loop
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: :lady_beetle: defect

#12121 Fix #12117: 14.0.2 Menu fix focus infinite loop
  pom.xml
  primefaces-cli/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.plainmenu.js
Labels: :lady_beetle: defect

#12122 Fix #12118: 14.0.2 Tooltip: escape selector for mouseTarget.closest
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#12076 Fix #12067: SelectOneMenu add 'clear' AJAX event for editable
  docs/15_0_0/components/selectonemenu.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenu.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: enhancement

#12129 Fix #12128: use captured this
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12133 Fix #12128: 14.0.2 Datatable updateExpansionAria called on wrong this
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#12134 Fix #12130: CommandLink restore TabIndex properly
  primefaces/src/main/java/org/primefaces/component/commandlink/CommandLinkRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js
Labels: :lady_beetle: defect

#12137 Fix #12130: 14.0.2 CommandLink restore TabIndex properly
  primefaces/src/main/java/org/primefaces/component/commandlink/CommandLinkRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.commandlink.js
Labels: :lady_beetle: defect

#12135 Fix #12131: TextEditor only fire change on API insert
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/1-texteditor.js
Labels: :lady_beetle: defect

#12132 Fixed #12131 14.0.2 TextEditor doesn't detect change of contents
  primefaces/src/main/resources/META-INF/resources/primefaces/texteditor/1-texteditor.js
Labels: :lady_beetle: defect

#12042 Update primefaces.taglib.xml -> fix description
  docs/14_0_0/components/datatable.md
  docs/15_0_0/components/datatable.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#12142 Fix #12138: Taglib only include URN version in Jakarta JAR
  primefaces/pom.xml
Labels: documentation

#12152 Fix #12144: ARIA label null checking
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12153 Fix #12144: 14.0.2 ARIA label null checking
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#12155 Fix #12140: CSP nonce validation
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: :lock: security

#12159 Fix #12140: 14.0.2 CSP nonce validation
  primefaces/src/main/java/org/primefaces/csp/CspState.java
Labels: :lock: security

#12156 Fix #12151: Sticky update global zIndex
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#12174 Update 13_0_0.md -> About chartOptions new features that are enabled by default
  docs/migrationguide/13_0_0.md
Labels: documentation

#12170 Fix #12169: Showcase add missing POJO/enums and Tag VDL
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/FileContent.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/FileContentMarkerUtil.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/ShowcaseUtil.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/app/App.java
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
  primefaces-showcase/src/main/webapp/ui/input/autoComplete.xhtml
Labels: documentation

#12179 Fix #12178: JPALazyDataModel use getId not getDeclaredId
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: :lady_beetle: defect

#12180 Fix #12178: 14.0.2 JPALazyDataModel use getId not getDeclaredId
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: :lady_beetle: defect

#12149 Fix #12143: MenuButton remove duplicate inherited code
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
Labels: :lady_beetle: defect

#12150 Fix #12143: 14.0.2 MenuButton remove duplicate inherited code
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubutton.js
Labels: :lady_beetle: defect

#12181 Fix #12172: Touch devices don't register resize handlers
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.env.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12182 Fix #12172: 14.0.2 Touch devices don't register resize handlers
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.env.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#12188 Fix #12187: InputNumber add modifyValueOnUpDownArrow
  docs/15_0_0/components/inputnumber.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberBase.java
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#12186 Fix #12185: DatePicker setViewDate add silent option
  docs/15_0_0/components/datepicker.md
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: enhancement

#12191 Upgrade download.js 4.21
  docs/15_0_0/core/thirdpartylibs.md
  primefaces/src/main/resources/META-INF/resources/primefaces/filedownload/0-download.js
Labels: dependencies, javascript

#12208 Wizard: update custom UI docs
  docs/11_0_0/components/wizard.md
  docs/12_0_0/components/wizard.md
  docs/13_0_0/components/wizard.md
  docs/14_0_0/components/wizard.md
  docs/15_0_0/components/wizard.md
Labels: documentation

#12200 Fix #12197: Tree allow label to be selectable for copying
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
Labels: enhancement

#12216 Fix #12169: Showcase handle invalid proxy classes
  primefaces-showcase/src/main/java/org/primefaces/showcase/util/FileContentMarkerUtil.java
  primefaces-showcase/src/main/webapp/ui/button/productDetail.xhtml
Labels: documentation

#12204 Fix #12203: Calendar restore pattern usage
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/calendar/Calendar001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/calendar/Calendar002Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
Labels: :lady_beetle: defect

#12205 Fix #12203: 14.0.2 Calendar restore pattern usage
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/calendar/Calendar001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/calendar/Calendar002Test.java
  primefaces/src/main/resources/META-INF/resources/primefaces/calendar/4-calendar.js
Labels: :lady_beetle: defect

#12217 Showcase improve Tag VDL link handling
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/app/App.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/app/TagLibrary.java
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
Labels: documentation

#12215 Fix #12214: RowExpansion rendered fix
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/RowExpandFeature.java
  primefaces/src/main/java/org/primefaces/util/ComponentTraversalUtils.java
Labels: :lady_beetle: defect

#12219 Fix #12214: 14.0.2 RowExpansion rendered fix
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/datatable/feature/RowExpandFeature.java
  primefaces/src/main/java/org/primefaces/util/ComponentTraversalUtils.java
Labels: :lady_beetle: defect

#12220 Fix #12207 - Fileupload: Advanced + drag&drop will resend binary on every ajax in form when form has enctype="multipart/form-data"
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect

#12221 Fix #12207 14.0.2 Fileupload: Advanced + drag&drop will resend binary…
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect
