Repository primefaces/primefaces, pull requests merged in 2025-06, with the labels that each got.

#13889 Fix #13883: Datatable respect ariaRowLabel
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: accessibility

#13886 Fix #13884: 15.0.5 TreeTable implement filterPosition
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#13895 Warning in documentation regarding p:datatable cell eding mode
  docs/10_0_0/components/datatable.md
  docs/11_0_0/components/datatable.md
  docs/12_0_0/components/datatable.md
  docs/13_0_0/components/datatable.md
  docs/14_0_0/components/datatable.md
  docs/15_0_0/components/datatable.md
  docs/16_0_0/components/datatable.md
Labels: documentation

#13909 Tomcat 10.1.41
  pom.xml
Labels: dependencies, integration_test

#13916 Fix #13911: AutoComplete clear event is fired when item via dropdown is selected with forceSelection
  primefaces/src/main/frontend/packages/components/src/autocomplete/autocomplete.widget.js
Labels: :lady_beetle: defect

#13917 Fix #13911: 15.0.6 AutoComplete clear event is fired when item via dropdown is selected with forceSelection
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: :lady_beetle: defect

#13920 Fix #13915: 15.0.6 LTS page update
  primefaces-showcase/src/main/webapp/lts.xhtml
Labels: documentation

#13922 Showcase fix deps
  primefaces-showcase/pom.xml
Labels: documentation

#13929 Fix #13927: Add isEnterKeyBlocked and reuse in multiple locations
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
  primefaces/src/main/frontend/packages/components/src/forms/forms.defaultcommand.widget.js
  primefaces/src/main/frontend/packages/core/src/core/core.utils.ts
Labels: :lady_beetle: defect

#13925 #13934 Tomcat 10.1.42 - reloaded
  docs/15_0_0/components/fileupload.md
  docs/16_0_0/components/fileupload.md
  pom.xml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/TomcatDeploymentAdapter.java
Labels: documentation

#13931 Fix #13905: 15.0.6 Paginator aria-label for navigator
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: accessibility

#13932 Fix #13905: Paginator aria-label for navigator
  primefaces/src/main/frontend/packages/components/src/paginator/paginator.widget.js
Labels: accessibility

#13943 Fix #13926: 15.0.6 Add missing readonly attribute
  docs/15_0_0/components/cascadeselect.md
  docs/15_0_0/components/multiselectlistbox.md
  docs/15_0_0/components/selectbooleancheckbox.md
  docs/15_0_0/components/selectonelistbox.md
  docs/15_0_0/components/slider.md
  docs/15_0_0/components/toggleswitch.md
  primefaces/src/main/java/org/primefaces/component/cascadeselect/CascadeSelectBase.java
  primefaces/src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java
  primefaces/src/main/java/org/primefaces/component/multiselectlistbox/MultiSelectListboxBase.java
  primefaces/src/main/java/org/primefaces/component/selectbooleancheckbox/SelectBooleanCheckboxRenderer.java
  primefaces/src/main/java/org/primefaces/component/slider/SliderBase.java
  primefaces/src/main/java/org/primefaces/component/slider/SliderRenderer.java
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitchBase.java
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitchRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13947 Fix #13946: ToggleSwitch proper use of aria-checked
  primefaces/src/main/java/org/primefaces/component/toggleswitch/ToggleSwitchRenderer.java
Labels: accessibility

#13949 Fix #13941: Paginator remove legacy ui-icons
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/paginator/FirstPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/LastPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/NextPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PrevPageLinkRenderer.java
Labels: :lady_beetle: defect

#13950 Fix #13941: 15.0.6 Paginator remove legacy ui-icons
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/paginator/FirstPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/LastPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/NextPageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PrevPageLinkRenderer.java
Labels: :lady_beetle: defect

#13957 Fix #13954: 15.0.6 SelectOneRadio can select disabled items
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio006.java
  primefaces-integration-tests/src/main/webapp/selectoneradio/selectOneRadio006.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectoneradio/SelectOneRadio006Test.java
  primefaces/src/main/java/org/primefaces/renderkit/SelectRenderer.java
Labels: :lock: security

#13958 Fix #13953: 15.0.6 DataRenderer should not encode header facet for ARIA Header
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/DataRenderer.java
Labels: :lady_beetle: defect
