Repository primefaces/primefaces, pull requests merged in 2025-08, with the labels that each got.

#14037 Fix #14036: 15.0.7 Tooltip custom position fix
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: :lady_beetle: defect

#14063 Fix #14043: 15.0.7 TriStateCheckbox do not fire valueChange if readonly/disabled
  primefaces/src/main/java/org/primefaces/component/tristatecheckbox/TriStateCheckbox.java
Labels: :lady_beetle: defect

#14064 Fix #14043: TriStateCheckbox do not fire valueChange if readonly/disabled
  primefaces/src/main/java/org/primefaces/component/tristatecheckbox/TriStateCheckbox.java
Labels: :lady_beetle: defect

#14059 Implement #13700: if oncomplete represents a ValueExpression then run it via executeScript() after action event
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/core/ajax/CoreAjax002.java
  primefaces-integration-tests/src/main/webapp/core/ajax/coreAjax002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/core/ajax/CoreAjax002Test.java
  primefaces/src/main/frontend/packages/core/index.ts
  primefaces/src/main/frontend/packages/core/src/core/core.ajax.ts
  primefaces/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorRenderer.java
  primefaces/src/main/java/org/primefaces/behavior/base/AbstractBehavior.java
  primefaces/src/main/java/org/primefaces/component/api/DialogReturnAware.java
  primefaces/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java
  primefaces/src/main/java/org/primefaces/el/ValueExpressionStateHelper.java
  primefaces/src/main/java/org/primefaces/event/DynamicOncompleteEvent.java
  primefaces/src/main/java/org/primefaces/renderkit/CoreRenderer.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: enhancement

#14072 jQuery 4.0.0-rc.1
  primefaces/src/main/frontend/package.json
  primefaces/src/main/frontend/yarn.lock
Labels: dependencies, javascript

#14073 15.0.7 jQuery v4.0.0-rc.1
  primefaces/src/main/resources/META-INF/resources/primefaces/jquery/jquery.js
Labels: dependencies, javascript

#14079 Fix #14074: 15.0.7 KeyFilter add inputRegex example
  primefaces-showcase/src/main/webapp/ui/input/keyFilter.xhtml
Labels: documentation

#14088 Fix #14067: 15.0.7 InputNumber: move autoNumeric updating from blur to change event
  primefaces/src/main/resources/META-INF/resources/primefaces/inputnumber/1-inputnumber.js
Labels: :lady_beetle: defect

#14091 Fix #14087: 15.0.7 Draggable add onDrag client side event
  primefaces/src/main/resources/META-INF/resources/primefaces/dragdrop/dragdrop.js
Labels: :lady_beetle: defect

#14092 Fix #14087: Draggable add onDrag client side event
  primefaces/src/main/frontend/packages/components/src/dragdrop/dragdrop.widget.js
Labels: :lady_beetle: defect

#14093 Fix #14069: InputNumber respect autocomplete but default to "off"
  primefaces/src/main/java/org/primefaces/component/api/AbstractPrimeHtmlInputText.java
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect
