Repository primefaces/primefaces, pull requests merged in 2025-07, with the labels that each got.

#13975 Fix #13968: Datatable filter footer example
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
Labels: documentation

#13977 Vis Data 7.1.10, PrimeLocale 2.1.4
  primefaces/src/main/frontend/package.json
  primefaces/src/main/frontend/yarn.lock
Labels: dependencies, javascript

#13979 Fix #13978: 15.0.6 OutputPanel missing widgetVar in taglib
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13983 Fix #13965: InputNumber fix value change check
  primefaces/src/main/frontend/packages/inputnumber/inputnumber/src/inputnumber.widget.js
Labels: :lady_beetle: defect

#13973 Fix #13858: Extending validateFile with allowMediaTypes
  docs/16_0_0/validators/validateFile.md
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/java/org/primefaces/validate/FileValidator.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: enhancement

#13987 15.0.6 QRcode fix showcase
  primefaces-showcase/src/main/webapp/ui/multimedia/qrcode.xhtml
Labels: documentation

#13988 QRcode fix showcase
  primefaces-showcase/src/main/webapp/ui/multimedia/qrcode.xhtml
Labels: documentation

#13992 Fix #13990: Theme dialog footer button margin
  primefaces-themes/theme-base/components/overlay/_dialog.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: enhancement, theme

#13995 Fix #13989: 15.0.6 SelectOneButton ARIA role
  primefaces/src/main/java/org/primefaces/component/selectonebutton/SelectOneButtonRenderer.java
Labels: accessibility

#14000 AccordionPanel: respect rendered attribute for repeating tabs
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/accordionpanel/AccordionPanel005.java
  primefaces-integration-tests/src/main/webapp/accordionpanel/accordionPanel005.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/accordionpanel/AccordionPanel005Test.java
  primefaces/src/main/java/org/primefaces/component/accordionpanel/AccordionPanelRenderer.java
Labels: :lady_beetle: defect

#14003 Fix #13993: 15.0.6 ResourceUtils close inputstream
  primefaces/src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java
  primefaces/src/main/java/org/primefaces/util/ResourceUtils.java
Labels: :lady_beetle: defect

#13840 Fix #13836: Release workflow and Sonatype publisher upgrade
  .github/workflows/release.yml
  README.md
  pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
Labels: enhancement

#14011 Fix #14006: Menu keyboard focus non-disabled item
  primefaces/src/main/frontend/packages/components/src/menu/menu.base.widget.ts
Labels: accessibility

#14013 Fix #14012: ImageCompare remove Flickr
  primefaces/src/main/frontend/packages/imagecompare/imagecompare/src/juxtapose.js
Labels: :lock: security

#14026 Fix #14024: PanelMenu missing collapse icon
  primefaces/src/main/frontend/packages/components/src/menu/menu.panelmenu.widget.ts
Labels: :lady_beetle: defect

#14027 Fix #14018: 15.0.7 AutoComplete focus input on dropdown
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: :lady_beetle: defect

#14029 Fix #14007: 15.0.7 DatePicker improve min/max date handling
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#14033 15.x Messages: Add closable to widget config, respect in appendMessage function
  primefaces-integration-tests/src/main/webapp/messages/messages002.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/messages/Messages002Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java
  primefaces/src/main/java/org/primefaces/component/messages/Messages.java
  primefaces/src/main/java/org/primefaces/component/messages/MessagesRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/messages/messages.js
Labels: :lady_beetle: defect
