Repository primefaces/primefaces, pull requests merged in 2025-04, with the labels that each got.

#13663 Issue #13661 update 6_2 migration guide
  docs/migrationguide/6_2.md
Labels: documentation

#13667 Fix #13666 - Dialog fit viewport width in addition to height
  docs/16_0_0/components/dialog.md
  docs/16_0_0/core/dialogframework.md
  docs/PrimeFaces.d.ts
  primefaces-showcase/src/main/webapp/ui/overlay/dialog.xhtml
  primefaces/src/main/frontend/packages/components/src/dialog/dialog.widget.ts
  primefaces/src/main/frontend/packages/core/index.ts
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#13672 Fix #13671: SelectCheckboxMenu: Invalid SelectItems' value type not obvious
  primefaces/src/main/java/org/primefaces/renderkit/SelectRenderer.java
Labels: :lady_beetle: defect

#13652 Fix #13651: PrimeFlex 4.0.0
  docs/migrationguide/16_0_0.md
  primefaces-themes/theme-base/_colors.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: breaking-change

#13662 Fix #13658: AutoComplete prevent double escaping
  primefaces/src/main/frontend/packages/components/src/autocomplete/autocomplete.widget.js
Labels: :lady_beetle: defect

#13685 Fix #13582: InputNumber default range has issues for negative and zero Double and Float values
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect

#13686 Fix #13582: InputNumber do not use HashMaps
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect

#13687 Fix #13582: 15.0.4 InputNumber default range
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect

#13695 FIX FOR #13694 - targetElement in align method might be null
  primefaces/src/main/frontend/packages/components/src/overlaypanel/overlaypanel.widget.js
Labels: :lady_beetle: defect

#13696 Fix #13694: 15.0.4 targetElement in align method might be null
  primefaces/src/main/resources/META-INF/resources/primefaces/overlaypanel/overlaypanel.js
Labels: :lady_beetle: defect

#13703 Fix #13531: Separator menu style removal
  primefaces-themes/theme-base/components/menu/_menu.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: breaking-change

#13692 Fix #13689: @Positive use min value = 0
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputnumber/InputNumber004Test.java
  primefaces/src/main/java/org/primefaces/validate/bean/PositiveClientValidationConstraint.java
Labels: :lady_beetle: defect

#13693 Fix #13689: 15.0.4 @Positive use min value = 0
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputnumber/InputNumber004Test.java
  primefaces/src/main/java/org/primefaces/validate/bean/PositiveClientValidationConstraint.java
Labels: :lady_beetle: defect

#13707 Chart.js 4.4.9, Moment 0.5.48,
  primefaces/src/main/frontend/package.json
  primefaces/src/main/frontend/yarn.lock
Labels: dependencies, javascript

#13710 Fix #13709: 15.0.4 SelectManyCheckbox doc updates
  docs/15_0_0/components/selectmanycheckbox.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13711 Fix #13709: SelectManyCheckbox doc updates
  docs/15_0_0/components/selectmanycheckbox.md
  docs/16_0_0/components/selectmanycheckbox.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13719 Fix #13715: 15.0.4 IdleMonitor use global storage key
  primefaces/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js
Labels: :lady_beetle: defect

#13720 Fix #13715: IdleMonitor use global storage key
  primefaces/src/main/frontend/packages/idlemonitor/idlemonitor/src/idlemonitor.widget.ts
Labels: :lady_beetle: defect

#13718 Fix #13716: Menu clean up escaping pipe
  primefaces/src/main/frontend/packages/components/src/menu/menu.plainmenu.widget.ts
Labels: :lady_beetle: defect

#13728 Fix #13726: 15.0.4 DatePicker with disable trigger button
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#13729 Fix #13726: DatePicker with disable trigger button
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/datepicker.widget.js
Labels: :lady_beetle: defect

#13733 Fix #13732: Chart update `value` docs
  docs/14_0_0/components/chart.md
  docs/15_0_0/components/chart.md
  docs/16_0_0/components/chart.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13734 Fix #13732: 15.0.4 Chart update `value` docs
  docs/14_0_0/components/chart.md
  docs/15_0_0/components/chart.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13740 Fix #13737: TabView consistent focus highlighting
  primefaces/src/main/frontend/packages/components/src/tabview/tabview.widget.js
Labels: :lady_beetle: defect

#13753 Fix #13751: 15.0.4 Accordion fix TabClose event
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.js
Labels: :lady_beetle: defect

#13749 Fix #13736: Confirm with plain JS type=button
  primefaces/src/main/frontend/packages/components/src/dialog/dialog.widget.ts
Labels: :lady_beetle: defect

#13750 Fix #13736: 15.0.4 Confirm with plain JS type=button
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: :lady_beetle: defect

#13744 Fix #13742: 15.0.4 Datatable emptyMessage fill out colspan for rowGroup
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13757 Fix #13756: SelectOneRadio docs remove grid layout
  docs/15_0_0/components/selectoneradio.md
  docs/16_0_0/components/selectoneradio.md
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: documentation

#13759 Fix #13758: 15.0.4 MegaMenu submenu ids
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
Labels: :lady_beetle: defect

#13760 Fix #13758: MegaMenu submenu ids
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
Labels: :lady_beetle: defect
