Repository primefaces/primefaces, pull requests merged in 2025-03, with the labels that each got.

#13449 Fix #13447: 15.0.1 JPALazyModel enrich results of getRowData
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: :lady_beetle: defect

#13450 Fix #13447: JPALazyModel enrich results of getRowData
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: :lady_beetle: defect

#13474 Fix Firefox test
  primefaces-integration-tests/pom.xml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/autocomplete/AutoComplete005Test.java
  primefaces/src/main/frontend/packages/core/src/core/core.utils.ts
Labels: integration_test

#13464 Fixes #13463 Improve JPALazyDataModel
  docs/16_0_0/components/datatable.md
  primefaces/src/main/java/org/primefaces/model/DefaultLazyDataModel.java
  primefaces/src/main/java/org/primefaces/model/JPALazyDataModel.java
Labels: enhancement

#13472 Fix #13465: 15.0.1 ContextMenu must always be rendered
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
Labels: :lady_beetle: defect

#13473 Fix #13465: ContextMenu must always be rendered
  primefaces/src/main/java/org/primefaces/component/contextmenu/ContextMenuRenderer.java
Labels: :lady_beetle: defect

#13477 Fix #13476: Dialog remain responsive after minimize/maximize
  primefaces/src/main/frontend/packages/components/index.ts
  primefaces/src/main/frontend/packages/components/src/dialog/dialog.widget.ts
Labels: :lady_beetle: defect

#13467 Fix #13462: 15.0.1 SelectCheckboxMenu empty
  docs/14_0_0/components/selectcheckboxmenu.md
  docs/15_0_0/components/selectcheckboxmenu.md
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#13479 Fix #13543: Fix getRowCount for lazy
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/CustomerLazyDataModel.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/datatable/ProgrammingLanguageLazyDataModel.java
  primefaces-integration-tests/src/main/webapp/datatable/dataTable037.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable037Test.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/datatable/HeaderCell.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoComplete.java
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGrid.java
  primefaces/src/main/java/org/primefaces/component/datalist/DataList.java
  primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataView.java
  primefaces/src/main/java/org/primefaces/model/LazyDataModel.java
Labels: :lady_beetle: defect

#13487 Fix #12519: Remove NestedSelectItem/PF
  primefaces/src/main/java/org/primefaces/PF.java
  primefaces/src/main/java/org/primefaces/model/NestedSelectItem.java
Labels: breaking-change

#13493 Fix #13492: 15.0.1 Datatable ignore headerRow when updating visibility
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13494 Fix #13492: Datatable ignore headerRow when updating visibility
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13498 Fix #13441: 15.0.1 FileUpload cancel multiple upload
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect

#13499 Fix #13441: FileUpload cancel multiple upload
  primefaces/src/main/frontend/packages/fileupload/fileupload/src/fileupload.widget.ts
Labels: :lady_beetle: defect

#13503 Fix #13211: FileUpload multiple mode only discard invalid files
  primefaces/src/main/frontend/packages/fileupload/fileupload/src/fileupload.widget.ts
Labels: :lady_beetle: defect

#13510 Fix #13508: Barcode add quiet zone properties
  docs/15_0_0/components/barcode.md
  docs/16_0_0/components/barcode.md
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeBase.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeHandler.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13509 Fix #13508: 15.0.1 Barcode add quiet zone properties
  docs/15_0_0/components/barcode.md
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeBase.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeHandler.java
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13523 Showcase switch primeflex and prismjs to webjars
  docs/16_0_0/core/responsive.md
  primefaces-showcase/pom.xml
  primefaces-showcase/src/main/webapp/WEB-INF/template.xhtml
  primefaces-showcase/src/main/webapp/primeflex/setup.xhtml
  primefaces-showcase/src/main/webapp/resources/showcase/css/primeflex3.css
  primefaces-showcase/src/main/webapp/resources/showcase/script/prism.js
  primefaces-showcase/src/main/webapp/ui/df/level1.xhtml
  primefaces-showcase/src/main/webapp/ui/df/viewResponsive.xhtml
  primefaces-showcase/src/main/webapp/ui/input/manyCheckbox.xhtml
  primefaces-showcase/src/main/webapp/ui/panel/flexGrid.xhtml
Labels: documentation

#13537 Fix #13532: Captcha respect defaults
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaBase.java
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
Labels: :lady_beetle: defect

#13539 Fix #13532: 15.0.1 Captcha respect defaults
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaBase.java
  primefaces/src/main/java/org/primefaces/component/captcha/CaptchaRenderer.java
Labels: :lady_beetle: defect

#13536 Fix #13531: Remove Separator
  docs/15_0_0/components/feedreader.md
  docs/15_0_0/components/menu.md
  docs/15_0_0/components/selectonemenu.md
  docs/15_0_0/components/slidemenu.md
  docs/15_0_0/components/splitbutton.md
  docs/15_0_0/components/sticky.md
  docs/15_0_0/components/tieredmenu.md
  docs/16_0_0/components/feedreader.md
  docs/16_0_0/components/menu.md
  docs/16_0_0/components/selectonemenu.md
  docs/16_0_0/components/separator.md
  docs/16_0_0/components/slidemenu.md
  docs/16_0_0/components/splitbutton.md
  docs/16_0_0/components/sticky.md
  docs/16_0_0/components/tieredmenu.md
  docs/migrationguide/16_0_0.md
  primefaces-integration-tests/src/main/webapp/selectonemenu/selectOneMenu003.xhtml
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/webapp/ui/misc/separator.xhtml
  primefaces-themes/theme-base/components/input/_datepicker.scss
  primefaces-themes/theme-base/components/menu/_menu.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/frontend/packages/components/src/forms/forms.splitbutton.widget.ts
  primefaces/src/main/frontend/packages/components/src/jquery/jquery.ui.datepicker.css
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
  primefaces/src/main/java/org/primefaces/component/megamenu/MegaMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/separator/SeparatorRenderer.java
  primefaces/src/main/java/org/primefaces/component/separator/UISeparator.java
  primefaces/src/main/java/org/primefaces/component/separator/UISeparatorBase.java
  primefaces/src/main/resources/META-INF/faces-config.xml
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: breaking-change

#13543 Fix #13542: MetadataTransformer fix remove handling
  primefaces/src/main/java/org/primefaces/metadata/transformer/MetadataTransformerExecutor.java
Labels: :lady_beetle: defect

#13544 Fix #13542: 15.0.2 MetadataTransformer fix remove handling
  pom.xml
  primefaces-cli/pom.xml
  primefaces-coverage/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-themes/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/metadata/transformer/MetadataTransformerExecutor.java
Labels: :lady_beetle: defect

#13552 Fix #13550: support multiple events for ContextMenu attached to DataTable
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13554 Fix #13550: 15.0.X support multiple events for ContextMenu attached to DataTable
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13558 Fix #13522: GraphicImage default cache to false
  docs/16_0_0/components/graphicimage.md
  docs/migrationguide/16_0_0.md
  primefaces/src/main/java/org/primefaces/component/graphicimage/GraphicImageBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: breaking-change

#13563 Fix #13351: MVS doc update about AJAX and forms
  docs/10_0_0/core/ajaxProcessing.md
  docs/10_0_0/core/multiviewstate.md
  docs/11_0_0/core/ajaxProcessing.md
  docs/11_0_0/core/multiviewstate.md
  docs/12_0_0/core/ajaxProcessing.md
  docs/12_0_0/core/multiviewstate.md
  docs/13_0_0/core/ajaxProcessing.md
  docs/13_0_0/core/multiviewstate.md
  docs/14_0_0/core/ajaxProcessing.md
  docs/14_0_0/core/multiviewstate.md
  docs/15_0_0/core/ajaxProcessing.md
  docs/15_0_0/core/multiviewstate.md
  docs/16_0_0/core/ajaxProcessing.md
  docs/16_0_0/core/multiviewstate.md
Labels: documentation

#13559 Fix #13546: SelectOneRadio clicking already active label should not trigger change
  primefaces/src/main/frontend/packages/components/src/forms/forms.selectoneradio.widget.js
Labels: :lady_beetle: defect

#13560 Fix #13546: 15.0.2 SelectOneRadio clicking already active label should not trigger change
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectoneradio.js
Labels: :lady_beetle: defect

#13568 Fixes #13566 - DatePicker: posting week selection doesnt work
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarJava8View.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
  primefaces/src/test/java/org/primefaces/util/CalendarUtilsTest.java
Labels: :lady_beetle: defect

#13571 Fixes #13566 15.0.2 DatePicker: posting week selection doesnt work
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/input/CalendarJava8View.java
  primefaces-showcase/src/main/webapp/ui/input/datepicker/datePickerJava8.xhtml
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
  primefaces/src/test/java/org/primefaces/util/CalendarUtilsTest.java
Labels: :lady_beetle: defect

#13561 Fix #13538: SplitButton aria menu button fixes
  primefaces/src/main/frontend/packages/components/src/forms/forms.splitbutton.widget.ts
  primefaces/src/main/frontend/packages/core/index.ts
  primefaces/src/main/frontend/packages/core/src/core/core.ts
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
Labels: accessibility

#13562 Fix #13538: 15.0.2 SplitButton aria menu button fixes
  primefaces/src/main/java/org/primefaces/component/splitbutton/SplitButtonRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.splitbutton.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
Labels: accessibility

#13574 Fix #13551: 15.0.2 Accordion dynamic content load send MVS state
  primefaces/src/main/resources/META-INF/resources/primefaces/accordion/accordion.js
Labels: :lady_beetle: defect

#13556 Fix #13548: Barcode be lenient with EAN/UPC check digits
  primefaces-showcase/src/main/webapp/ui/multimedia/barcode.xhtml
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeHandler.java
Labels: :lady_beetle: defect

#13557 Fix #13548: 15.0.2 Barcode be lenient with EAN/UPC check digits
  primefaces-showcase/src/main/webapp/ui/multimedia/barcode.xhtml
  primefaces/src/main/java/org/primefaces/component/barcode/BarcodeHandler.java
Labels: :lady_beetle: defect

#13555 Fix #13521: Tooltip allow multiple events and ESC to close
  primefaces-showcase/src/main/webapp/ui/overlay/tooltip/tooltipOptions.xhtml
  primefaces/src/main/frontend/packages/components/src/tooltip/tooltip.widget.js
Labels: accessibility

#13565 Fix #13521: 15.0.2 Tooltip allow multiple events and ESC to close
  primefaces-showcase/src/main/webapp/ui/overlay/tooltip/tooltipOptions.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js
Labels: accessibility

#13580 Fix #13564: jQuery MouseWheel 3.2.2
  primefaces/src/main/frontend/.yarn/patches/jquery-mousewheel-npm-3.1.13-854d2918be.patch
  primefaces/src/main/frontend/.yarn/patches/jquery-mousewheel-npm-3.1.13-854d2918be.patch.md
  primefaces/src/main/frontend/package.json
  primefaces/src/main/frontend/yarn.lock
Labels: dependencies, javascript

#13589 Fix #13576: 15.0.2 DatePicker use time values on selectDate
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13587 Fix #13576: DatePicker use time values on selectDate
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
Labels: :lady_beetle: defect

#13600 Fix #13593: 15.0.2 DataTable clearFilters() fix
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13601 Fix #13593: DataTable clearFilters() fix
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13604 Fix #13597: InputNumber use default range for numeric type
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect

#13605 Fix #13597: 15.0.2 InputNumber use default range for numeric type
  primefaces/src/main/java/org/primefaces/component/inputnumber/InputNumberRenderer.java
Labels: :lady_beetle: defect

#13611 Fix #13609: 15.0.3 Datatable editing more specific selector
  pom.xml
  primefaces-cli/pom.xml
  primefaces-coverage/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-themes/pom.xml
  primefaces/pom.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13619 Fixes #13608 15.0.3 firstDayWeekOffset not calculated / IndexOfOutBound while submitting
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/test/java/org/primefaces/util/CalendarUtilsTest.java
Labels: :lady_beetle: defect

#13617 Fix spelling
  docs/16_0_0/gettingstarted/whatsnew.md
  docs/migrationguide/16_0_0.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable039Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable048Test.java
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/AutoComplete.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DatePicker.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectCheckboxMenu.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/tree/TreeNode.java
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.css
Labels: documentation

#13622 Fixes #13621 - FileUpload: virusScan/validateContentType attribute has no effect
  docs/15_0_0/components/fileupload.md
  docs/16_0_0/components/fileupload.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#13629 Fix #13620: DataTable: Global select checkbox gets automatically selected when all visible table rows on the current page are selected
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13630 Fix #13620: 15.0.3 DataTable: Global select checkbox gets automatically selected when all visible table rows on the current page are selected
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13626 Fix #13624: 15.0.3 PrimeFaces.escapeClientId handle pipe character
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: :lady_beetle: defect

#13627 Fix #13624: PrimeFaces.escapeClientId handle pipe character
  primefaces/src/main/frontend/packages/core/src/core/core.ts
Labels: :lady_beetle: defect

#13628 Fix #13616: Spinner support right-to-left
  docs/16_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/input/spinner.xhtml
  primefaces-themes/theme-base/components/input/_spinner.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/frontend/packages/components/src/spinner/spinner.css
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerBase.java
  primefaces/src/main/java/org/primefaces/component/spinner/SpinnerRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: enhancement

#13635 Fix #13634: 15.0.3 DatePicker correct display after AJAX update
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13636 Fix #13634: DatePicker correct display after AJAX update
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
Labels: :lady_beetle: defect

#13644 Fix #13642: 15.0.3 Paginator CSS unset width of buttons
  primefaces-themes/theme-base/components/data/_paginator.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: :lady_beetle: defect

#13646 Fix #13641: 15.0.3 SelectCheckBoxMenu fix registering overlay trigger
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js
Labels: :lady_beetle: defect

#13647 Fix #13641: SelectCheckBoxMenu fix registering overlay trigger
  primefaces/src/main/frontend/packages/components/src/forms/forms.selectcheckboxmenu.widget.js
Labels: :lady_beetle: defect

#13575 improve modal dialog scrollability
  docs/migrationguide/16_0_0.md
  primefaces-themes/theme-base/components/overlay/_dialog.scss
  primefaces-themes/themes/primefaces-arya-blue/_variables.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-dark-common/_variables.scss
  primefaces-themes/themes/primefaces-bootstrap4-light-common/_variables.scss
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-common/_variables.scss
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-dark-common/_variables.scss
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-light-common/_variables.scss
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-mytheme/variables/_overlay.scss
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-common/_variables.scss
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/_variables.scss
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/_variables.scss
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/frontend/packages/components/src/core.dialog.ts
  primefaces/src/main/frontend/packages/components/src/dialog/dialog.widget.ts
  primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialog.java
  primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java
  primefaces/src/main/java/org/primefaces/component/dialog/Dialog.java
  primefaces/src/main/java/org/primefaces/component/dialog/DialogRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: breaking-change

#13649 Fix #13645: 15.0.4 Datatable footer missing width styling
  pom.xml
  primefaces-cli/pom.xml
  primefaces-coverage/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-themes/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: :lady_beetle: defect

#13650 Fix #13645: Datatable footer missing width styling
  primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java
Labels: :lady_beetle: defect
