Repository primefaces/primefaces, pull requests merged in 2025-01, with the labels that each got.

#13130 Fix #13129: Add JS utility isVisibleInViewport.
  docs/15_0_0/core/javascriptAPI.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: enhancement

#13133 Fix #12698: Ensure row edited is visible after AJAX
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13134 Fix #12698: 14.0.10 Ensure row edited is visible after AJAX
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13132 Fix #13131: Picklist disable drag/drop on touch devices
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
Labels: enhancement

#13107 Fix #12663: ConfirmDialog/Popup restore original values
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001.java
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/confirmpopup/ConfirmPopup001.java
  primefaces-integration-tests/src/main/webapp/confirmdialog/confirmDialog002.xhtml
  primefaces-integration-tests/src/main/webapp/confirmpopup/confirmPopup001.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog001Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmdialog/ConfirmDialog002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/confirmpopup/ConfirmPopup001Test.java
  primefaces/src/main/java/org/primefaces/component/confirmdialog/ConfirmDialogRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/confirmpopup/confirmpopup.js
  primefaces/src/main/resources/META-INF/resources/primefaces/dialog/dialog.js
Labels: enhancement

#13141 Fix #13140: SelectOneMenu use outerWidth for panel
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#13139 #11364 CSV - complex/multi-value: add showcase-excample
  primefaces-showcase/src/main/java/org/primefaces/showcase/menu/AppMenu.java
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/csv/ComplexValidationView.java
  primefaces-showcase/src/main/webapp/ui/csv/basic.xhtml
  primefaces-showcase/src/main/webapp/ui/csv/complex.xhtml
  primefaces-showcase/src/main/webapp/ui/csv/immediate.xhtml
Labels: documentation

#13151 #13143 Fix AutoComplete disabled opacity
  .gitignore
  primefaces-themes/theme-base/_common.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: :lady_beetle: defect

#13149 Fix #12754: DatePicker fire onChange if mask is used
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13156 Fix #13152: 14.0.11 SelectOneMenu scrollbar issues with long option l…
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#13161 Fix #13159: DataTable rowEditing="true" must enable cells
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13160 Fix #13159: 14.0.11 DataTable rowEditing="true" must enable cells
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13162 Fix #13147: 14.0.11 Menu toggleEvent hover do not allow click
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#13163 Fix #13147: Menu toggleEvent hover do not allow click
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#13165 Fix #13164: 14.0.11 Menu remove mouseleave stopPropagation
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#13166 Fix #13164: Menu remove mouseleave stopPropagation
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: :lady_beetle: defect

#13155 Fix #13154: DatePicker w/mask only fire change if changed
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13157 Fix #13154: 14.0.11 DatePicker w/mask only fire change if changed
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13175 Selenium: deprecated getAttribute
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/AccordionPanel.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/AutoComplete.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Button.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/CascadeSelect.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/CommandLink.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/DataView.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/FileUpload.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Messages.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/OutputLabel.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/PickList.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectBooleanButton.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectManyCheckbox.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectManyMenu.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectOneButton.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectOneMenu.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/SelectOneRadio.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/TabView.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/Tree.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/TriStateCheckbox.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/AbstractComponent.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/AbstractInputComponent.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/AbstractToggleComponent.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/base/ComponentUtils.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/html/Link.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/html/SelectOneMenu.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/datatable/Row.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/tree/TreeNode.java
  primefaces-selenium/primefaces-selenium-components/src/main/java/org/primefaces/selenium/component/model/treetable/Row.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePageFragment.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePageTest.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeSelenium.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/findby/FindByParentPartialIdElementLocator.java
Labels: integration_test

#13172 Fix #13168: Menu highlight on hover but don't steal focus
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: accessibility

#13171 Fix #13168: 14.0.11 Menu highlight on hover but don't steal focus
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.menubar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/menu/menu.tieredmenu.js
Labels: accessibility

#13183 Fix #13182: DatePicker timeinput allow selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13184 Fix #13182: 14.0.11 DatePicker timeinput allow selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13186 #13185 - WidgetVar: improve performance by resolve it on the client side
  primefaces/src/main/java/org/primefaces/expression/WidgetVarSearchKeywordResolver.java
  primefaces/src/main/java/org/primefaces/expression/WidgetVarVisitCallback.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.expressions.js
Labels: :zap: performance

#13179 #13178 PF Selenium: Selenium deprecated WebStorage - abstraction
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/AbstractPrimePage.java
  primefaces-selenium/primefaces-selenium-core/src/main/java/org/primefaces/selenium/PrimeSelenium.java
Labels: integration_test

#13195 Fixes #13193
  docs/15_0_0/core/dynamiccontentstreaming.md
  primefaces-showcase/src/main/java/org/primefaces/showcase/view/multimedia/DynamicGalleriaView.java
  primefaces/src/main/java/org/primefaces/model/DefaultStreamedContent.java
Labels: :lady_beetle: defect

#13196 Fix #13191: 14.0.11 ComponentUtils allow flex="false"
  primefaces/src/main/java/org/primefaces/component/api/FlexAware.java
  primefaces/src/main/java/org/primefaces/component/datagrid/DataGridBase.java
  primefaces/src/main/java/org/primefaces/component/dataview/DataViewBase.java
  primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerBase.java
  primefaces/src/main/java/org/primefaces/component/orderlist/OrderListBase.java
  primefaces/src/main/java/org/primefaces/component/selectmanycheckbox/SelectManyCheckboxBase.java
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioBase.java
  primefaces/src/main/java/org/primefaces/util/ComponentUtils.java
Labels: :lady_beetle: defect

#13201 Fix #13182: DatePicker time input separate keydown/keyup
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13202 Fix #13182: 14.0.11 DatePicker time input separate keydown/keyup
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13197 Fix #13188: Wizard add reset() widget method
  docs/14_0_0/components/wizard.md
  docs/15_0_0/components/wizard.md
  primefaces-showcase/src/main/webapp/ui/panel/wizard.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js
Labels: enhancement

#13198 Fix #13188: 14.0.11 Wizard add reset() widget method
  docs/14_0_0/components/wizard.md
  primefaces-showcase/src/main/webapp/ui/panel/wizard.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js
Labels: enhancement

#13199 Fix #13189: PrimeFaces.debounce utility function
  docs/15_0_0/components/datatable.md
  docs/15_0_0/core/javascriptAPI.md
  primefaces-showcase/src/main/webapp/ui/data/datatable/crud.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/filter.xhtml
  primefaces-showcase/src/main/webapp/ui/data/datatable/multiViewState.xhtml
  primefaces-showcase/src/main/webapp/ui/data/treetable/filter.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
  primefaces/src/main/resources/META-INF/resources/primefaces/picklist/picklist.js
  primefaces/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js
  primefaces/src/main/resources/META-INF/resources/primefaces/treetable/treetable.js
Labels: enhancement

#13206 Fix #13182: DatePicker allow ENTER accept time input and close overlay
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13204 #12460
  docs/15_0_0/core/dynamiccontentstreaming.md
  docs/15_0_0/gettingstarted/configuration.md
  primefaces/src/main/java/org/primefaces/config/PrimeConfiguration.java
  primefaces/src/main/java/org/primefaces/util/Constants.java
  primefaces/src/main/java/org/primefaces/util/DynamicContentSrcBuilder.java
Labels: enhancement

#13207 Exclude Docker-Java from WebDriverMananager
  primefaces-selenium/primefaces-selenium-core/pom.xml
Labels: integration_test

#13208 Docs: Add instructions for creating a theme, add community project
  docs/15_0_0/core/themes.md
  docs/15_0_0/gettingstarted/community.md
Labels: documentation

#13213 Fix #13182: 14.0.11 DatePicker allow CTRL+Z in time input
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13214 Fix #13182: DatePicker allow CTRL+Z in time input
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13229 Fix #13223: SelectCheckBoxMenu 14.0.0 migration guide
  docs/migrationguide/14_0_0.md
Labels: documentation

#13226 Fix #13225: 14.0.11 DatePicker escape aria-label
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13227 Fix #13225: DatePicker escape aria-label
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13218 Fix #13217: 14.0.11 FileUpload simple mode onstart callback
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
Labels: :lady_beetle: defect

#13219 Fix #13217: FileUpload simple mode onstart callback
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
Labels: :lady_beetle: defect

#13233 Fix #13232: SelectCheckBoxMenu add showSelectAll
  docs/15_0_0/components/selectcheckboxmenu.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces-showcase/src/main/webapp/ui/input/checkboxMenu.xhtml
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuBase.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: enhancement

#13221 Fix #13220: 14.0.11 FileUpload add ignoreAutoUpdate property
  docs/14_0_0/components/fileupload.md
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
Labels: enhancement

#13222 Fix #13220: FileUpload add ignoreAutoUpdate property
  docs/14_0_0/components/fileupload.md
  docs/15_0_0/components/fileupload.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadBase.java
  primefaces/src/main/java/org/primefaces/component/fileupload/FileUploadRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.ajax.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/3-fileupload.simple.js
Labels: enhancement

#13238 Fix #13237: 14.0.11 ClamAV downgrade logger INFO to FINE
  primefaces/src/main/java/org/primefaces/virusscan/impl/ClamDaemonScanner.java
Labels: :lady_beetle: defect

#13240 Fix #13236: 14.0.11 DataTable ignore non selectable rows during selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13241 Fix #13236: DataTable ignore non selectable rows during selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13249 Fix #13209: Improve formatBytes for localization
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: enhancement

#13252 Fix #13251: 14.0.11 DatePicker yearnavigator in month view
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13253 Fix #13251: DatePicker yearnavigator in month view
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13250 #13230, #13224 - allowType error message improvements
  primefaces/src/main/java/org/primefaces/util/FileUploadUtils.java
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/test/java/org/primefaces/util/FileUploadUtilsTest.java
Labels: enhancement

#13261 Fix #13258: 14.0.11 Turkish clear translation update
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
Labels: documentation

#13262 Fix #13258: Turkish clear translation update
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
Labels: documentation

#13260 Fix #13259: Wizard add highlightCompletedSteps
  docs/14_0_0/components/wizard.md
  docs/15_0_0/components/wizard.md
  docs/15_0_0/gettingstarted/whatsnew.md
  primefaces/src/main/java/org/primefaces/component/wizard/WizardBase.java
  primefaces/src/main/java/org/primefaces/component/wizard/WizardRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js
Labels: enhancement

#13265 Fix #13259: 14.0.11 Wizard add highlightCompletedSteps
  docs/14_0_0/components/wizard.md
  primefaces/src/main/java/org/primefaces/component/wizard/WizardBase.java
  primefaces/src/main/java/org/primefaces/component/wizard/WizardRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/wizard/wizard.js
Labels: enhancement

#13272 Fix #13268: 14.0.12 Dialog improve focus trap
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#13273 Fix #13268: Dialog improve focus trap
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#13282 Fix #13281: SelectOneListbox move aria-activedescendent to client
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectlistbox.js
Labels: :lady_beetle: defect

#13270 Fix #13269: 14.0.12 DatePicker onChange with CSP
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#13271 Fix #13269: DatePicker onChange with CSP
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/1-datepicker.js
Labels: :lady_beetle: defect

#13284 Fix #13283: CSP Ajax False
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.csp.js
Labels: :lady_beetle: defect

#13279 Fix #13278: InputTextArea handle UTF-8 and emojis
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
Labels: :lady_beetle: defect

#13280 Fix #13278: 14.0.12 InputTextArea handle UTF-8 and emojis
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.inputtextarea.js
Labels: :lady_beetle: defect

#13275 Fix #13274: BlockUI switch to ResizeObserver/MutationObserver
  primefaces-showcase/src/main/webapp/ui/misc/blockUI.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#13276 Fix #13274: 14.0.12 BlockUI switch to ResizeObserver/MutationObserver
  primefaces-showcase/src/main/webapp/ui/misc/blockUI.xhtml
  primefaces/src/main/resources/META-INF/resources/primefaces/blockui/blockui.js
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect
