Repository primefaces/primefaces, pull requests merged in 2025-05, with the labels that each got.

#13763 Fix #13730: 15.0.4 ProgressBar 0% alignment with PrimeReact
  primefaces/src/main/resources/META-INF/resources/primefaces/progressbar/progressbar.js
Labels: :lady_beetle: defect

#13679 Fix #13678: 15.0.4 Exporter fix for LazyModel
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java
Labels: :lady_beetle: defect

#13680 Fix #13678: Exporter fix for LazyModel
  primefaces/src/main/java/org/primefaces/component/datatable/export/DataTableExporter.java
Labels: :lady_beetle: defect

#13762 fix #13761 - ensure MVS keys are reset only for the current view
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
Labels: :lady_beetle: defect

#13767 Fix #13761 - 15.0.4 ensure MVS keys are reset only for the current view
  primefaces/src/main/java/org/primefaces/PrimeFaces.java
Labels: :lady_beetle: defect

#13770 Fix #13768: 15.0.4 Datatable checkbox rows in range use silent selection
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13777 Fix #13773: 15.0.4 ProgressBar improve label handling
  primefaces/src/main/resources/META-INF/resources/primefaces/progressbar/progressbar.js
Labels: :lady_beetle: defect

#13776 Fix #13774 15.0.4 Calendar/DatePicker: does not support timeOnly corectly with SQL time
  primefaces/src/main/java/org/primefaces/util/CalendarUtils.java
Labels: :lady_beetle: defect

#13783 Fix #13782: CSP ReportOnlyPolicy fix
  primefaces/src/main/java/org/primefaces/csp/CspPhaseListener.java
Labels: :lady_beetle: defect

#13784 Fix #13782: 15.0.5 CSP ReportOnlyPolicy fix
  pom.xml
  primefaces-cli/pom.xml
  primefaces-coverage/pom.xml
  primefaces-integration-tests-jakarta/pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-selenium/pom.xml
  primefaces-selenium/primefaces-selenium-components/pom.xml
  primefaces-selenium/primefaces-selenium-core/pom.xml
  primefaces-showcase/pom.xml
  primefaces-themes/pom.xml
  primefaces/pom.xml
  primefaces/src/main/java/org/primefaces/csp/CspPhaseListener.java
Labels: :lady_beetle: defect

#13795 Fix #13789: Autocomplete size docs
  docs/10_0_0/components/autocomplete.md
  docs/11_0_0/components/autocomplete.md
  docs/12_0_0/components/autocomplete.md
  docs/13_0_0/components/autocomplete.md
  docs/14_0_0/components/autocomplete.md
  docs/15_0_0/components/autocomplete.md
  docs/16_0_0/components/autocomplete.md
Labels: documentation

#13797 Fix #13790: 15.0.5 GraphicImage render alt="" when alt is not set
  primefaces/src/main/java/org/primefaces/component/graphicimage/GraphicImageRenderer.java
Labels: accessibility

#13798 Fix #13793: 15.0.5 Carousel add aria-labels
  primefaces/src/main/resources/META-INF/resources/primefaces/carousel/carousel.js
Labels: accessibility

#13799 Fix #13793: Carousel add aria-labels
  primefaces/src/main/frontend/packages/components/src/carousel/carousel.widget.js
Labels: accessibility

#13800 Fix #13791: 15.0.5 Timeline delay context menu until rendered
  primefaces/src/main/resources/META-INF/resources/primefaces/timeline/1-timeline.js
Labels: :lady_beetle: defect

#13807 Fix #13802: 15.0.5 Schedule ignoreAutoUpdate on core fetch events
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js
Labels: :lady_beetle: defect

#13808 Fix #13792: 15.0.5 CSS Transition use UI Delay not MicroTask
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.utils.js
Labels: :lady_beetle: defect

#13811 Fix #13810: 15.0.5 SelectOne add autocomplete property for editable input
  docs/15_0_0/components/selectonemenu.md
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuBase.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13812 Fix #13810: SelectOne add autocomplete property for editable input
  docs/15_0_0/components/selectonemenu.md
  docs/16_0_0/components/selectonemenu.md
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuBase.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13816 Vis Timeline 7.7.4
  primefaces/src/main/frontend/package.json
  primefaces/src/main/frontend/yarn.lock
Labels: dependencies

#13822 Add 'Unsupported features' to JPALazyDataModel docs
  docs/15_0_0/components/datatable.md
  docs/16_0_0/components/datatable.md
Labels: documentation

#13814 Fix #13813: 15.0.5 TristateCheckbox ARIA accessibility
  primefaces/src/main/resources/META-INF/resources/primefaces/tristatecheckbox/tristatecheckbox.js
Labels: accessibility

#13815 Fix #13813: TristateCheckbox ARIA accessibility
  primefaces/src/main/frontend/packages/components/src/tristatecheckbox/tristatecheckbox.widget.js
Labels: accessibility

#13820 Fix #13817: 15.0.5 FileUpload prevent any uploads if max exceeded on auto
  primefaces/src/main/resources/META-INF/resources/primefaces/fileupload/2-fileupload.js
Labels: :lady_beetle: defect

#13821 Fix #13817: FileUpload prevent any uploads if max exceeded on auto
  primefaces/src/main/frontend/packages/fileupload/fileupload/src/fileupload.widget.ts
Labels: :lady_beetle: defect

#13829 Fix #13826 15.0.5 Add ui-widget class to ScheduleRenderer
  primefaces/src/main/java/org/primefaces/component/schedule/ScheduleRenderer.java
Labels: :lady_beetle: defect

#13851 Fix #13847/#13848/#13849: ARIA accessibility issues
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datepicker/DatePicker001Test.java
  primefaces/src/main/frontend/packages/components/src/autocomplete/autocomplete.widget.js
  primefaces/src/main/frontend/packages/components/src/forms/forms.selectlistbox.widget.js
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
Labels: accessibility

#13856 Fix #13846: DatePicker improve accessibility of date cells
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
Labels: accessibility

#13867 Fix #13854: 15.0.5 Table render with ARIA role="group"
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
Labels: accessibility

#13866 Fix #13854: Table render with ARIA role="group"
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/java/org/primefaces/component/cascadeselect/CascadeSelectRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectcheckboxmenu/SelectCheckboxMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectmanymenu/SelectManyMenuRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
  primefaces/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java
  primefaces/src/main/java/org/primefaces/renderkit/InputRenderer.java
  primefaces/src/main/java/org/primefaces/util/HTML.java
Labels: accessibility

#13864 Fix #13861: 15.0.5 TreeTable fix header title
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#13865 Fix #13861: TreeTable fix header title
  primefaces/src/main/java/org/primefaces/component/treetable/TreeTableRenderer.java
Labels: :lady_beetle: defect

#13872 Fix #13869: 15.0.5 Datatable responsive with expander fix
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13878 Fix #13876 15.0.5 DefaultCommand: Infinite recursion when scope is the same as parent form
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
Labels: :lady_beetle: defect
