Repository primefaces/primefaces, pull requests merged in 2025-02, with the labels that each got.

#13291 Fix #13288: SelectOneRadio prevent unclickable gap
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#13292 Fix #13288: 14.0.12 SelectOneRadio prevent unclickable gap
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.css
Labels: :lady_beetle: defect

#13290 Wizard example add p:focus to focus first element on each tab change
  primefaces-showcase/src/main/webapp/ui/panel/wizard.xhtml
Labels: documentation

#13293 Fix PrimeFaces.resources.isExtensionMapping
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.resources.js
Labels: :lady_beetle: defect

#13294 14.0.12 Fix PrimeFaces.resources.isExtensionMapping
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.resources.js
Labels: :lady_beetle: defect

#13286 Fix #13285: DatePicker default time pickers to view date
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13287 Fix #13285: 14.0.12 DatePicker default time pickers to view date
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13304 Fix #13303: Locale previousPageLabel to prevPageLabel
  docs/15_0_0/core/localization.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ar.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bg.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bn.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-bs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ca.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ckb.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-cs.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-da.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-el.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-en.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-es.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fa.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-fr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-he.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-hu.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-in.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-it.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ja.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-kk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-km.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ko.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ky.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-lv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ms.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-nl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-no.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pt.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ro.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-ru.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sl.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-sv.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-th.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-tr.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uk.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-uz.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-vi.js
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-zh.js
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: documentation

#13297 Fix #13295: RemoteCommand treat object like h:commandScript
  primefaces-showcase/src/main/webapp/ui/ajax/remoteCommand.xhtml
  primefaces/src/main/java/org/primefaces/util/AjaxRequestBuilder.java
Labels: :lady_beetle: defect

#13296 Fix #13295: 14.0.12 RemoteCommand treat object like h:commandScript
  primefaces-showcase/src/main/webapp/ui/ajax/remoteCommand.xhtml
  primefaces/src/main/java/org/primefaces/util/AjaxRequestBuilder.java
Labels: :lady_beetle: defect

#13309 #13278: Textarea, countBytesAsChars, Integrationtests
  primefaces-integration-tests/src/main/java/org/primefaces/integrationtests/iputtextarea/InputTextArea002.java
  primefaces-integration-tests/src/main/webapp/inputtextarea/inputTextArea003.xhtml
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/inputtextarea/InputTextArea003Test.java
Labels: integration_test

#13307 Fix #13300: 14.0.12 AjaxStatus handle f:ajax and p:ajax
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
Labels: :lady_beetle: defect

#13301 Fix #13300: AjaxStatus handle f:ajax and p:ajax
  primefaces/src/main/resources/META-INF/resources/primefaces/ajaxstatus/ajaxstatus.js
Labels: :lady_beetle: defect

#13308 Remove PrimeFaces.setCaretToEnd JS method
  docs/migrationguide/15_0_0.md
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.js
Labels: breaking-change

#13302 Fix #13299: Paginator convert links to buttons
  docs/migrationguide/15_0_0.md
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/datatable/DataTable046Test.java
  primefaces-themes/themes/primefaces-arya-blue/_variables.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-common/_variables.scss
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-mytheme/variables/_data.scss
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-common/_variables.scss
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/_variables.scss
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/_variables.scss
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/java/org/primefaces/component/api/UIPageableData.java
  primefaces/src/main/java/org/primefaces/component/paginator/PageLinkRenderer.java
  primefaces/src/main/java/org/primefaces/component/paginator/PageLinksRenderer.java
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js
Labels: breaking-change

#13316 Fix #13215: German translation updates
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
Labels: enhancement

#13317 Fix #13315: 14.0.12 German translation updates
  primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-de.js
  primefaces/src/main/resources/org/primefaces/Messages_de.properties
Labels: enhancement

#13325 Fix #13321: AutoComplete reinstate `emptyMessage` property
  docs/15_0_0/components/autocomplete.md
  docs/migrationguide/15_0_0.md
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteBase.java
  primefaces/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
  primefaces/src/main/resources/META-INF/resources/primefaces/autocomplete/autocomplete.js
Labels: enhancement

#13328 Fix #13327: 14.0.12 SelectOneRadio restore aria-checked
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility

#13329 Fix #13327: SelectOneRadio restore aria-checked
  primefaces/src/main/java/org/primefaces/component/selectoneradio/SelectOneRadioRenderer.java
Labels: accessibility

#13334 Fix #13330 14.0.12 SelectCheckboxMenu002Test#submitEmptyLabel for Chr…
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/selectcheckboxmenu/SelectCheckboxMenu002Test.java
Labels: integration_test

#13336 Fix #13335: 14.0.12 SelectOneMenu respect escape for title
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#13337 Fix #13335: SelectOneMenu respect escape for title
  primefaces/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js
Labels: :lady_beetle: defect

#13349 Fix #13347: Add CycloneDX SBOM
  primefaces/pom.xml
Labels: :lock: security

#13350 Fix #13347: 15.0.1 Add CycloneDX SBOM
  primefaces/pom.xml
Labels: :lock: security

#13352 Fix #13348: DatePicker CSP on responsive UI changes
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13351 Fix #13348: 15.0.1 DatePicker CSP on responsive UI changes
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13356 Fix #13355: 15.0.1 Toolbar must check each group for a rendered component
  primefaces/src/main/java/org/primefaces/component/toolbar/ToolbarRenderer.java
Labels: :lady_beetle: defect

#13357 Fix #13355: Toolbar must check each group for a rendered component
  primefaces/src/main/java/org/primefaces/component/toolbar/ToolbarRenderer.java
Labels: :lady_beetle: defect

#13366 Fix #13363: ColumnToggler selectAll checkbox UI fix
  primefaces/src/main/frontend/packages/components/src/columntoggler/columntoggler.widget.js
Labels: :lady_beetle: defect

#13369 Fix #13348: DatePicker CSP on responsive UI changes
  primefaces/src/main/frontend/packages/datepicker/datepicker/src/jquery.ui.prime.datepicker.cjs
Labels: :lady_beetle: defect

#13370 Fix #13348: 15.0.1 DatePicker CSP on responsive UI changes
  primefaces/src/main/resources/META-INF/resources/primefaces/datepicker/0-datepicker.js
Labels: :lady_beetle: defect

#13376 ValidateFile update docs
  docs/14_0_0/components/fileupload.md
  docs/14_0_0/validators/validateFile.md
  docs/15_0_0/components/fileupload.md
  docs/15_0_0/validators/validateFile.md
  docs/16_0_0/components/fileupload.md
  docs/16_0_0/validators/validateFile.md
Labels: documentation

#13380 Fix #13377: 15.0.1 SelectOneListBox ARIA moved to client side
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
Labels: :lady_beetle: defect

#13384 Fix #13346: 15.0.1 Schedule events must be called after the viewChange event is fired
  primefaces/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js
Labels: :lady_beetle: defect

#13381 Fix #13377: SelectOneListBox ARIA moved to client side
  primefaces/src/main/java/org/primefaces/component/selectonelistbox/SelectOneListboxRenderer.java
Labels: :lady_beetle: defect

#13393 Fix #13388: Integration Test fixes
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv002Test.java
  primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/csv/Csv003Test.java
Labels: integration_test

#13392 Fix #13389: 15.0.1 CSV allow p:message
  primefaces/src/main/resources/META-INF/resources/primefaces/validation/validation.common.js
Labels: :lady_beetle: defect

#13410 Fix #13396: DatePicker improve responsiveness on smallest displays
  primefaces-themes/theme-base/components/input/_datepicker.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: :lady_beetle: defect

#13411 Fix #13396: 15.0.1 DatePicker improve responsiveness on smallest displays
  primefaces-themes/theme-base/components/input/_datepicker.scss
  primefaces-themes/themes/primefaces-arya-blue/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-blue-light/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-dark/theme.css
  primefaces-themes/themes/primefaces-bootstrap4-purple-light/theme.css
  primefaces-themes/themes/primefaces-luna-amber/theme.css
  primefaces-themes/themes/primefaces-luna-blue/theme.css
  primefaces-themes/themes/primefaces-luna-green/theme.css
  primefaces-themes/themes/primefaces-luna-pink/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-compact-indigo-light/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-dark/theme.css
  primefaces-themes/themes/primefaces-material-deeppurple-light/theme.css
  primefaces-themes/themes/primefaces-material-indigo-dark/theme.css
  primefaces-themes/themes/primefaces-material-indigo-light/theme.css
  primefaces-themes/themes/primefaces-mytheme/theme.css
  primefaces-themes/themes/primefaces-nova-colored/theme.css
  primefaces-themes/themes/primefaces-nova-dark/theme.css
  primefaces-themes/themes/primefaces-nova-light/theme.css
  primefaces-themes/themes/primefaces-saga-blue/theme.css
  primefaces-themes/themes/primefaces-vela-blue/theme.css
  primefaces/src/main/resources/META-INF/resources/primefaces-saga-blue/theme.css
Labels: :lady_beetle: defect

#13409 Fix #13406: Datatable select checkbox with keyboard
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13408 Fix #13406: 15.0.1 Datatable select checkbox with keyboard
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13428 Fix #13427: DataView missing rowIndexVar in taglib
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13429 Fix #13427: 15.0.1 DataView missing rowIndexVar in taglib
  primefaces/src/main/resources/META-INF/primefaces.taglib.xml
Labels: :lady_beetle: defect

#13425 Fix #13406: Checkbox selection keyboard navigation
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13426 Fix #13406: 15.0.1 Checkbox selection keyboard navigation
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13431 Fix #13419: 15.0.1 Datatable rowEdit specific selector
  primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js
Labels: :lady_beetle: defect

#13432 Fix #13419: Datatable rowEdit specific selector
  primefaces/src/main/frontend/packages/components/src/datatable/datatable.widget.js
Labels: :lady_beetle: defect

#13440 Fix #13438: IdleMonitor stack overflow
  primefaces/src/main/frontend/packages/core/src/core/core.widget.js
  primefaces/src/main/frontend/packages/idlemonitor/idlemonitor/src/idlemonitor.widget.js
Labels: :lady_beetle: defect

#13439 Fix #13438: 15.0.1 IdleMonitor stack overflow
  primefaces/src/main/resources/META-INF/resources/primefaces/core/core.widget.js
  primefaces/src/main/resources/META-INF/resources/primefaces/idlemonitor/1-idlemonitor.js
Labels: :lady_beetle: defect

#13437 Slf4J version in one spot
  pom.xml
  primefaces-integration-tests/pom.xml
  primefaces-showcase/pom.xml
  primefaces/pom.xml
Labels: dependencies

#13451 Fix #13448: 15.0.1 ResetInput showcase messages
  primefaces-showcase/src/main/webapp/ui/misc/resetInput.xhtml
Labels: documentation

#13452 Fix #13448: ResetInput showcase messages
  primefaces-showcase/src/main/webapp/ui/misc/resetInput.xhtml
Labels: documentation
